import type { Course } from "@/lib/types";

export const cppToJavascript: Course = {
  id: "cpp-to-javascript",
  knownLang: "cpp",
  targetLang: "javascript",
  title: "C++ → JavaScript",
  modules: [
    // ===================== BEGINNER =====================
    {
      id: "cpp-js-variables",
      title: "Variables & Types",
      tagline: "Dynamic typing, `let`/`const`, and no headers.",
      icon: "🏰",
      level: "beginner",
      order: 1,
      requires: [],
      rewardXp: 60,
      lessons: [
        {
          id: "lesson-cpp-js-vars-1",
          title: "Dynamic typing with let and const",
          intro: "JavaScript is dynamically typed — no type annotations. Variables are declared with `let` (mutable) or `const` (immutable binding). `var` is legacy and function-scoped (avoid it). JavaScript has 7 primitive types: `number`, `string`, `boolean`, `null`, `undefined`, `symbol`, `bigint`. Everything else is an object.",
          comparisons: [
            { concept: "Variable declaration", knownCode: "int count = 0;\ncount = count + 1;", targetCode: "let count = 0;\ncount = count + 1;", note: "`let` for mutable, `const` for immutable. No type annotation." },
            { concept: "Constants", knownCode: "const double PI = 3.14159;", targetCode: "const PI = 3.14159;", note: "`const` prevents reassignment but NOT deep mutation of objects." },
            { concept: "No integer type", knownCode: "int a = 5;\ndouble b = 5.0;", targetCode: "const a = 5;    // All numbers are IEEE 754 doubles\nconst b = 5.0;  // Same thing!", note: "JavaScript has only `number` (64-bit float). Use `BigInt` for arbitrary precision." },
          ],
          realWorld: "Modern JS: always `const` by default, `let` when reassignment is needed. Never `var`.",
          exercise: { id: "ex-cpp-js-vars-1", prompt: 'Declare a `const` variable `greeting` set to "world" and log it.', starterCode: '// const greeting = ...\n', solution: 'const greeting = "world";\nconsole.log(greeting);', expectedOutputIncludes: "world", xp: 20 },
        },
        {
          id: "lesson-cpp-js-vars-2",
          title: "Type coercion and equality",
          intro: "JavaScript does implicit type coercion — `\"5\" + 1` gives `\"51\"` (string), but `\"5\" - 1` gives `4` (number). This is one of JS's biggest footguns. Always use `===` (strict equality) instead of `==` (loose equality with coercion).",
          comparisons: [
            { concept: "Equality", knownCode: "if (a == b) { ... }  // Always strict in C++", targetCode: 'if (a === b) { ... }  // Strict — no coercion\n// "5" == 5 is true (bad!)\n// "5" === 5 is false (good!)', note: "Always use `===` and `!==` in JavaScript." },
            { concept: "Type checking", knownCode: "// Compile-time type checking", targetCode: 'typeof x        // "number", "string", "boolean", etc.\nx instanceof Array  // true/false', note: "`typeof null` is `\"object\"` — a famous JS bug." },
          ],
          realWorld: "ESLint's `eqeqeq` rule enforces `===` in all professional codebases.",
          exercise: { id: "ex-cpp-js-vars-2", prompt: 'What does `typeof 42` return? Log it.', starterCode: '// Log typeof 42\n', solution: 'console.log(typeof 42);', expectedOutputIncludes: "number", xp: 15 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-cpp-js-var-1", prompt: "Which keyword should you use by default for variables?", choices: ["var", "let", "const", "int"], correctIndex: 2, explanation: "Use `const` by default; `let` only when reassignment is needed.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-var-2", prompt: "JavaScript's number type is…", choices: ["32-bit integer", "64-bit double (IEEE 754)", "Arbitrary precision", "Platform dependent"], correctIndex: 1, explanation: "All numbers are 64-bit floating point. Use `BigInt` for integers larger than 2^53.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-var-3", prompt: "What does `===` do vs `==`?", choices: ["Same thing", "`===` compares without type coercion", "`==` is faster", "`===` is deprecated"], correctIndex: 1, explanation: "`===` is strict equality — no type coercion. Always prefer it.", xp: 10 },
        { kind: "debug", id: "q-cpp-js-var-4", prompt: "Why does this log `true`?", brokenCode: 'console.log("5" == 5);', choices: ["`==` coerces types — use `===` instead", "All comparisons return true", "Strings equal their numeric value", "console.log always prints true"], correctIndex: 0, explanation: "`==` converts the string to a number before comparing. Use `===`.", xp: 15 },
        { kind: "mcq", id: "q-cpp-js-var-5", prompt: "What is `undefined` in JavaScript?", choices: ["Same as null", "A variable declared but never assigned a value", "An error state", "A falsy number"], correctIndex: 1, explanation: "`undefined` means 'never assigned'. `null` means 'explicitly nothing'.", xp: 10 },
      ],
    },
    {
      id: "cpp-js-controlflow",
      title: "Control Flow",
      tagline: "Familiar braces with some truthy surprises.",
      icon: "🛡️",
      level: "beginner",
      order: 2,
      requires: ["cpp-js-variables"],
      rewardXp: 70,
      lessons: [
        {
          id: "lesson-cpp-js-cf-1",
          title: "Conditionals and truthiness",
          intro: "JavaScript's `if/else if/else` looks identical to C++. The key difference: JavaScript has 'truthiness'. Six values are falsy: `false`, `0`, `\"\"`, `null`, `undefined`, `NaN`. Everything else is truthy — including `\"false\"`, `[]`, and `{}`.",
          comparisons: [
            { concept: "if/else", knownCode: 'if (score > 90) {\n    std::cout << "A";\n} else if (score > 75) {\n    std::cout << "B";\n}', targetCode: 'if (score > 90) {\n    console.log("A");\n} else if (score > 75) {\n    console.log("B");\n}', note: "Nearly identical syntax. `console.log` replaces `std::cout`." },
            { concept: "Truthiness", knownCode: "if (ptr) { ... }  // Checks non-null", targetCode: 'if (name) { ... }  // Truthy check\n// Falsy: false, 0, "", null, undefined, NaN', note: "Empty string is falsy. Empty array `[]` is truthy!" },
            { concept: "Optional chaining + nullish coalescing", knownCode: "// C++ has no equivalent", targetCode: 'const city = user?.address?.city ?? "Unknown";', note: "`?.` stops if null/undefined. `??` provides a default for null/undefined only." },
          ],
          realWorld: "Optional chaining (`?.`) and nullish coalescing (`??`) are used everywhere in modern JS. They replaced dozens of lines of null-checking code.",
          exercise: { id: "ex-cpp-js-cf-1", prompt: "Given `n = 7`, log 'even' if divisible by 2, otherwise 'odd'.", starterCode: "const n = 7;\n// Branch here\n", solution: "const n = 7;\nif (n % 2 === 0) {\n    console.log('even');\n} else {\n    console.log('odd');\n}", expectedOutputIncludes: "odd", xp: 25 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-cpp-js-cf-1", prompt: "Which value is truthy in JavaScript?", choices: ["0", '""', "null", '[]'], correctIndex: 3, explanation: "Empty array is truthy! Only `false`, `0`, `\"\"`, `null`, `undefined`, `NaN` are falsy.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-cf-2", prompt: "What does `??` do?", choices: ["Logical OR", "Returns right side only if left is null or undefined", "Throws an error", "Same as ||"], correctIndex: 1, explanation: "`??` is nullish coalescing. `||` returns right side for any falsy value.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-cf-3", prompt: "What does `user?.name` do?", choices: ["Accesses name or throws", "Accesses name or returns undefined (no error)", "Creates a new property", "Deletes the property"], correctIndex: 1, explanation: "Optional chaining returns `undefined` if `user` is null/undefined.", xp: 10 },
        { kind: "debug", id: "q-cpp-js-cf-4", prompt: "Why does this always log 'truthy'?", brokenCode: 'const x = "false";\nif (x) {\n    console.log("truthy");\n}', choices: ["Any non-empty string is truthy — even \"false\"", "x is a boolean", "if always evaluates to true", "Missing ==="], correctIndex: 0, explanation: '`"false"` is a non-empty string, which is truthy. Compare explicitly: `x === "true"`.', xp: 15 },
        { kind: "mcq", id: "q-cpp-js-cf-5", prompt: "How many falsy values does JavaScript have?", choices: ["2", "4", "6", "8"], correctIndex: 2, explanation: "Six: `false`, `0`, `\"\"`, `null`, `undefined`, `NaN`.", xp: 10 },
      ],
    },
    {
      id: "cpp-js-loops",
      title: "Loops & Iteration",
      tagline: "`for...of`, `for...in`, and array methods.",
      icon: "🌀",
      level: "beginner",
      order: 3,
      requires: ["cpp-js-controlflow"],
      rewardXp: 80,
      lessons: [
        {
          id: "lesson-cpp-js-loops-1",
          title: "Iterating in JavaScript",
          intro: "JavaScript has multiple loop styles: classic `for`, `for...of` (values of iterables), `for...in` (keys of objects), and array methods (`.forEach`, `.map`, `.filter`). `for...of` is closest to C++ range-based for. Avoid `for...in` on arrays — it iterates keys as strings.",
          comparisons: [
            { concept: "Range-based for", knownCode: "for (const auto& word : words) {\n    std::cout << word;\n}", targetCode: "for (const word of words) {\n    console.log(word);\n}", note: "`for...of` iterates values. Use for arrays, strings, Maps, Sets." },
            { concept: "Index loop", knownCode: "for (int i = 0; i < 5; i++) {\n    std::cout << i;\n}", targetCode: "for (let i = 0; i < 5; i++) {\n    console.log(i);\n}" },
            { concept: "Functional: map/filter/reduce", knownCode: "std::transform(v.begin(), v.end(), out.begin(), func);", targetCode: "const doubled = nums.map(x => x * 2);\nconst evens = nums.filter(x => x % 2 === 0);\nconst sum = nums.reduce((acc, x) => acc + x, 0);", note: "Array methods are the idiomatic way to transform data in JS." },
          ],
          realWorld: "Modern JS overwhelmingly uses `.map()`, `.filter()`, `.reduce()` and `for...of` over index loops.",
          exercise: { id: "ex-cpp-js-loops-1", prompt: "Given `[1,2,3,4,5]`, use `.map()` to double each value and log the result.", starterCode: "const nums = [1, 2, 3, 4, 5];\n// doubled = ...\n", solution: "const nums = [1, 2, 3, 4, 5];\nconst doubled = nums.map(x => x * 2);\nconsole.log(doubled);", expectedOutputIncludes: "2,4,6,8,10", xp: 30 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-cpp-js-loop-1", prompt: "Which loop iterates values of an array?", choices: ["for...in", "for...of", "for...each", "while...of"], correctIndex: 1, explanation: "`for...of` iterates values. `for...in` iterates keys (string indices).", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-loop-2", prompt: "`[1,2,3].map(x => x * 2)` returns…", choices: ["undefined", "[2, 4, 6]", "6", "[1, 2, 3, 1, 2, 3]"], correctIndex: 1, explanation: "`.map()` transforms each element and returns a new array.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-loop-3", prompt: "What does `.reduce()` do?", choices: ["Removes elements", "Transforms each element", "Accumulates values into a single result", "Sorts the array"], correctIndex: 2, explanation: "Reduce folds an array into a single value using an accumulator.", xp: 10 },
        { kind: "debug", id: "q-cpp-js-loop-4", prompt: "Why does this print '0', '1', '2' as strings?", brokenCode: "const arr = [10, 20, 30];\nfor (const i in arr) {\n    console.log(typeof i);  // 'string'!\n}", choices: ["`for...in` iterates keys as strings — use `for...of` for values", "Arrays don't have types", "const prevents type inference", "typeof is broken"], correctIndex: 0, explanation: "`for...in` gives string keys ('0', '1', '2'). Use `for...of` for values.", xp: 15 },
        { kind: "mcq", id: "q-cpp-js-loop-5", prompt: "`.filter()` returns…", choices: ["The first matching element", "A boolean", "A new array with matching elements", "The original array, modified"], correctIndex: 2, explanation: "`.filter()` creates a new array with elements that pass the test.", xp: 10 },
      ],
    },
    {
      id: "cpp-js-functions",
      title: "Functions & Closures",
      tagline: "Arrow functions, closures, and `this`.",
      icon: "⚔️",
      level: "beginner",
      order: 4,
      requires: ["cpp-js-loops"],
      rewardXp: 90,
      lessons: [
        {
          id: "lesson-cpp-js-fn-1",
          title: "Functions and arrow syntax",
          intro: "JS has function declarations (`function name() {}`), function expressions, and arrow functions (`const f = (x) => x * 2`). Arrow functions are concise and inherit `this` from their enclosing scope. Functions are first-class values — pass them as arguments, store them in variables. JavaScript has closures: inner functions can capture outer variables.",
          comparisons: [
            { concept: "Function declaration", knownCode: "int add(int a, int b) {\n    return a + b;\n}", targetCode: "function add(a, b) {\n    return a + b;\n}" },
            { concept: "Arrow function (lambda)", knownCode: "auto add = [](int a, int b) { return a + b; };", targetCode: "const add = (a, b) => a + b;", note: "Single expression → implicit return. Multi-line needs `{}` and `return`." },
            { concept: "Default parameters", knownCode: 'void greet(std::string name = "World") { ... }', targetCode: 'function greet(name = "World") {\n    console.log(`Hello, ${name}!`);\n}', note: "Template literals use backticks and `${...}` instead of string concatenation." },
            { concept: "Closures", knownCode: "// C++ lambdas capture by value [=] or ref [&]", targetCode: "function counter() {\n    let n = 0;\n    return () => ++n;  // Captures n\n}\nconst inc = counter();\ninc(); // 1\ninc(); // 2", note: "JS closures always capture by reference. No [=] vs [&] distinction." },
          ],
          realWorld: "Arrow functions dominate modern JS for callbacks, event handlers, and `.map()` chains. Named `function` declarations are used at module top level.",
          exercise: { id: "ex-cpp-js-fn-1", prompt: "Write an arrow function `square` that returns x*x. Log `square(7)`.", starterCode: "// const square = ...\n", solution: "const square = x => x * x;\nconsole.log(square(7));", expectedOutputIncludes: "49", xp: 25 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-cpp-js-fn-1", prompt: "Which arrow function correctly returns n + 1?", choices: ["const f = n => { n + 1 }", "const f = n => n + 1;", "const f = (n) -> n + 1;", "const f = lambda n: n + 1;"], correctIndex: 1, explanation: "Without braces, the expression is implicitly returned. With braces, you need `return`.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-fn-2", prompt: "Template literals use…", choices: ["Double quotes and %s", "Backticks and ${...}", "f-strings", "Single quotes and +"], correctIndex: 1, explanation: "Backtick strings with `${expression}` interpolation.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-fn-3", prompt: "JavaScript closures capture variables by…", choices: ["Value (copy)", "Reference", "Move", "Neither — no closures"], correctIndex: 1, explanation: "JS closures capture by reference. Changes to outer variables are visible inside.", xp: 10 },
        { kind: "debug", id: "q-cpp-js-fn-4", prompt: "Why does this return undefined?", brokenCode: "const add = (a, b) => {\n    a + b;\n};", choices: ["Missing `return` — braces require explicit return", "Arrow functions can't use braces", "a + b is not valid", "Missing semicolons"], correctIndex: 0, explanation: "With `{}`, you must write `return a + b;`. Without `{}`, return is implicit.", xp: 15 },
        { kind: "mcq", id: "q-cpp-js-fn-5", prompt: "What is 'hoisting' for function declarations?", choices: ["Functions are moved to the top of their scope", "Functions are loaded lazily", "Functions are cached", "Functions are compiled separately"], correctIndex: 0, explanation: "`function` declarations are hoisted — usable before their line. Arrow/const are not.", xp: 10 },
      ],
    },
    {
      id: "cpp-js-collections",
      title: "Arrays & Objects",
      tagline: "Arrays, objects, destructuring, and spread.",
      icon: "📜",
      level: "beginner",
      order: 5,
      requires: ["cpp-js-functions"],
      rewardXp: 100,
      lessons: [
        {
          id: "lesson-cpp-js-col-1",
          title: "Arrays and objects",
          intro: "JS arrays are dynamic, heterogeneous, and zero-indexed. Objects are key-value maps (like `std::unordered_map<string, T>`). Destructuring extracts values: `const { name } = user`. Spread (`...`) copies and merges arrays/objects. `Map` and `Set` are also available for non-string keys and unique values.",
          comparisons: [
            { concept: "Array (vector)", knownCode: "std::vector<int> nums = {1, 2, 3};\nnums.push_back(4);", targetCode: "const nums = [1, 2, 3];\nnums.push(4);  // const allows mutation!", note: "`const` prevents reassignment but NOT mutation." },
            { concept: "Object (map)", knownCode: 'std::unordered_map<std::string, int> ages;\nages["Ada"] = 36;', targetCode: 'const ages = { Ada: 36 };\nages.Bob = 25;  // Dot notation\nages["Charlie"] = 30;  // Bracket notation' },
            { concept: "Destructuring", knownCode: "// C++17: auto [x, y] = std::make_pair(1, 2);", targetCode: 'const { name, age } = user;\nconst [first, ...rest] = [1, 2, 3, 4];', note: "Object destructuring by key name. Array destructuring by position." },
            { concept: "Spread", knownCode: "// No direct equivalent", targetCode: "const merged = { ...obj1, ...obj2 };\nconst combined = [...arr1, ...arr2];", note: "Spread creates shallow copies and merges." },
          ],
          realWorld: "Destructuring is one of JS's most-used features. It's in virtually every modern codebase.",
          exercise: { id: "ex-cpp-js-col-1", prompt: "Create an object `user` with name='Ada' and age=36. Destructure `name` and log it.", starterCode: "// const user = ...\n// Destructure name\n", solution: "const user = { name: 'Ada', age: 36 };\nconst { name } = user;\nconsole.log(name);", expectedOutputIncludes: "Ada", xp: 30 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-cpp-js-col-1", prompt: "`const arr = [1,2,3]; arr.push(4);` — does this work?", choices: ["No — const prevents mutation", "Yes — const prevents reassignment, not mutation", "Only with let", "Only for objects"], correctIndex: 1, explanation: "`const` prevents `arr = ...` but not `arr.push(...)`. The reference is constant, not the contents.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-col-2", prompt: "What does `{ ...a, ...b }` do?", choices: ["Adds a and b", "Merges objects a and b into a new object", "Destructures a and b", "Compares a and b"], correctIndex: 1, explanation: "Spread `...` copies own-enumerable properties. Later keys override earlier ones.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-col-3", prompt: "Which method removes the last element of an array?", choices: [".shift()", ".pop()", ".splice(-1)", ".slice(-1)"], correctIndex: 1, explanation: "`.pop()` removes and returns the last element. `.shift()` removes the first.", xp: 10 },
        { kind: "debug", id: "q-cpp-js-col-4", prompt: "Why doesn't this remove the first element?", brokenCode: "const xs = [1, 2, 3];\nxs.slice(1);\nconsole.log(xs);  // Still [1, 2, 3]!", choices: ["`slice` returns a new array without mutating — use `shift()` to remove in-place", "slice only works on strings", "Missing assignment", "Arrays are immutable"], correctIndex: 0, explanation: "`.slice()` is non-mutating. `.splice()` or `.shift()` mutate in-place.", xp: 15 },
        { kind: "mcq", id: "q-cpp-js-col-5", prompt: "What does `const [a, ...rest] = [1,2,3,4]` produce?", choices: ["a=1, rest=[2,3,4]", "a=[1,2,3], rest=4", "Error", "a=1, rest=2"], correctIndex: 0, explanation: "`...rest` collects remaining elements into an array.", xp: 10 },
      ],
    },
    // ===================== INTERMEDIATE =====================
    {
      id: "cpp-js-oop",
      title: "Classes & Prototypes",
      tagline: "ES6 classes are sugar over prototypes.",
      icon: "👑",
      level: "intermediate",
      order: 1,
      requires: [],
      rewardXp: 120,
      lessons: [
        {
          id: "lesson-cpp-js-oop-1",
          title: "Classes in JavaScript",
          intro: "ES6 classes look like C++ classes but are syntactic sugar over prototypal inheritance. `constructor` replaces the constructor. Methods don't take `this` explicitly — `this` is determined by how the method is called (the famous JS footgun). No access modifiers — use `#` for truly private fields (ES2022+).",
          comparisons: [
            { concept: "Class definition", knownCode: "class Hero {\npublic:\n    std::string name;\n    Hero(const std::string& n) : name(n) {}\n    std::string greet() { return \"Hi, \" + name; }\n};", targetCode: "class Hero {\n    constructor(name) {\n        this.name = name;\n    }\n    greet() {\n        return `Hi, ${this.name}`;\n    }\n}" },
            { concept: "Inheritance", knownCode: "class Mage : public Hero { ... };", targetCode: "class Mage extends Hero {\n    constructor(name, spell) {\n        super(name);\n        this.spell = spell;\n    }\n}" },
            { concept: "Private fields", knownCode: "private: int hp;", targetCode: "class Hero {\n    #hp = 100;  // Truly private (ES2022+)\n    getHp() { return this.#hp; }\n}", note: "`#` prefix makes fields truly private at the language level." },
          ],
          realWorld: "Many JS codebases prefer plain functions + objects over classes. Classes are common in frameworks like React (legacy class components) and NestJS.",
          exercise: { id: "ex-cpp-js-oop-1", prompt: "Define a `Counter` class with a `count` field (0), `inc()` method. Create one, call `inc()` twice, log `count`.", starterCode: "// class Counter { ... }\n", solution: "class Counter {\n    constructor() {\n        this.count = 0;\n    }\n    inc() {\n        this.count += 1;\n    }\n}\nconst c = new Counter();\nc.inc();\nc.inc();\nconsole.log(c.count);", expectedOutputIncludes: "2", xp: 35 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-cpp-js-oop-1", prompt: "What is the JS equivalent of a C++ constructor?", choices: ["init()", "constructor()", "new()", "create()"], correctIndex: 1, explanation: "`constructor()` runs on `new ClassName()`.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-oop-2", prompt: "How do you make a truly private field in JS?", choices: ["private keyword", "_ prefix", "# prefix", "closure only"], correctIndex: 2, explanation: "`#field` is truly private since ES2022. `_` is just a convention.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-oop-3", prompt: "JS classes are sugar over…", choices: ["Structs", "Prototypal inheritance", "C++ virtual tables", "Interfaces"], correctIndex: 1, explanation: "Under the hood, JS uses prototype chains for inheritance.", xp: 10 },
        { kind: "debug", id: "q-cpp-js-oop-4", prompt: "Why does `this` become undefined?", brokenCode: "class Timer {\n    constructor() { this.s = 0; }\n    tick() { this.s++; }\n}\nconst t = new Timer();\nsetTimeout(t.tick, 100);", choices: ["Method reference loses `this` binding — use arrow function or .bind()", "`this` is deprecated", "setTimeout doesn't accept methods", "Missing new keyword"], correctIndex: 0, explanation: "When you pass `t.tick` as a callback, `this` is lost. Use `() => t.tick()` or `t.tick.bind(t)`.", xp: 15 },
        { kind: "mcq", id: "q-cpp-js-oop-5", prompt: "`extends` in JS is equivalent to C++…", choices: [": public", "implements", "friend", "using"], correctIndex: 0, explanation: "`extends` creates an inheritance relationship, like `: public Base` in C++.", xp: 10 },
      ],
    },
    {
      id: "cpp-js-errors",
      title: "Error Handling",
      tagline: "try/catch + Promises + async error patterns.",
      icon: "🔥",
      level: "intermediate",
      order: 2,
      requires: ["cpp-js-oop"],
      rewardXp: 110,
      lessons: [
        {
          id: "lesson-cpp-js-err-1",
          title: "Exceptions and error patterns",
          intro: "JavaScript uses `try/catch/finally`. You can throw anything (not just Error objects). There are no checked exceptions. For async code, errors can be caught with `.catch()` on Promises or `try/catch` with `async/await`. Unhandled promise rejections crash Node.js.",
          comparisons: [
            { concept: "Try/catch", knownCode: "try {\n    risky();\n} catch (const std::exception& e) {\n    std::cerr << e.what();\n}", targetCode: "try {\n    risky();\n} catch (error) {\n    console.error(error.message);\n}", note: "JS catch doesn't filter by type — use `instanceof` checks inside." },
            { concept: "Throwing errors", knownCode: "throw std::runtime_error(\"fail\");", targetCode: "throw new Error('fail');\n// Can throw anything: throw 42; throw 'oops';", note: "Always throw `Error` objects — they include stack traces." },
            { concept: "Async error handling", knownCode: "// No direct equivalent", targetCode: "try {\n    const data = await fetchData();\n} catch (err) {\n    console.error('Fetch failed:', err);\n}", note: "`async/await` with `try/catch` is the modern pattern." },
          ],
          realWorld: "Always throw `Error` (or subclass) objects. Throwing strings or numbers loses the stack trace.",
          exercise: { id: "ex-cpp-js-err-1", prompt: 'Write a function `safeParse(json)` that tries JSON.parse and returns null on error. Test with invalid JSON.', starterCode: "function safeParse(json) {\n    // ...\n}\n", solution: "function safeParse(json) {\n    try {\n        return JSON.parse(json);\n    } catch (e) {\n        return null;\n    }\n}\nconsole.log(safeParse('invalid'));", expectedOutputIncludes: "null", xp: 30 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-cpp-js-err-1", prompt: "Can you throw a string in JavaScript?", choices: ["No — only Error objects", "Yes — but you shouldn't (no stack trace)", "Only in strict mode", "Only numbers"], correctIndex: 1, explanation: "JS lets you throw anything, but only Error objects have stack traces.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-err-2", prompt: "How do you catch async errors with await?", choices: ["callback", ".catch()", "try/catch around await", "Both B and C work"], correctIndex: 3, explanation: "Both `.catch()` and `try/catch` with `await` handle async errors.", xp: 10 },
        { kind: "debug", id: "q-cpp-js-err-3", prompt: "Why does this crash the process?", brokenCode: "fetch('https://bad.url').then(r => r.json());\n// No .catch() — unhandled rejection!", choices: ["Unhandled promise rejection — add .catch() or try/catch with await", "fetch is synchronous", "json() doesn't throw", "Missing callback"], correctIndex: 0, explanation: "Unhandled promise rejections terminate Node.js. Always handle errors.", xp: 15 },
        { kind: "mcq", id: "q-cpp-js-err-3b", prompt: "Does JS have checked exceptions?", choices: ["Yes", "No — all exceptions are unchecked", "Only in TypeScript", "Only for async code"], correctIndex: 1, explanation: "JavaScript has no concept of checked exceptions. Nothing forces you to handle errors.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-err-4", prompt: "`finally` block runs…", choices: ["Only on error", "Only on success", "Always — error or not", "Never in async code"], correctIndex: 2, explanation: "`finally` always executes, regardless of whether an error was thrown.", xp: 10 },
      ],
    },
    {
      id: "cpp-js-modules",
      title: "Modules & npm",
      tagline: "import/export and the npm ecosystem.",
      icon: "📦",
      level: "intermediate",
      order: 3,
      requires: ["cpp-js-errors"],
      rewardXp: 100,
      lessons: [
        {
          id: "lesson-cpp-js-mod-1",
          title: "ES Modules and npm",
          intro: "JavaScript uses ES Modules (`import`/`export`) for code organization. `npm` (or `yarn`, `pnpm`) manages dependencies from the npm registry. `package.json` is the project manifest. Node.js also has CommonJS (`require`/`module.exports`) but ES Modules are the standard.",
          comparisons: [
            { concept: "Import/include", knownCode: "#include <cmath>\n#include \"mylib.h\"", targetCode: "import { sqrt } from 'math-lib';\nimport myModule from './myModule.js';", note: "Named exports use `{}`. Default exports don't." },
            { concept: "Export", knownCode: "// Declare in header, define in source", targetCode: "export function add(a, b) { return a + b; }\nexport default class App { ... }", note: "Each file can have one `default` export and many named exports." },
            { concept: "Package management", knownCode: "// CMake find_package, vcpkg, conan", targetCode: "// npm install lodash\n// package.json tracks dependencies\nimport _ from 'lodash';", note: "npm has 2M+ packages. `node_modules` stores them locally." },
          ],
          realWorld: "Modern JS uses ESM (`import`/`export`). Legacy code uses CommonJS (`require`). Most bundlers (Vite, webpack) handle both.",
          exercise: { id: "ex-cpp-js-mod-1", prompt: "Write a module that exports a function `greet(name)` and a constant `VERSION`. Show the import syntax.", starterCode: "// In greet.js\n// export ...\n", solution: "// greet.js\nexport const VERSION = '1.0';\nexport function greet(name) {\n    return `Hello, ${name}!`;\n}\n\n// main.js\n// import { greet, VERSION } from './greet.js';", expectedOutputIncludes: "export", xp: 25 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-cpp-js-mod-1", prompt: "ES Module syntax uses…", choices: ["require/module.exports", "import/export", "#include", "using namespace"], correctIndex: 1, explanation: "`import`/`export` is the modern standard. `require` is CommonJS (legacy Node.js).", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-mod-2", prompt: "What is `package.json`?", choices: ["Build script", "Project manifest with dependencies and metadata", "Module registry", "Config file for ESLint"], correctIndex: 1, explanation: "`package.json` defines the project, its dependencies, scripts, and metadata.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-mod-3", prompt: "What does `npm install` do?", choices: ["Compiles the project", "Downloads dependencies to node_modules/", "Deploys to production", "Runs unit tests"], correctIndex: 1, explanation: "It reads `package.json` and installs all listed dependencies.", xp: 10 },
        { kind: "debug", id: "q-cpp-js-mod-4", prompt: "Why does this fail?", brokenCode: "import add from './math.js';\n// math.js: export function add(a, b) { return a + b; }", choices: ["Named exports need `{}` — use `import { add } from './math.js'`", "add is not a function", "Wrong file extension", "Missing npm install"], correctIndex: 0, explanation: "`export function` is a named export. Import with `{ add }`. Only `export default` uses no braces.", xp: 15 },
      ],
    },
    {
      id: "cpp-js-functional",
      title: "Functional Patterns",
      tagline: "Immutability, pure functions, and composition.",
      icon: "⚡",
      level: "intermediate",
      order: 4,
      requires: ["cpp-js-modules"],
      rewardXp: 130,
      lessons: [
        {
          id: "lesson-cpp-js-func-1",
          title: "Functional JavaScript",
          intro: "JavaScript excels at functional programming. Functions are first-class, closures are natural, and array methods encourage immutable transformations. Key patterns: pure functions, immutability (spread/Object.freeze), composition, and currying. Libraries like Ramda and Lodash/fp provide additional FP utilities.",
          comparisons: [
            { concept: "Map + Filter chain", knownCode: "// C++ ranges (C++20) pipeline", targetCode: "const result = data\n    .filter(x => x.active)\n    .map(x => x.name)\n    .sort();" },
            { concept: "Reduce (fold)", knownCode: "int sum = std::accumulate(v.begin(), v.end(), 0);", targetCode: "const sum = nums.reduce((acc, n) => acc + n, 0);", note: "Second argument (0) is the initial accumulator value." },
            { concept: "Currying", knownCode: "// Template metaprogramming needed...", targetCode: "const multiply = a => b => a * b;\nconst double = multiply(2);\nconsole.log(double(5)); // 10", note: "Currying creates specialized functions from general ones." },
          ],
          realWorld: "React, Redux, and most modern JS frameworks are built on functional patterns. Understanding immutability and pure functions is essential.",
          exercise: { id: "ex-cpp-js-func-1", prompt: "Write a `pipe` function that composes functions left-to-right. `pipe(double, addOne)(3)` should return 7.", starterCode: "// const pipe = (...fns) => ...\n", solution: "const pipe = (...fns) => x => fns.reduce((v, f) => f(v), x);\nconst double = x => x * 2;\nconst addOne = x => x + 1;\nconsole.log(pipe(double, addOne)(3));", expectedOutputIncludes: "7", xp: 45 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-cpp-js-func-1", prompt: "What is a pure function?", choices: ["A function with no parameters", "A function with no side effects and deterministic output", "A function that returns void", "A static method"], correctIndex: 1, explanation: "Pure functions: same inputs → same output, no side effects.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-func-2", prompt: "What does `Object.freeze(obj)` do?", choices: ["Deletes the object", "Makes the object shallowly immutable", "Compresses the object", "Makes a deep copy"], correctIndex: 1, explanation: "Freeze prevents adding, removing, or modifying properties (shallow only).", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-func-3", prompt: "Currying transforms a function that takes multiple args into…", choices: ["A function that takes an array", "A chain of functions each taking one argument", "A recursive function", "A generator"], correctIndex: 1, explanation: "`f(a, b)` becomes `f(a)(b)`. Each call returns a new function.", xp: 10 },
        { kind: "debug", id: "q-cpp-js-func-4", prompt: "Why does this `.reduce()` fail?", brokenCode: "const sum = [1, 2, 3].reduce((acc, n) => acc + n);", choices: ["It doesn't fail — it works, but omitting initial value is risky on empty arrays", "reduce needs 4 arguments", "Arrow functions can't be used with reduce", "Missing return"], correctIndex: 0, explanation: "Without initial value, reduce uses first element. On empty array, it throws TypeError.", xp: 15 },
        { kind: "mcq", id: "q-cpp-js-func-5", prompt: "`.flatMap()` is equivalent to…", choices: [".flat() then .map()", ".map() then .flat(1)", ".filter() then .map()", ".reduce() then .flat()"], correctIndex: 1, explanation: "`.flatMap()` maps each element then flattens one level.", xp: 10 },
      ],
    },
    // ===================== ADVANCED =====================
    {
      id: "cpp-js-async",
      title: "Async Programming",
      tagline: "Event loop, Promises, and async/await.",
      icon: "🔄",
      level: "advanced",
      order: 1,
      requires: [],
      rewardXp: 170,
      lessons: [
        {
          id: "lesson-cpp-js-async-1",
          title: "The event loop and Promises",
          intro: "JavaScript is single-threaded with an event loop. Async operations (I/O, timers, network) are non-blocking. Promises represent eventual values: `pending` → `fulfilled`/`rejected`. `async/await` is syntactic sugar for Promises. The event loop processes: call stack → microtasks (Promises) → macrotasks (setTimeout, I/O).",
          comparisons: [
            { concept: "Async operation", knownCode: "auto future = std::async(std::launch::async, func);\nauto result = future.get();", targetCode: "const result = await someAsyncFunc();\n// Or: someAsyncFunc().then(result => { ... });", note: "JS is single-threaded — async doesn't mean parallel." },
            { concept: "Promise creation", knownCode: "std::promise<int> p;\nauto f = p.get_future();", targetCode: "const p = new Promise((resolve, reject) => {\n    // async work...\n    resolve(42);\n    // or: reject(new Error('fail'));\n});", note: "The executor function runs immediately." },
            { concept: "Parallel async", knownCode: "// std::async with launch::async", targetCode: "const [a, b] = await Promise.all([\n    fetchA(),\n    fetchB()\n]);", note: "`Promise.all` runs promises concurrently (not parallel — single thread)." },
          ],
          realWorld: "Understanding the event loop is critical for Node.js and browser JS. `Promise.all` for concurrent I/O, `Promise.race` for timeouts.",
          exercise: { id: "ex-cpp-js-async-1", prompt: "Write an async function `delayed(ms, value)` that returns `value` after `ms` milliseconds. Test with `delayed(0, 'hello')`.", starterCode: "// async function delayed(ms, value) { ... }\n", solution: "async function delayed(ms, value) {\n    return new Promise(resolve => setTimeout(() => resolve(value), ms));\n}\n\ndelayed(0, 'hello').then(v => console.log(v));", expectedOutputIncludes: "hello", xp: 45 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-cpp-js-async-1", prompt: "JavaScript is…", choices: ["Multi-threaded", "Single-threaded with an event loop", "Compiled to native code", "Thread-per-request"], correctIndex: 1, explanation: "JS runs on one thread. Async operations use the event loop.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-async-2", prompt: "What does `Promise.all()` do?", choices: ["Runs promises sequentially", "Waits for all promises to settle", "Cancels failed promises", "Creates new threads"], correctIndex: 1, explanation: "Resolves when all promises fulfill. Rejects if any one rejects.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-async-3", prompt: "Microtasks (Promises) run before…", choices: ["Nothing — they run last", "Macrotasks (setTimeout, I/O)", "The call stack", "Garbage collection"], correctIndex: 1, explanation: "After the call stack empties: microtasks first, then one macrotask.", xp: 10 },
        { kind: "debug", id: "q-cpp-js-async-4", prompt: "Why does '2' print before '1'?", brokenCode: "setTimeout(() => console.log('1'), 0);\nconsole.log('2');", choices: ["setTimeout is always async — '2' runs on the call stack first", "Math error", "console.log is async", "setTimeout is synchronous"], correctIndex: 0, explanation: "Even with 0ms delay, setTimeout schedules a macrotask. Synchronous code runs first.", xp: 15 },
        { kind: "mcq", id: "q-cpp-js-async-5", prompt: "`async function` always returns…", choices: ["void", "A value", "A Promise", "undefined"], correctIndex: 2, explanation: "Async functions implicitly wrap their return value in a Promise.", xp: 10 },
      ],
    },
    {
      id: "cpp-js-memory",
      title: "Memory & Performance",
      tagline: "GC, closures, and V8 optimizations.",
      icon: "🧠",
      level: "advanced",
      order: 2,
      requires: ["cpp-js-async"],
      rewardXp: 150,
      lessons: [
        {
          id: "lesson-cpp-js-mem-1",
          title: "Memory model and GC",
          intro: "JavaScript uses garbage collection (mark-and-sweep in V8). No manual memory management. Common memory leaks: closures holding references, detached DOM nodes, forgotten timers/listeners. V8 uses hidden classes and inline caches for optimization — writing 'monomorphic' code (consistent object shapes) helps performance.",
          comparisons: [
            { concept: "Memory management", knownCode: "int* arr = new int[100];\ndelete[] arr;", targetCode: "const arr = new Array(100);\n// No delete — GC handles it", note: "V8's GC is generational: young gen (Scavenger) and old gen (Mark-Sweep-Compact)." },
            { concept: "Avoiding leaks", knownCode: "// RAII handles resource cleanup", targetCode: "// Remove event listeners:\nel.removeEventListener('click', handler);\n// Clear timers:\nclearInterval(timerId);", note: "The GC can't free objects still referenced by closures, listeners, or globals." },
          ],
          realWorld: "Use Chrome DevTools Memory tab to find leaks. WeakRef and WeakMap allow GC-friendly caches.",
          exercise: { id: "ex-cpp-js-mem-1", prompt: "Explain (in a comment) why this creates a memory leak, then fix it.", starterCode: "const cache = [];\nfunction process(data) {\n    cache.push(data);  // Never cleared!\n    return data.toUpperCase();\n}", solution: "// Memory leak: cache grows unbounded. Fix: use a bounded cache or WeakRef.\nconst cache = [];\nfunction process(data) {\n    if (cache.length > 1000) cache.length = 0;  // Bound the cache\n    cache.push(data);\n    return data.toUpperCase();\n}", expectedOutputIncludes: "", xp: 35 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-cpp-js-mem-1", prompt: "JavaScript uses which GC algorithm?", choices: ["Reference counting only", "Mark-and-sweep (V8)", "Manual free()", "RAII"], correctIndex: 1, explanation: "V8 uses generational mark-and-sweep garbage collection.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-mem-2", prompt: "Common source of memory leaks in JS:", choices: ["Using const", "Closures holding large references", "Arrow functions", "Template literals"], correctIndex: 1, explanation: "Closures capture outer scope — if those references are large, they can't be GC'd.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-mem-3", prompt: "What is `WeakRef` used for?", choices: ["Making variables immutable", "Holding a reference that doesn't prevent GC", "Creating weak types", "Thread safety"], correctIndex: 1, explanation: "WeakRef lets the GC collect the referenced object if no strong refs exist.", xp: 10 },
        { kind: "debug", id: "q-cpp-js-mem-4", prompt: "Why does this leak memory?", brokenCode: "setInterval(() => {\n    console.log(new Date());\n}, 1000);\n// Never cleared!", choices: ["The interval runs forever — use clearInterval() when done", "setInterval is synchronous", "Date objects are large", "console.log caches output"], correctIndex: 0, explanation: "Without `clearInterval()`, the callback and its closure live forever.", xp: 15 },
        { kind: "mcq", id: "q-cpp-js-mem-5", prompt: "V8 optimizes objects with consistent shapes using…", choices: ["Templates", "Hidden classes (maps)", "Manual structs", "Type annotations"], correctIndex: 1, explanation: "V8 creates hidden classes for consistent object shapes. Adding/deleting properties randomly deoptimizes.", xp: 10 },
      ],
    },
    {
      id: "cpp-js-advanced",
      title: "Advanced Patterns",
      tagline: "Proxies, generators, and metaprogramming.",
      icon: "✨",
      level: "advanced",
      order: 3,
      requires: ["cpp-js-memory"],
      rewardXp: 200,
      lessons: [
        {
          id: "lesson-cpp-js-adv-1",
          title: "Generators and iterators",
          intro: "JavaScript generators (`function*`) use `yield` to produce values lazily — similar to Python generators. They implement the iterator protocol. `for...of` works with any iterator. Async generators (`async function*`) combine async and lazy iteration.",
          comparisons: [
            { concept: "Generator", knownCode: "// Complex custom iterator in C++", targetCode: "function* range(start, end) {\n    for (let i = start; i < end; i++) {\n        yield i;\n    }\n}\nfor (const n of range(0, 5)) console.log(n);", note: "`function*` declares a generator. `yield` suspends and resumes." },
            { concept: "Proxy (metaprogramming)", knownCode: "// operator overloading in C++", targetCode: "const handler = {\n    get(target, prop) {\n        return prop in target ? target[prop] : 'default';\n    }\n};\nconst p = new Proxy({}, handler);", note: "Proxies intercept operations on objects — extremely powerful." },
          ],
          realWorld: "Generators power async iteration in Node.js streams. Proxies are used by Vue.js reactivity, validation libraries, and ORM frameworks.",
          exercise: { id: "ex-cpp-js-adv-1", prompt: "Write a generator `fibonacci()` that yields Fibonacci numbers forever. Print the first 8.", starterCode: "// function* fibonacci() { ... }\n", solution: "function* fibonacci() {\n    let a = 0, b = 1;\n    while (true) {\n        yield a;\n        [a, b] = [b, a + b];\n    }\n}\n\nlet count = 0;\nfor (const n of fibonacci()) {\n    console.log(n);\n    if (++count >= 8) break;\n}", expectedOutputIncludes: "0\n1\n1\n2\n3\n5\n8\n13", xp: 50 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-cpp-js-adv-1", prompt: "Generator functions are declared with…", choices: ["function()", "function*()", "gen()", "async function()"], correctIndex: 1, explanation: "The asterisk `*` marks a generator function.", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-adv-2", prompt: "What can a Proxy intercept?", choices: ["Only get/set", "Any object operation (get, set, delete, has, etc.)", "Only function calls", "Only property access"], correctIndex: 1, explanation: "Proxies can intercept 13+ different operations (traps).", xp: 10 },
        { kind: "mcq", id: "q-cpp-js-adv-3", prompt: "What does `Symbol` provide?", choices: ["String encryption", "Globally unique identifiers for object keys", "Mathematical symbols", "Type annotations"], correctIndex: 1, explanation: "Symbols are unique, immutable identifiers. Used for metaprogramming (e.g., `Symbol.iterator`).", xp: 10 },
        { kind: "debug", id: "q-cpp-js-adv-4", prompt: "Why does this generator produce nothing?", brokenCode: "function* nums() {\n    return [1, 2, 3];\n}\nfor (const n of nums()) console.log(n);", choices: ["`return` ends the generator. Use `yield` or `yield*` for each value", "for...of doesn't work with generators", "Missing function call", "Array can't be returned"], correctIndex: 0, explanation: "`return` completes the generator with `done: true`. Use `yield* [1,2,3]` or yield individually.", xp: 15 },
        { kind: "mcq", id: "q-cpp-js-adv-5", prompt: "`yield*` is used to…", choices: ["Yield multiple values at once", "Delegate to another generator/iterable", "Yield in parallel", "Create a new generator"], correctIndex: 1, explanation: "`yield*` delegates iteration to another iterable or generator.", xp: 10 },
      ],
    },
  ],
};
