import type { Course } from "@/lib/types";

export const cppToJava: Course = {
  id: "cpp-to-java",
  knownLang: "cpp",
  targetLang: "java",
  title: "C++ → Java",
  modules: [
    // ===================== BEGINNER =====================
    {
      id: "cpp-java-variables",
      title: "Variables & Types",
      tagline: "Still statically typed, but everything is an object.",
      icon: "🏰",
      level: "beginner",
      order: 1,
      requires: [],
      rewardXp: 60,
      lessons: [
        {
          id: "lesson-cpp-java-vars-1",
          title: "Primitive types and declarations",
          intro:
            "Java is statically typed like C++, but has no unsigned types, no pointers, and no `typedef`. Primitive types (`int`, `double`, `boolean`, `char`, `byte`, `short`, `long`, `float`) live on the stack. Everything else is a reference type (object on the heap). Java also has autoboxing: `int` ↔ `Integer`.",
          comparisons: [
            {
              concept: "Variable declaration",
              knownCode: "int count = 0;\ndouble pi = 3.14;\nbool done = false;",
              targetCode: "int count = 0;\ndouble pi = 3.14;\nboolean done = false;",
              note: "`bool` → `boolean`. Java spells it out.",
            },
            {
              concept: "Constants",
              knownCode: "const int MAX = 100;",
              targetCode: "final int MAX = 100;",
              note: "`const` → `final`. `final` prevents reassignment.",
            },
            {
              concept: "Strings",
              knownCode: 'std::string name = "Ada";',
              targetCode: 'String name = "Ada";',
              note: "`String` is a class (capital S), not a primitive. Strings are immutable in Java.",
            },
            {
              concept: "Auto type inference",
              knownCode: "auto x = 42;",
              targetCode: "var x = 42;  // Java 10+",
              note: "`var` in Java is local type inference (like C++ `auto`).",
            },
          ],
          realWorld:
            "Java has no `unsigned` types — this trips up many C++ developers. Use `long` for large positive numbers or bit manipulation libraries.",
          exercise: {
            id: "ex-cpp-java-vars-1",
            prompt:
              'Declare a `final` String variable `greeting` set to "Hello" and print it using `System.out.println`.',
            starterCode: "// Declare greeting and print it\n",
            solution:
              'final String greeting = "Hello";\nSystem.out.println(greeting);',
            expectedOutputIncludes: "Hello",
            xp: 20,
          },
        },
        {
          id: "lesson-cpp-java-vars-2",
          title: "Type system differences",
          intro:
            "Java has strict type safety with no implicit narrowing conversions (unlike C++). Casting is done with `(type)value`. Java has wrapper classes for each primitive (`Integer`, `Double`, `Boolean`) that enable null and work with generics. Autoboxing/unboxing converts between them automatically.",
          comparisons: [
            {
              concept: "Casting",
              knownCode: "double d = 3.7;\nint n = (int)d;  // or static_cast<int>(d)",
              targetCode: "double d = 3.7;\nint n = (int) d;  // Truncates to 3",
            },
            {
              concept: "Autoboxing",
              knownCode: "// No equivalent in C++",
              targetCode: "Integer boxed = 42;    // int → Integer (autoboxing)\nint unboxed = boxed;   // Integer → int (unboxing)",
              note: "Autoboxing has overhead — avoid in performance-critical loops.",
            },
            {
              concept: "Null safety",
              knownCode: "int* ptr = nullptr;",
              targetCode: "Integer x = null;  // Wrapper can be null\n// int y = null;  // COMPILE ERROR — primitives can't be null",
              note: "Only reference types can be `null`. Primitives always have a value.",
            },
          ],
          realWorld:
            "NullPointerException is Java's most common runtime error. Modern Java uses `Optional<T>` to handle nullable values safely.",
          exercise: {
            id: "ex-cpp-java-vars-2",
            prompt:
              'Convert the string "42" to an int, add 8, and print the result.',
            starterCode: 'String s = "42";\n// Convert and add 8\n',
            solution:
              'String s = "42";\nint result = Integer.parseInt(s) + 8;\nSystem.out.println(result);',
            expectedOutputIncludes: "50",
            xp: 25,
          },
        },
      ],
      quiz: [
        {
          kind: "mcq",
          id: "q-cpp-java-var-1",
          prompt: "What is the Java equivalent of C++ `bool`?",
          choices: ["bool", "boolean", "Boolean", "bit"],
          correctIndex: 1,
          explanation: "Java's primitive boolean type is `boolean` (lowercase).",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-var-2",
          prompt: "What does `final` do in Java?",
          choices: [
            "Makes a variable thread-safe",
            "Prevents reassignment (like C++ `const`)",
            "Makes a variable static",
            "Deletes the variable after use",
          ],
          correctIndex: 1,
          explanation: "`final` prevents the variable from being reassigned.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-var-3",
          prompt: "Java has no unsigned integer types. True or false?",
          choices: ["True", "False"],
          correctIndex: 0,
          explanation: "Java has no `unsigned` keyword. All integer types are signed.",
          xp: 10,
        },
        {
          kind: "debug",
          id: "q-cpp-java-var-4",
          prompt: "Why does this crash at runtime?",
          brokenCode: 'Integer x = null;\nint y = x;  // NullPointerException!',
          choices: [
            "Unboxing null throws NullPointerException",
            "null is not a valid keyword",
            "int and Integer are incompatible",
            "Missing final keyword",
          ],
          correctIndex: 0,
          explanation:
            "Unboxing `null` to a primitive throws NPE. Always check for null before unboxing.",
          xp: 15,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-var-5",
          prompt: "What does `var x = 42;` do in Java 10+?",
          choices: [
            "Creates a dynamic variable",
            "Local type inference — compiler infers `int`",
            "Creates a variant type",
            "Syntax error",
          ],
          correctIndex: 1,
          explanation: "`var` is Java's local variable type inference, similar to C++ `auto`.",
          xp: 10,
        },
      ],
    },
    {
      id: "cpp-java-controlflow",
      title: "Control Flow",
      tagline: "Familiar braces and parens — plus enhanced switch.",
      icon: "🛡️",
      level: "beginner",
      order: 2,
      requires: ["cpp-java-variables"],
      rewardXp: 70,
      lessons: [
        {
          id: "lesson-cpp-java-cf-1",
          title: "Conditionals and switch",
          intro:
            "Java's `if/else if/else` is nearly identical to C++. The main differences: `boolean` expressions only (no implicit int-to-bool), `&&`/`||` are the same, and Java 14+ introduced enhanced `switch` expressions with arrow syntax (`->`) and no fall-through.",
          comparisons: [
            {
              concept: "if / else if / else",
              knownCode: 'if (score > 90) {\n    std::cout << "A";\n} else if (score > 75) {\n    std::cout << "B";\n}',
              targetCode: 'if (score > 90) {\n    System.out.println("A");\n} else if (score > 75) {\n    System.out.println("B");\n}',
              note: "Almost identical! Use `System.out.println` instead of `std::cout`.",
            },
            {
              concept: "Enhanced switch (Java 14+)",
              knownCode: 'switch (day) {\n    case 1: std::cout << "Mon"; break;\n    case 2: std::cout << "Tue"; break;\n    default: std::cout << "Other";\n}',
              targetCode: 'String result = switch (day) {\n    case 1 -> "Mon";\n    case 2 -> "Tue";\n    default -> "Other";\n};',
              note: "Arrow switch: no fall-through, returns a value. Much cleaner!",
            },
            {
              concept: "No implicit boolean conversion",
              knownCode: "if (count) { ... }  // Valid in C++ (0 = false)",
              targetCode: "if (count != 0) { ... }  // Must be explicit in Java",
              note: "Java requires `boolean` — no implicit int-to-bool conversion.",
            },
          ],
          realWorld:
            "Java's enhanced switch (arrow syntax) eliminates fall-through bugs. Pattern matching in switch is being added in recent Java versions (17+).",
          exercise: {
            id: "ex-cpp-java-cf-1",
            prompt:
              "Write an enhanced switch expression that assigns a letter grade to `score = 85`: A for >90, B for >75, C for >60, F otherwise. Print the grade.",
            starterCode: "int score = 85;\n// Use if/else (enhanced switch needs Java 14+)\n",
            solution:
              'int score = 85;\nString grade;\nif (score > 90) {\n    grade = "A";\n} else if (score > 75) {\n    grade = "B";\n} else if (score > 60) {\n    grade = "C";\n} else {\n    grade = "F";\n}\nSystem.out.println(grade);',
            expectedOutputIncludes: "B",
            xp: 25,
          },
        },
      ],
      quiz: [
        {
          kind: "mcq",
          id: "q-cpp-java-cf-1",
          prompt: "Can you write `if (count)` in Java (where count is int)?",
          choices: [
            "Yes, 0 is false like in C++",
            "No — Java requires a boolean expression",
            "Yes, but only for positive numbers",
            "Only with var keyword",
          ],
          correctIndex: 1,
          explanation: "Java doesn't do implicit int-to-boolean. Write `if (count != 0)`.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-cf-2",
          prompt: "What advantage does Java's arrow switch (`->`) have?",
          choices: [
            "It's faster at runtime",
            "No fall-through, can return values",
            "It supports regex patterns",
            "It works with null",
          ],
          correctIndex: 1,
          explanation: "Arrow switch eliminates fall-through bugs and can be used as an expression.",
          xp: 10,
        },
        {
          kind: "debug",
          id: "q-cpp-java-cf-3",
          prompt: "Why does this switch behave unexpectedly?",
          brokenCode: 'switch (x) {\n    case 1: System.out.println("one");\n    case 2: System.out.println("two");\n    default: System.out.println("other");\n}',
          choices: [
            "Missing `break` — causes fall-through to subsequent cases",
            "switch doesn't work with ints",
            "Missing curly braces",
            "x must be final",
          ],
          correctIndex: 0,
          explanation: "Without `break`, execution falls through to the next case. Use `->` syntax or add `break;`.",
          xp: 15,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-cf-3b",
          prompt: "Java's output function is…",
          choices: ["cout <<", "printf()", "System.out.println()", "print()"],
          correctIndex: 2,
          explanation: "`System.out.println()` for line output, `.print()` without newline.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-cf-4",
          prompt: "What Java feature (17+) is similar to C++17 structured bindings?",
          choices: [
            "Pattern matching in switch",
            "var declarations",
            "Records with deconstruction",
            "All of the above are partial equivalents",
          ],
          correctIndex: 3,
          explanation: "Java is gradually adding pattern matching features across versions.",
          xp: 10,
        },
      ],
    },
    {
      id: "cpp-java-loops",
      title: "Loops & Iteration",
      tagline: "for-each and Iterables — no iterators needed.",
      icon: "🌀",
      level: "beginner",
      order: 3,
      requires: ["cpp-java-controlflow"],
      rewardXp: 80,
      lessons: [
        {
          id: "lesson-cpp-java-loops-1",
          title: "For loops and enhanced for",
          intro:
            "Java's classic for loop is identical to C++. The enhanced for loop (`for (Type x : collection)`) works with arrays and any `Iterable`. Java has no `range()` — use classic for loops for counting. `while` and `do-while` work identically.",
          comparisons: [
            {
              concept: "Classic for loop",
              knownCode: "for (int i = 0; i < 5; i++) {\n    std::cout << i;\n}",
              targetCode: "for (int i = 0; i < 5; i++) {\n    System.out.println(i);\n}",
              note: "Identical syntax! Just different output function.",
            },
            {
              concept: "Enhanced for (range-based)",
              knownCode: "for (const auto& word : words) {\n    std::cout << word;\n}",
              targetCode: "for (String word : words) {\n    System.out.println(word);\n}",
              note: "No `auto` in enhanced for — you specify the type (or use `var` in Java 10+).",
            },
            {
              concept: "Iterating with index",
              knownCode: "for (int i = 0; i < v.size(); i++) { ... }",
              targetCode: "for (int i = 0; i < list.size(); i++) {\n    System.out.println(list.get(i));\n}",
              note: "Use `.size()` and `.get(i)` for List. Arrays use `.length` and `arr[i]`.",
            },
          ],
          realWorld:
            "Java 8+ `IntStream.range(0, 5).forEach(...)` is the closest thing to Python's `range()`. Streams offer functional iteration.",
          exercise: {
            id: "ex-cpp-java-loops-1",
            prompt: "Print the numbers 1 through 5 using a for loop.",
            starterCode: "// Print 1, 2, 3, 4, 5\n",
            solution: "for (int i = 1; i <= 5; i++) {\n    System.out.println(i);\n}",
            expectedOutputIncludes: "1\n2\n3\n4\n5",
            xp: 20,
          },
        },
        {
          id: "lesson-cpp-java-loops-2",
          title: "Iterators and Iterable interface",
          intro:
            "Any Java class that implements `Iterable<T>` can be used with the enhanced for loop. The `Iterator<T>` interface has `hasNext()` and `next()`. Java 8+ Streams (`stream().map().filter().collect()`) provide a functional alternative — like C++20 ranges but more mature.",
          comparisons: [
            {
              concept: "Iterator pattern",
              knownCode: "for (auto it = v.begin(); it != v.end(); ++it) { ... }",
              targetCode: "Iterator<String> it = list.iterator();\nwhile (it.hasNext()) {\n    System.out.println(it.next());\n}",
              note: "Explicit iterators are rarely used — enhanced for-loop is preferred.",
            },
            {
              concept: "Stream API (functional)",
              knownCode: "// C++20 ranges: views::filter | views::transform",
              targetCode: "list.stream()\n    .filter(s -> s.length() > 3)\n    .map(String::toUpperCase)\n    .forEach(System.out::println);",
              note: "Streams are lazy and composable — very powerful for data processing.",
            },
          ],
          realWorld:
            "The Stream API is one of Java's best features. It's used everywhere in modern Java code for collection processing.",
          exercise: {
            id: "ex-cpp-java-loops-2",
            prompt:
              'Given a String array `{"apple", "banana", "cherry"}`, use an enhanced for loop to print each fruit.',
            starterCode: 'String[] fruits = {"apple", "banana", "cherry"};\n// Enhanced for loop\n',
            solution:
              'String[] fruits = {"apple", "banana", "cherry"};\nfor (String fruit : fruits) {\n    System.out.println(fruit);\n}',
            expectedOutputIncludes: "apple\nbanana\ncherry",
            xp: 25,
          },
        },
      ],
      quiz: [
        {
          kind: "mcq",
          id: "q-cpp-java-loop-1",
          prompt: "Java's enhanced for-each loop syntax is…",
          choices: [
            "for (auto x : collection)",
            "for (Type x : collection)",
            "for x in collection",
            "foreach (x in collection)",
          ],
          correctIndex: 1,
          explanation: "Use `for (Type variable : iterable)` — type is required (or `var` in Java 10+).",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-loop-2",
          prompt: "How do you get the length of an array vs a List in Java?",
          choices: [
            "Both use .size()",
            "Both use .length",
            "Array uses .length, List uses .size()",
            "Array uses len(), List uses count()",
          ],
          correctIndex: 2,
          explanation: "Arrays: `.length` (field). Lists: `.size()` (method).",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-loop-3",
          prompt: "Java's Stream API is most similar to…",
          choices: ["C++ STL algorithms", "C++20 ranges", "printf", "RAII"],
          correctIndex: 1,
          explanation: "Streams are lazy, composable pipelines — like C++20 ranges.",
          xp: 10,
        },
        {
          kind: "debug",
          id: "q-cpp-java-loop-4",
          prompt: "Why does this throw ConcurrentModificationException?",
          brokenCode: 'List<String> list = new ArrayList<>(Arrays.asList("a", "b", "c"));\nfor (String s : list) {\n    if (s.equals("b")) list.remove(s);\n}',
          choices: [
            "You can't modify a collection while iterating with enhanced for-loop",
            "remove() doesn't work on ArrayLists",
            "equals() is wrong for strings",
            "Missing break statement",
          ],
          correctIndex: 0,
          explanation: "Use `Iterator.remove()` or `list.removeIf(s -> s.equals(\"b\"))` instead.",
          xp: 15,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-loop-5",
          prompt: "What does `::` mean in `System.out::println`?",
          choices: [
            "Scope resolution (like C++)",
            "Method reference — shorthand for a lambda",
            "Static import",
            "Namespace separator",
          ],
          correctIndex: 1,
          explanation: "`System.out::println` is a method reference, equivalent to `x -> System.out.println(x)`.",
          xp: 10,
        },
      ],
    },
    {
      id: "cpp-java-functions",
      title: "Methods & Lambdas",
      tagline: "Everything lives in a class — no free functions.",
      icon: "⚔️",
      level: "beginner",
      order: 4,
      requires: ["cpp-java-loops"],
      rewardXp: 90,
      lessons: [
        {
          id: "lesson-cpp-java-fn-1",
          title: "Methods (no free functions)",
          intro:
            "Java has no free functions — every function is a method inside a class. `static` methods are the closest thing to C++ free functions. Method overloading works the same way. Java has no default arguments — use overloading instead. Since Java 8, lambdas and method references enable functional programming.",
          comparisons: [
            {
              concept: "Function → static method",
              knownCode: "int add(int a, int b) {\n    return a + b;\n}",
              targetCode: "static int add(int a, int b) {\n    return a + b;\n}",
              note: "Must be inside a class. `static` means no instance needed.",
            },
            {
              concept: "Method overloading",
              knownCode: "int max(int a, int b);\ndouble max(double a, double b);",
              targetCode: "static int max(int a, int b) { return a > b ? a : b; }\nstatic double max(double a, double b) { return a > b ? a : b; }",
              note: "Overloading by parameter types works identically to C++.",
            },
            {
              concept: "Lambda expressions (Java 8+)",
              knownCode: "auto square = [](int x) { return x * x; };",
              targetCode: "// Functional interface required\nFunction<Integer, Integer> square = x -> x * x;",
              note: "Java lambdas need a functional interface type. No `auto` equivalent for lambda types.",
            },
          ],
          realWorld:
            "Common functional interfaces: `Function<T,R>`, `Predicate<T>`, `Consumer<T>`, `Supplier<T>`. The `java.util.function` package has dozens.",
          exercise: {
            id: "ex-cpp-java-fn-1",
            prompt: "Write a static method `square(int n)` that returns n*n. Call it with 6 and print the result.",
            starterCode: "// static int square(int n) { ... }\n",
            solution: "static int square(int n) {\n    return n * n;\n}\n// In main: System.out.println(square(6));",
            expectedOutputIncludes: "36",
            xp: 25,
          },
        },
      ],
      quiz: [
        {
          kind: "mcq",
          id: "q-cpp-java-fn-1",
          prompt: "Can Java have free functions (outside a class)?",
          choices: [
            "Yes, like C++",
            "No — every function must be in a class",
            "Only lambdas",
            "Only in scripts",
          ],
          correctIndex: 1,
          explanation: "Everything in Java is inside a class. Use `static` for utility functions.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-fn-2",
          prompt: "Java doesn't support default arguments. What's the alternative?",
          choices: [
            "Optional parameters",
            "Method overloading",
            "Named parameters",
            "Macros",
          ],
          correctIndex: 1,
          explanation: "Define multiple methods with different parameter lists.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-fn-3",
          prompt: "Java lambdas require a…",
          choices: [
            "Return type annotation",
            "Functional interface (single abstract method)",
            "Template parameter",
            "Lambda keyword",
          ],
          correctIndex: 1,
          explanation: "Java lambdas are implementations of functional interfaces (interfaces with one abstract method).",
          xp: 10,
        },
        {
          kind: "debug",
          id: "q-cpp-java-fn-4",
          prompt: "Why doesn't this compile?",
          brokenCode: "int add(int a, int b = 0) {\n    return a + b;\n}",
          choices: [
            "Java doesn't support default parameter values",
            "Return type should be Integer",
            "Missing static keyword",
            "b must be final",
          ],
          correctIndex: 0,
          explanation: "Use method overloading: `int add(int a) { return add(a, 0); }`.",
          xp: 15,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-fn-5",
          prompt: "What is `x -> x * 2` in Java?",
          choices: [
            "A pointer expression",
            "A lambda expression",
            "A method declaration",
            "An arrow function (not valid Java)",
          ],
          correctIndex: 1,
          explanation: "`->` separates parameters from the body in a lambda expression.",
          xp: 10,
        },
      ],
    },
    {
      id: "cpp-java-collections",
      title: "Strings & Collections",
      tagline: "ArrayList, HashMap, and the Collections framework.",
      icon: "📜",
      level: "beginner",
      order: 5,
      requires: ["cpp-java-functions"],
      rewardXp: 100,
      lessons: [
        {
          id: "lesson-cpp-java-col-1",
          title: "Strings in Java",
          intro:
            "Java `String` is an immutable reference type (not a primitive). String comparison uses `.equals()` — not `==` (which compares references). `StringBuilder` is for mutable string construction. Java has text blocks (multiline strings) since Java 15.",
          comparisons: [
            {
              concept: "String comparison",
              knownCode: 'if (s1 == s2) { ... }  // Compares content in C++',
              targetCode: 'if (s1.equals(s2)) { ... }  // Must use .equals() in Java!',
              note: "`==` compares references (memory addresses) in Java, not content!",
            },
            {
              concept: "String formatting",
              knownCode: 'printf("Hello, %s!", name);',
              targetCode: 'String.format("Hello, %s!", name)\n// Or: "Hello, " + name + "!"',
              note: "Java 21+ will have string templates. For now, use `String.format` or concatenation.",
            },
            {
              concept: "StringBuilder",
              knownCode: "std::ostringstream oss;\noss << \"Hello\" << \" World\";",
              targetCode: 'StringBuilder sb = new StringBuilder();\nsb.append("Hello").append(" World");\nString result = sb.toString();',
              note: "Use `StringBuilder` in loops — concatenation with `+` creates many temporary objects.",
            },
          ],
          realWorld:
            "The `==` vs `.equals()` pitfall is one of the most common Java bugs. Always use `.equals()` for String comparison.",
          exercise: {
            id: "ex-cpp-java-col-1",
            prompt:
              'Check if two strings "hello" and "hello" are equal using `.equals()` and print the result.',
            starterCode: 'String a = "hello";\nString b = "hello";\n// Compare and print\n',
            solution:
              'String a = "hello";\nString b = "hello";\nSystem.out.println(a.equals(b));',
            expectedOutputIncludes: "true",
            xp: 20,
          },
        },
        {
          id: "lesson-cpp-java-col-2",
          title: "Collections framework",
          intro:
            "Java's Collections framework provides `List`, `Set`, `Map`, `Queue`, and more. Unlike C++ STL, Java uses interfaces (`List<T>`) with implementations (`ArrayList<T>`, `LinkedList<T>`). Generics use `<>` but with type erasure (unlike C++ templates). No operator overloading — use `.get()`, `.put()`, `.add()`.",
          comparisons: [
            {
              concept: "Dynamic array (vector/list)",
              knownCode: "std::vector<int> nums = {1, 2, 3};\nnums.push_back(4);",
              targetCode: "List<Integer> nums = new ArrayList<>(List.of(1, 2, 3));\nnums.add(4);",
              note: "Must use `Integer` (wrapper) — generics don't work with primitives.",
            },
            {
              concept: "Hash map",
              knownCode: 'std::unordered_map<std::string, int> ages;\nages["Ada"] = 36;',
              targetCode: 'Map<String, Integer> ages = new HashMap<>();\nages.put("Ada", 36);',
              note: "`.put(key, val)` and `.get(key)` — no operator[] overloading.",
            },
            {
              concept: "Iterating a map",
              knownCode: "for (const auto& [k, v] : map) { ... }",
              targetCode: "for (Map.Entry<String, Integer> e : ages.entrySet()) {\n    System.out.println(e.getKey() + \": \" + e.getValue());\n}",
              note: "Or use `ages.forEach((k, v) -> ...)` with Java 8+ lambdas.",
            },
          ],
          realWorld:
            "Program to interfaces: declare `List<T>`, not `ArrayList<T>`. This lets you swap implementations easily.",
          exercise: {
            id: "ex-cpp-java-col-2",
            prompt:
              'Create a `HashMap<String, Integer>` with entries "Alice"→90 and "Bob"→85. Print Bob\'s score.',
            starterCode: "// Create map and print Bob's score\n",
            solution:
              'Map<String, Integer> scores = new HashMap<>();\nscores.put("Alice", 90);\nscores.put("Bob", 85);\nSystem.out.println(scores.get("Bob"));',
            expectedOutputIncludes: "85",
            xp: 30,
          },
        },
      ],
      quiz: [
        {
          kind: "mcq",
          id: "q-cpp-java-col-1",
          prompt: "How should you compare strings in Java?",
          choices: ["s1 == s2", "s1.equals(s2)", "strcmp(s1, s2)", "s1.compare(s2)"],
          correctIndex: 1,
          explanation: "`==` compares references. `.equals()` compares content.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-col-2",
          prompt: "Why can't you use `List<int>` in Java?",
          choices: [
            "int is not imported",
            "Generics don't work with primitive types — use Integer",
            "List doesn't support numbers",
            "Must use ArrayList instead",
          ],
          correctIndex: 1,
          explanation: "Java generics use type erasure — only reference types are supported.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-col-3",
          prompt: "What is `Map.Entry<K, V>` used for?",
          choices: [
            "Creating new maps",
            "Iterating over key-value pairs",
            "Sorting maps",
            "Thread-safe map access",
          ],
          correctIndex: 1,
          explanation: "`entrySet()` returns `Set<Map.Entry<K,V>>` for iteration.",
          xp: 10,
        },
        {
          kind: "debug",
          id: "q-cpp-java-col-4",
          prompt: "Why does this print 'false'?",
          brokenCode: 'String a = new String("hello");\nString b = new String("hello");\nSystem.out.println(a == b);',
          choices: [
            "`==` compares references, not content — use `.equals()`",
            "Strings can't use ==",
            "new String creates immutable objects",
            "Missing toString()",
          ],
          correctIndex: 0,
          explanation: "`new String` creates distinct objects. `==` compares object identity, not value.",
          xp: 15,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-col-5",
          prompt: "Which is the best practice for declaring a List variable?",
          choices: [
            "ArrayList<String> list = new ArrayList<>();",
            "List<String> list = new ArrayList<>();",
            "var list = new ArrayList<String>();",
            "Both B and C are acceptable",
          ],
          correctIndex: 3,
          explanation: "Program to the interface (`List<>`) or use `var` for local variables.",
          xp: 10,
        },
      ],
    },

    // ===================== INTERMEDIATE =====================
    {
      id: "cpp-java-oop",
      title: "OOP & Classes",
      tagline: "Interfaces, abstract classes, and no multiple inheritance.",
      icon: "👑",
      level: "intermediate",
      order: 1,
      requires: [],
      rewardXp: 120,
      lessons: [
        {
          id: "lesson-cpp-java-oop-1",
          title: "Classes, interfaces, and inheritance",
          intro:
            "Java has single inheritance (one parent class) + multiple interface implementation. Interfaces define contracts — since Java 8, they can have default methods. Abstract classes are like C++ abstract classes. Access modifiers: `public`, `protected`, `private`, and package-private (no modifier).",
          comparisons: [
            {
              concept: "Class with constructor",
              knownCode: 'class Hero {\npublic:\n    std::string name;\n    Hero(const std::string& n) : name(n) {}\n};',
              targetCode: 'public class Hero {\n    private String name;\n    public Hero(String name) {\n        this.name = name;\n    }\n}',
              note: "No initializer lists. Fields default to 0/null/false.",
            },
            {
              concept: "Interface (pure virtual)",
              knownCode: "class Drawable {\npublic:\n    virtual void draw() = 0;\n};",
              targetCode: "public interface Drawable {\n    void draw();\n}",
              note: "Interfaces are cleaner than C++ pure virtual classes — no vtable concerns.",
            },
            {
              concept: "Multiple interfaces",
              knownCode: "class Shape : public Drawable, public Serializable { ... };",
              targetCode: "public class Shape implements Drawable, Serializable { ... }",
              note: "Java uses `implements` for interfaces, `extends` for classes.",
            },
          ],
          realWorld:
            "Java 16+ has `record` classes for immutable data: `record Point(int x, int y) {}` auto-generates constructor, getters, equals, hashCode, toString.",
          exercise: {
            id: "ex-cpp-java-oop-1",
            prompt: "Create an interface `Greetable` with a `greet()` method. Implement it in a class `Person` with a name field. Print the greeting.",
            starterCode: "// interface Greetable { ... }\n// class Person implements Greetable { ... }\n",
            solution: 'interface Greetable {\n    String greet();\n}\n\nclass Person implements Greetable {\n    private String name;\n    public Person(String name) { this.name = name; }\n    public String greet() { return "Hello, " + name + "!"; }\n}\n\nPerson p = new Person("Ada");\nSystem.out.println(p.greet());',
            expectedOutputIncludes: "Hello, Ada!",
            xp: 40,
          },
        },
      ],
      quiz: [
        {
          kind: "mcq",
          id: "q-cpp-java-oop-1",
          prompt: "Java supports multiple inheritance of…",
          choices: [
            "Classes",
            "Interfaces only",
            "Both classes and interfaces",
            "Neither",
          ],
          correctIndex: 1,
          explanation: "Java: single class inheritance, multiple interface implementation.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-oop-2",
          prompt: "What keyword does Java use to inherit from a class?",
          choices: ["inherits", "extends", "implements", ":"],
          correctIndex: 1,
          explanation: "`extends` for classes, `implements` for interfaces.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-oop-3",
          prompt: "What does `record Point(int x, int y) {}` do in Java 16+?",
          choices: [
            "Creates a mutable class",
            "Creates an immutable data class with auto-generated methods",
            "Creates a database record",
            "Defines a struct",
          ],
          correctIndex: 1,
          explanation: "Records auto-generate constructor, getters, equals(), hashCode(), and toString().",
          xp: 10,
        },
        {
          kind: "debug",
          id: "q-cpp-java-oop-4",
          prompt: "Why doesn't this compile?",
          brokenCode: "public class Dog extends Animal, Pet { ... }",
          choices: [
            "Java doesn't support extending multiple classes",
            "Animal and Pet must be interfaces",
            "Missing import",
            "Need 'implements' keyword",
          ],
          correctIndex: 0,
          explanation: "Only single class inheritance. If Pet is an interface, use `extends Animal implements Pet`.",
          xp: 15,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-oop-5",
          prompt: "What is Java's default access modifier (no keyword)?",
          choices: ["public", "private", "protected", "package-private"],
          correctIndex: 3,
          explanation: "No modifier = package-private. Accessible within the same package only.",
          xp: 10,
        },
      ],
    },
    {
      id: "cpp-java-errors",
      title: "Error Handling",
      tagline: "Checked vs unchecked exceptions.",
      icon: "🔥",
      level: "intermediate",
      order: 2,
      requires: ["cpp-java-oop"],
      rewardXp: 110,
      lessons: [
        {
          id: "lesson-cpp-java-err-1",
          title: "Exceptions: checked and unchecked",
          intro:
            "Java distinguishes between checked exceptions (must be caught or declared with `throws`) and unchecked exceptions (`RuntimeException` and its subclasses — like `NullPointerException`, `ArrayIndexOutOfBoundsException`). This is unique to Java — C++ has no checked exceptions.",
          comparisons: [
            {
              concept: "Try/catch",
              knownCode: 'try {\n    risky();\n} catch (const std::exception& e) {\n    std::cerr << e.what();\n}',
              targetCode: 'try {\n    risky();\n} catch (IOException e) {\n    System.err.println(e.getMessage());\n}',
              note: "Java uses class names, not references. Can catch multiple: `catch (A | B e)`.",
            },
            {
              concept: "Throwing exceptions",
              knownCode: 'throw std::runtime_error("fail");',
              targetCode: 'throw new RuntimeException("fail");',
              note: "`new` is required — exceptions are objects in Java.",
            },
            {
              concept: "Checked exceptions",
              knownCode: "// C++ has no equivalent",
              targetCode: "public void readFile(String path) throws IOException {\n    // IOException is checked — caller MUST handle it\n}",
              note: "Checked exceptions force the caller to handle or propagate — love it or hate it.",
            },
          ],
          realWorld:
            "Modern Java code increasingly uses unchecked exceptions. Many frameworks (Spring, etc.) wrap checked exceptions in unchecked ones.",
          exercise: {
            id: "ex-cpp-java-err-1",
            prompt:
              'Write a try/catch that parses "abc" as an integer and catches NumberFormatException, printing "Invalid number".',
            starterCode: '// Try to parse "abc" as int\n',
            solution:
              'try {\n    int n = Integer.parseInt("abc");\n} catch (NumberFormatException e) {\n    System.out.println("Invalid number");\n}',
            expectedOutputIncludes: "Invalid number",
            xp: 30,
          },
        },
      ],
      quiz: [
        {
          kind: "mcq",
          id: "q-cpp-java-err-1",
          prompt: "What are checked exceptions in Java?",
          choices: [
            "Exceptions that are checked at runtime",
            "Exceptions that must be caught or declared with `throws`",
            "Exceptions that can't be caught",
            "All exceptions",
          ],
          correctIndex: 1,
          explanation: "Checked exceptions (not RuntimeException) must be handled at compile time.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-err-2",
          prompt: "`NullPointerException` is a…",
          choices: [
            "Checked exception",
            "Unchecked exception (RuntimeException)",
            "Error",
            "Compile-time exception",
          ],
          correctIndex: 1,
          explanation: "NPE extends RuntimeException — unchecked, doesn't need to be declared.",
          xp: 10,
        },
        {
          kind: "debug",
          id: "q-cpp-java-err-3",
          prompt: "Why doesn't this compile?",
          brokenCode: 'public void read() {\n    FileReader fr = new FileReader("file.txt");\n}',
          choices: [
            "FileReader constructor throws checked IOException — must catch or declare",
            "FileReader doesn't exist",
            "Missing import",
            "Need try-with-resources",
          ],
          correctIndex: 0,
          explanation: "Add `throws IOException` to the method signature or wrap in try/catch.",
          xp: 15,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-err-3b",
          prompt: "Java's `try-with-resources` is similar to C++…",
          choices: [
            "RAII (stack-based cleanup)",
            "try/catch",
            "shared_ptr",
            "delete keyword",
          ],
          correctIndex: 0,
          explanation: "`try (Resource r = ...) { }` auto-closes resources, like RAII.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-err-4",
          prompt: "How do you catch multiple exception types in one block?",
          choices: [
            "catch (A, B e)",
            "catch (A | B e)",
            "catch (A or B e)",
            "catch A catch B",
          ],
          correctIndex: 1,
          explanation: "Multi-catch: `catch (IOException | SQLException e)`.",
          xp: 10,
        },
      ],
    },
    {
      id: "cpp-java-packages",
      title: "Packages & Build Tools",
      tagline: "Maven, Gradle, and the classpath.",
      icon: "📦",
      level: "intermediate",
      order: 3,
      requires: ["cpp-java-errors"],
      rewardXp: 100,
      lessons: [
        {
          id: "lesson-cpp-java-pkg-1",
          title: "Packages and imports",
          intro:
            "Java organizes code into packages (like C++ namespaces, but tied to directory structure). `package com.myapp.models;` at the top of a file places it in that package. `import java.util.List;` imports a class. Build tools like Maven (`pom.xml`) and Gradle (`build.gradle`) manage dependencies and builds.",
          comparisons: [
            {
              concept: "Namespaces → Packages",
              knownCode: "namespace myapp::models {\n    class User { ... };\n}",
              targetCode: "package com.myapp.models;\n\npublic class User { ... }",
              note: "Package name must match directory structure: `com/myapp/models/User.java`.",
            },
            {
              concept: "Build system",
              knownCode: "// CMakeLists.txt, Makefile",
              targetCode: "// Maven: pom.xml\n// Gradle: build.gradle\n// Dependencies from Maven Central",
              note: "Maven/Gradle handle dependency resolution, compilation, testing, and packaging.",
            },
          ],
          realWorld:
            "Gradle is the modern choice (used by Android). Maven is still dominant in enterprise Java. Both download deps from Maven Central.",
          exercise: {
            id: "ex-cpp-java-pkg-1",
            prompt: "Write the package declaration and import for a class in `com.app.utils` that uses `java.util.List`.",
            starterCode: "// Package and import declarations\n",
            solution: "package com.app.utils;\n\nimport java.util.List;\n\n// public class MyUtils { ... }",
            expectedOutputIncludes: "package",
            xp: 20,
          },
        },
      ],
      quiz: [
        {
          kind: "mcq",
          id: "q-cpp-java-pkg-1",
          prompt: "Java packages are most similar to C++…",
          choices: ["Headers", "Namespaces", "Modules (C++20)", "Libraries"],
          correctIndex: 1,
          explanation: "Packages organize code like namespaces, but are tied to directory structure.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-pkg-2",
          prompt: "What build tool is most common in modern Java?",
          choices: ["Make", "CMake", "Maven or Gradle", "Ant"],
          correctIndex: 2,
          explanation: "Maven and Gradle are the dominant Java build tools.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-pkg-3",
          prompt: "Must package names match directory structure?",
          choices: ["No, it's just a convention", "Yes, strictly required", "Only for public classes", "Only with Maven"],
          correctIndex: 1,
          explanation: "Package `com.app.utils` must be in directory `com/app/utils/`.",
          xp: 10,
        },
        {
          kind: "debug",
          id: "q-cpp-java-pkg-4",
          prompt: "Why can't you access this class?",
          brokenCode: "// File: com/app/Secret.java\npackage com.app;\nclass Secret { }  // Note: no 'public' keyword",
          choices: [
            "Package-private (no modifier) — only accessible within same package",
            "Missing import",
            "Class name must match file name",
            "Need 'extends Object'",
          ],
          correctIndex: 0,
          explanation: "No access modifier = package-private. Add `public` to make it accessible outside the package.",
          xp: 15,
        },
      ],
    },
    {
      id: "cpp-java-streams",
      title: "Functional Patterns & Streams",
      tagline: "Stream API: map, filter, reduce the Java way.",
      icon: "⚡",
      level: "intermediate",
      order: 4,
      requires: ["cpp-java-packages"],
      rewardXp: 130,
      lessons: [
        {
          id: "lesson-cpp-java-stream-1",
          title: "Stream API deep dive",
          intro:
            "Java's Stream API (Java 8+) provides functional data processing. Create a stream from a collection (`.stream()`), chain operations (`.map()`, `.filter()`, `.sorted()`), and collect results (`.collect(Collectors.toList())`). Streams are lazy — operations only execute on terminal operations.",
          comparisons: [
            {
              concept: "Map + Filter + Collect",
              knownCode: "// C++ ranges (C++20): v | filter(...) | transform(...)",
              targetCode: 'List<String> upper = names.stream()\n    .filter(n -> n.length() > 3)\n    .map(String::toUpperCase)\n    .collect(Collectors.toList());',
              note: "Terminal operations: `collect()`, `forEach()`, `reduce()`, `count()`.",
            },
            {
              concept: "Reduce",
              knownCode: "int sum = std::accumulate(v.begin(), v.end(), 0);",
              targetCode: "int sum = nums.stream()\n    .reduce(0, Integer::sum);",
            },
          ],
          realWorld:
            "Streams should be used for declarative data transformation. Don't use them for side-effect-heavy code — use regular loops.",
          exercise: {
            id: "ex-cpp-java-stream-1",
            prompt: "Given a list of integers [1,2,3,4,5], use Streams to filter even numbers, square them, and collect to a list. Print the result.",
            starterCode: "List<Integer> nums = List.of(1, 2, 3, 4, 5);\n// Stream pipeline\n",
            solution: "List<Integer> nums = List.of(1, 2, 3, 4, 5);\nList<Integer> result = nums.stream()\n    .filter(n -> n % 2 == 0)\n    .map(n -> n * n)\n    .collect(Collectors.toList());\nSystem.out.println(result);",
            expectedOutputIncludes: "[4, 16]",
            xp: 40,
          },
        },
      ],
      quiz: [
        {
          kind: "mcq",
          id: "q-cpp-java-stream-1",
          prompt: "Streams are evaluated…",
          choices: ["Eagerly", "Lazily — only on terminal operations", "In parallel by default", "At compile time"],
          correctIndex: 1,
          explanation: "Intermediate operations are lazy. A terminal operation triggers the pipeline.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-stream-2",
          prompt: "Which is a terminal operation?",
          choices: [".map()", ".filter()", ".collect()", ".sorted()"],
          correctIndex: 2,
          explanation: "`.collect()` triggers execution and produces a result.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-stream-3",
          prompt: "How do you create a stream from a List?",
          choices: ["Stream.of(list)", "list.stream()", "new Stream(list)", "list.toStream()"],
          correctIndex: 1,
          explanation: "`.stream()` is a method on all Collection types.",
          xp: 10,
        },
        {
          kind: "debug",
          id: "q-cpp-java-stream-4",
          prompt: "Why does this throw IllegalStateException?",
          brokenCode: "Stream<String> s = names.stream();\ns.forEach(System.out::println);\ns.forEach(System.out::println);  // Crash!",
          choices: [
            "Streams can only be consumed once — create a new stream for the second use",
            "forEach is not a valid operation",
            "Missing collect()",
            "Streams are thread-unsafe",
          ],
          correctIndex: 0,
          explanation: "Streams are single-use. Create a new `.stream()` for each consumption.",
          xp: 15,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-stream-5",
          prompt: "What does `.parallelStream()` do?",
          choices: [
            "Creates a synchronized stream",
            "Enables parallel processing using ForkJoinPool",
            "Runs the stream on GPU",
            "Makes the stream thread-safe",
          ],
          correctIndex: 1,
          explanation: "Parallel streams distribute work across CPU cores. Use for CPU-heavy operations on large datasets.",
          xp: 10,
        },
      ],
    },

    // ===================== ADVANCED =====================
    {
      id: "cpp-java-memory",
      title: "Memory & JVM",
      tagline: "Garbage collection vs manual memory.",
      icon: "🧠",
      level: "advanced",
      order: 1,
      requires: [],
      rewardXp: 150,
      lessons: [
        {
          id: "lesson-cpp-java-mem-1",
          title: "JVM memory model and GC",
          intro:
            "Java runs on the JVM with automatic garbage collection. No `new`/`delete` pairing — objects are heap-allocated and GC'd when unreachable. The JVM has generations (young/old) and multiple GC algorithms (G1, ZGC, Shenandoah). `try-with-resources` handles deterministic cleanup for non-memory resources (files, connections).",
          comparisons: [
            {
              concept: "Object lifecycle",
              knownCode: "Hero* h = new Hero();\n// ...\ndelete h;  // Manual cleanup",
              targetCode: "Hero h = new Hero();\n// No delete needed — GC handles it",
              note: "All objects live on the heap. Primitives live on the stack.",
            },
            {
              concept: "Deterministic cleanup (RAII)",
              knownCode: "{\n    std::ifstream file(\"data.txt\");\n    // Closed on scope exit (RAII)\n}",
              targetCode: 'try (var reader = new FileReader("data.txt")) {\n    // Auto-closed at end of try block\n}',
              note: "`try-with-resources` works with any `AutoCloseable` — Java's RAII equivalent.",
            },
          ],
          realWorld:
            "JVM tuning (heap size, GC algorithm) is crucial for production Java. `-Xmx` sets max heap. G1GC is the default in Java 9+.",
          exercise: {
            id: "ex-cpp-java-mem-1",
            prompt: "Explain (in a comment) why Java doesn't need a destructor. Then write a try-with-resources using a Scanner on System.in that reads one line.",
            starterCode: "import java.util.Scanner;\n// Why no destructor needed?\n",
            solution: 'import java.util.Scanner;\n// Java uses garbage collection for memory and try-with-resources for other cleanup.\ntry (Scanner sc = new Scanner(System.in)) {\n    String line = sc.nextLine();\n    System.out.println(line);\n}',
            expectedOutputIncludes: "",
            xp: 35,
          },
        },
      ],
      quiz: [
        {
          kind: "mcq",
          id: "q-cpp-java-mem-1",
          prompt: "Where do Java objects live?",
          choices: ["Stack only", "Heap only", "Stack or heap (compiler decides)", "Registers"],
          correctIndex: 1,
          explanation: "All objects are heap-allocated. Only primitives and references live on the stack.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-mem-2",
          prompt: "What is `try-with-resources` for?",
          choices: [
            "Memory management",
            "Deterministic cleanup of AutoCloseable resources",
            "Thread synchronization",
            "Exception logging",
          ],
          correctIndex: 1,
          explanation: "Auto-closes resources (files, connections) at end of the try block.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-mem-3",
          prompt: "Java's default garbage collector (Java 9+) is…",
          choices: ["Serial GC", "Parallel GC", "G1 GC", "ZGC"],
          correctIndex: 2,
          explanation: "G1GC is the default since Java 9. ZGC and Shenandoah are for low-latency.",
          xp: 10,
        },
        {
          kind: "debug",
          id: "q-cpp-java-mem-4",
          prompt: "What's the problem here?",
          brokenCode: 'FileReader fr = new FileReader("data.txt");\nString data = readAll(fr);\n// fr is never closed!',
          choices: [
            "Resource leak — use try-with-resources or explicit close()",
            "FileReader doesn't exist",
            "Missing import",
            "No problem — GC will close it",
          ],
          correctIndex: 0,
          explanation: "GC handles memory, but NOT file handles. Always close I/O resources explicitly.",
          xp: 15,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-mem-5",
          prompt: "What JVM flag sets maximum heap size?",
          choices: ["-Xss", "-Xmx", "-Xms", "-Xgc"],
          correctIndex: 1,
          explanation: "`-Xmx512m` sets max heap to 512MB. `-Xms` sets initial heap size.",
          xp: 10,
        },
      ],
    },
    {
      id: "cpp-java-concurrency",
      title: "Concurrency & Threads",
      tagline: "Real threads, synchronized blocks, and virtual threads.",
      icon: "🔄",
      level: "advanced",
      order: 2,
      requires: ["cpp-java-memory"],
      rewardXp: 170,
      lessons: [
        {
          id: "lesson-cpp-java-conc-1",
          title: "Threading in Java",
          intro:
            "Java has first-class threading with `Thread`, `Runnable`, and `synchronized`. Unlike Python, Java threads run truly in parallel (no GIL). Java 21+ introduced virtual threads (Project Loom) — lightweight threads that can scale to millions. `CompletableFuture` provides async composition similar to C++ futures.",
          comparisons: [
            {
              concept: "Creating threads",
              knownCode: "#include <thread>\nstd::thread t(func);\nt.join();",
              targetCode: "Thread t = new Thread(() -> {\n    System.out.println(\"Hello from thread\");\n});\nt.start();\nt.join();",
              note: "Use `start()` not `run()`. `run()` executes synchronously!",
            },
            {
              concept: "Synchronization",
              knownCode: "std::mutex mtx;\nstd::lock_guard<std::mutex> lock(mtx);",
              targetCode: "synchronized (lockObject) {\n    // Critical section\n}",
              note: "`synchronized` is built into the language — no separate mutex class needed.",
            },
            {
              concept: "Virtual threads (Java 21+)",
              knownCode: "// No C++ equivalent",
              targetCode: "Thread.startVirtualThread(() -> {\n    // Lightweight thread — can have millions\n});",
              note: "Virtual threads are ideal for I/O-bound tasks. They're scheduled by the JVM, not the OS.",
            },
          ],
          realWorld:
            "Virtual threads (Project Loom) are a game-changer for Java server applications. They eliminate the need for reactive/async frameworks in many cases.",
          exercise: {
            id: "ex-cpp-java-conc-1",
            prompt: "Create a Thread that prints 'Hello from thread', start it, and join it.",
            starterCode: "// Create, start, and join a thread\n",
            solution: 'Thread t = new Thread(() -> System.out.println("Hello from thread"));\nt.start();\nt.join();',
            expectedOutputIncludes: "Hello from thread",
            xp: 40,
          },
        },
      ],
      quiz: [
        {
          kind: "mcq",
          id: "q-cpp-java-conc-1",
          prompt: "Does Java have a GIL like Python?",
          choices: [
            "Yes",
            "No — Java threads run truly in parallel",
            "Only for synchronized blocks",
            "Only on single-core systems",
          ],
          correctIndex: 1,
          explanation: "Java threads are OS threads with true parallel execution.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-conc-2",
          prompt: "What are virtual threads (Java 21+)?",
          choices: [
            "Simulated threads for testing",
            "Lightweight JVM-managed threads that can scale to millions",
            "Threads that run on GPU",
            "Deprecated thread type",
          ],
          correctIndex: 1,
          explanation: "Virtual threads are lightweight and managed by the JVM, not the OS kernel.",
          xp: 10,
        },
        {
          kind: "debug",
          id: "q-cpp-java-conc-3",
          prompt: "Why doesn't this print anything?",
          brokenCode: 'Thread t = new Thread(() -> System.out.println("hi"));\nt.run();  // Wrong!',
          choices: [
            "`run()` executes synchronously on the current thread — use `start()` for a new thread",
            "Lambda syntax is wrong",
            "Missing join()",
            "Thread is not started",
          ],
          correctIndex: 0,
          explanation: "`run()` just calls the method normally. `start()` creates a new OS thread.",
          xp: 15,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-conc-4",
          prompt: "What is `synchronized` in Java?",
          choices: [
            "A type annotation",
            "Built-in mutex/lock mechanism for critical sections",
            "A thread priority setting",
            "A method return type",
          ],
          correctIndex: 1,
          explanation: "`synchronized` blocks acquire an intrinsic lock on an object.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-conc-5",
          prompt: "Java's `CompletableFuture` is most like C++…",
          choices: [
            "std::thread",
            "std::future + std::promise",
            "std::mutex",
            "std::atomic",
          ],
          correctIndex: 1,
          explanation: "CompletableFuture combines future and promise with chaining capabilities.",
          xp: 10,
        },
      ],
    },
    {
      id: "cpp-java-generics",
      title: "Generics & Advanced Patterns",
      tagline: "Type erasure, wildcards, and design patterns.",
      icon: "✨",
      level: "advanced",
      order: 3,
      requires: ["cpp-java-concurrency"],
      rewardXp: 200,
      lessons: [
        {
          id: "lesson-cpp-java-gen-1",
          title: "Generics vs Templates",
          intro:
            "Java generics look like C++ templates but work fundamentally differently. Java uses type erasure — generic type info is removed at compile time. This means no `new T()`, no `T.class`, no primitive type params. C++ templates generate new code per type; Java generics share one implementation. Wildcards (`? extends T`, `? super T`) handle covariance/contravariance.",
          comparisons: [
            {
              concept: "Generic class",
              knownCode: "template <typename T>\nclass Box {\n    T value;\n};",
              targetCode: "public class Box<T> {\n    private T value;\n    public Box(T value) { this.value = value; }\n    public T get() { return value; }\n}",
              note: "No specialization. No primitive types (use wrappers).",
            },
            {
              concept: "Bounded type",
              knownCode: "template <typename T>\nconcept Comparable = ...;",
              targetCode: "public <T extends Comparable<T>> T max(T a, T b) {\n    return a.compareTo(b) > 0 ? a : b;\n}",
              note: "`extends` for upper bounds. `super` for lower bounds (in wildcards).",
            },
            {
              concept: "Wildcards",
              knownCode: "// No direct C++ equivalent",
              targetCode: "void printAll(List<? extends Number> list) {\n    // Can read as Number, can't add\n}",
              note: "PECS: Producer Extends, Consumer Super.",
            },
          ],
          realWorld:
            "Type erasure means you can't do `new T()` or `instanceof T` at runtime. This is Java's biggest generics limitation vs C++ templates.",
          exercise: {
            id: "ex-cpp-java-gen-1",
            prompt: "Create a generic `Pair<A, B>` class with two fields and a `toString()` method. Create a `Pair<String, Integer>` and print it.",
            starterCode: "// class Pair<A, B> { ... }\n",
            solution: 'class Pair<A, B> {\n    private A first;\n    private B second;\n    public Pair(A first, B second) {\n        this.first = first;\n        this.second = second;\n    }\n    public String toString() {\n        return "(" + first + ", " + second + ")";\n    }\n}\n\nSystem.out.println(new Pair<>("Ada", 36));',
            expectedOutputIncludes: "(Ada, 36)",
            xp: 50,
          },
        },
      ],
      quiz: [
        {
          kind: "mcq",
          id: "q-cpp-java-gen-1",
          prompt: "Java generics use…",
          choices: [
            "Code generation per type (like C++ templates)",
            "Type erasure — generic info removed at compile time",
            "Runtime type checking only",
            "Duck typing",
          ],
          correctIndex: 1,
          explanation: "Type erasure means one compiled class for all generic instantiations.",
          xp: 10,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-gen-2",
          prompt: "Why can't you write `new T()` in Java generics?",
          choices: [
            "T is not a class",
            "Type erasure — T is replaced with Object at runtime",
            "new doesn't work with generics",
            "T must be final",
          ],
          correctIndex: 1,
          explanation: "At runtime, T is just Object. The compiler can't know which constructor to call.",
          xp: 15,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-gen-3",
          prompt: "What does PECS stand for?",
          choices: [
            "Producer Extends, Consumer Super",
            "Private Encapsulated Class Structure",
            "Parameterized Extended Class System",
            "Producer Emits, Consumer Stores",
          ],
          correctIndex: 0,
          explanation: "Use `? extends T` when reading (producing), `? super T` when writing (consuming).",
          xp: 10,
        },
        {
          kind: "debug",
          id: "q-cpp-java-gen-4",
          prompt: "Why doesn't this compile?",
          brokenCode: "List<int> numbers = new ArrayList<>();",
          choices: [
            "Generics can't use primitive types — use `List<Integer>`",
            "ArrayList is deprecated",
            "Missing import",
            "int is not a valid type",
          ],
          correctIndex: 0,
          explanation: "Java generics require reference types. Use wrapper classes for primitives.",
          xp: 15,
        },
        {
          kind: "mcq",
          id: "q-cpp-java-gen-5",
          prompt: "What does `? extends Number` mean?",
          choices: [
            "Any type that is Number or a subclass",
            "Any type that Number extends",
            "A number with extensions",
            "An optional Number",
          ],
          correctIndex: 0,
          explanation: "Upper bounded wildcard: accepts Number, Integer, Double, etc.",
          xp: 10,
        },
      ],
    },
  ],
};
