import type { Course } from "@/lib/types";

export const javaToPython: Course = {
  id: "java-to-python",
  knownLang: "java",
  targetLang: "python",
  title: "Java → Python",
  modules: [
    // ===================== BEGINNER =====================
    {
      id: "java-py-variables",
      title: "Variables & Types",
      tagline: "Drop the types, drop the semicolons.",
      icon: "🏰",
      level: "beginner",
      order: 1,
      requires: [],
      rewardXp: 60,
      lessons: [
        {
          id: "lesson-java-py-vars-1",
          title: "Dynamic typing freedom",
          intro: "Python is dynamically typed — no type declarations needed. `x = 42` just works. No semicolons, no curly braces — Python uses indentation for blocks and newlines for statement termination. Variables can change type freely. Python has `None` instead of `null`, `True/False` instead of `true/false`.",
          comparisons: [
            { concept: "Variable declaration", knownCode: "int count = 0;\nString name = \"Ada\";\nboolean done = false;", targetCode: "count = 0\nname = \"Ada\"\ndone = False", note: "No types, no semicolons. `True/False/None` are capitalized." },
            { concept: "Constants", knownCode: "final int MAX = 100;", targetCode: "MAX = 100  # Convention: ALL_CAPS", note: "Python has no `final`. ALL_CAPS is just a naming convention." },
            { concept: "Type inference", knownCode: "var x = 42;  // Java 10+", targetCode: "x = 42  # Always inferred", note: "Python always infers. Optional type hints: `x: int = 42`." },
            { concept: "Null/None", knownCode: "String s = null;\nif (s == null) { ... }", targetCode: "s = None\nif s is None: ...", note: "Use `is None` (identity check), not `== None`." },
          ],
          realWorld: "Python type hints (`x: int = 42`) are optional but recommended. They enable mypy static checking and better IDE support.",
          exercise: { id: "ex-java-py-vars-1", prompt: "Declare `name` as \"Ada\" and `age` as 36. Print them.", starterCode: "# Declare and print\n", solution: "name = \"Ada\"\nage = 36\nprint(f\"{name} is {age}\")", expectedOutputIncludes: "Ada", xp: 20 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-java-py-var-1", prompt: "Java's `null` becomes Python's…", choices: ["null", "nil", "None", "undefined"], correctIndex: 2, explanation: "Python uses `None` (capitalized).", xp: 10 },
        { kind: "mcq", id: "q-java-py-var-2", prompt: "Java's `true/false` become…", choices: ["true/false", "True/False", "TRUE/FALSE", "1/0"], correctIndex: 1, explanation: "Python booleans are capitalized: `True`, `False`.", xp: 10 },
        { kind: "mcq", id: "q-java-py-var-3", prompt: "How do you check for None in Python?", choices: ["x == null", "x == None", "x is None", "x.isNull()"], correctIndex: 2, explanation: "`is None` checks identity. `== None` works but `is` is preferred.", xp: 10 },
        { kind: "debug", id: "q-java-py-var-4", prompt: "Why does this fail?", brokenCode: "int x = 42", choices: ["Python doesn't use type declarations — just `x = 42`", "Missing semicolon", "int is not a type in Python", "Both A and C"], correctIndex: 3, explanation: "`int` in Python is a function/type, not a declaration keyword. Just write `x = 42`.", xp: 15 },
        { kind: "mcq", id: "q-java-py-var-5", prompt: "Can a variable change type in Python?", choices: ["No — like Java", "Yes — variables are just labels", "Only with casting", "Only for primitives"], correctIndex: 1, explanation: "Python variables are labels. `x = 42; x = 'hello'` is perfectly valid.", xp: 10 },
      ],
    },
    {
      id: "java-py-controlflow",
      title: "Control Flow",
      tagline: "Indentation IS the block — no braces needed.",
      icon: "🛡️",
      level: "beginner",
      order: 2,
      requires: ["java-py-variables"],
      rewardXp: 70,
      lessons: [
        {
          id: "lesson-java-py-cf-1",
          title: "Conditionals without braces",
          intro: "Python uses indentation for blocks — no curly braces. Conditions don't need parentheses but must end with a colon. `else if` becomes `elif`. Python has truthiness: empty collections, 0, None, and empty strings are falsy. Python 3.10+ has `match/case` for pattern matching.",
          comparisons: [
            { concept: "if/else if/else", knownCode: "if (score > 90) {\n    System.out.println(\"A\");\n} else if (score > 75) {\n    System.out.println(\"B\");\n} else {\n    System.out.println(\"C\");\n}", targetCode: "if score > 90:\n    print('A')\nelif score > 75:\n    print('B')\nelse:\n    print('C')" },
            { concept: "Truthiness", knownCode: "if (!list.isEmpty()) { ... }", targetCode: "if items:  # Truthy check — non-empty = True\n    ...", note: "Python truthiness: empty collections, 0, None, '' are all falsy." },
            { concept: "Ternary", knownCode: "String r = (x > 0) ? \"yes\" : \"no\";", targetCode: "r = 'yes' if x > 0 else 'no'", note: "Python ternary reads like English." },
          ],
          realWorld: "Pythonic code embraces truthiness: `if items:` instead of `if len(items) > 0:`. It's more readable and idiomatic.",
          exercise: { id: "ex-java-py-cf-1", prompt: "Given `n = 7`, print 'even' or 'odd'.", starterCode: "n = 7\n# Branch here\n", solution: "n = 7\nif n % 2 == 0:\n    print('even')\nelse:\n    print('odd')", expectedOutputIncludes: "odd", xp: 25 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-java-py-cf-1", prompt: "Java's `else if` becomes Python's…", choices: ["else if", "elseif", "elif", "elsif"], correctIndex: 2, explanation: "Python uses `elif`.", xp: 10 },
        { kind: "mcq", id: "q-java-py-cf-2", prompt: "How does Python define code blocks?", choices: ["Curly braces {}", "Indentation", "begin/end keywords", "Parentheses"], correctIndex: 1, explanation: "Indentation is part of the syntax. Consistent indentation is mandatory.", xp: 10 },
        { kind: "mcq", id: "q-java-py-cf-3", prompt: "Is `if items:` valid in Python (where items is a list)?", choices: ["No — must be boolean", "Yes — checks if list is non-empty (truthiness)", "Only for strings", "Only with len()"], correctIndex: 1, explanation: "Python truthiness: empty list is falsy, non-empty is truthy.", xp: 10 },
        { kind: "debug", id: "q-java-py-cf-4", prompt: "Why does this error?", brokenCode: "if (x > 5)\n    print('big')", choices: ["Missing colon after condition", "Parentheses are wrong", "print is not a function", "x not defined"], correctIndex: 0, explanation: "Python requires `:` after `if`, `elif`, `else`, `for`, `while`, etc.", xp: 15 },
        { kind: "mcq", id: "q-java-py-cf-5", prompt: "Python's ternary syntax is…", choices: ["cond ? x : y", "x if cond else y", "cond then x else y", "select(cond, x, y)"], correctIndex: 1, explanation: "`value_if_true if condition else value_if_false`.", xp: 10 },
      ],
    },
    {
      id: "java-py-loops",
      title: "Loops & Iteration",
      tagline: "`range()`, `enumerate()`, and comprehensions.",
      icon: "🌀",
      level: "beginner",
      order: 3,
      requires: ["java-py-controlflow"],
      rewardXp: 80,
      lessons: [
        {
          id: "lesson-java-py-loops-1",
          title: "Pythonic loops",
          intro: "Python loops are much simpler. `for x in items:` iterates directly. `range(n)` generates 0..n-1. `enumerate()` gives (index, value) pairs. List comprehensions `[expr for x in iterable if cond]` replace the Stream API pattern. Python has no `do-while`.",
          comparisons: [
            { concept: "For-each", knownCode: "for (String word : words) {\n    System.out.println(word);\n}", targetCode: "for word in words:\n    print(word)" },
            { concept: "Index loop", knownCode: "for (int i = 0; i < 5; i++) {\n    System.out.println(i);\n}", targetCode: "for i in range(5):\n    print(i)" },
            { concept: "Enumerate", knownCode: "for (int i = 0; i < items.size(); i++) {\n    System.out.println(i + \" \" + items.get(i));\n}", targetCode: "for i, item in enumerate(items):\n    print(f'{i} {item}')", note: "`enumerate()` is much cleaner than manual indexing." },
            { concept: "Stream → Comprehension", knownCode: "List<Integer> evens = nums.stream()\n    .filter(x -> x % 2 == 0)\n    .collect(Collectors.toList());", targetCode: "evens = [x for x in nums if x % 2 == 0]", note: "One line replaces 3+ lines of Stream API." },
          ],
          realWorld: "List comprehensions are one of Python's killer features. They're faster, more readable, and more concise than loops.",
          exercise: { id: "ex-java-py-loops-1", prompt: "Use a list comprehension to get squares of even numbers from [1,2,3,4,5,6]. Print result.", starterCode: "nums = [1, 2, 3, 4, 5, 6]\n# squares of evens\n", solution: "nums = [1, 2, 3, 4, 5, 6]\nresult = [x**2 for x in nums if x % 2 == 0]\nprint(result)", expectedOutputIncludes: "[4, 16, 36]", xp: 30 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-java-py-loop-1", prompt: "`range(5)` produces…", choices: ["1, 2, 3, 4, 5", "0, 1, 2, 3, 4", "0, 1, 2, 3, 4, 5", "5, 4, 3, 2, 1"], correctIndex: 1, explanation: "`range(n)` starts at 0 and stops before n.", xp: 10 },
        { kind: "mcq", id: "q-java-py-loop-2", prompt: "Java's Stream API is most concisely replaced by…", choices: ["for loops", "List comprehensions", "while loops", "map() function"], correctIndex: 1, explanation: "Comprehensions replace filter/map/collect in one clean line.", xp: 10 },
        { kind: "mcq", id: "q-java-py-loop-3", prompt: "`enumerate()` returns…", choices: ["Just indices", "(index, value) tuples", "Just values", "A dict"], correctIndex: 1, explanation: "`for i, val in enumerate(items):` gives both index and value.", xp: 10 },
        { kind: "debug", id: "q-java-py-loop-4", prompt: "Why does this print nothing?", brokenCode: "for i in range(5, 0):\n    print(i)", choices: ["`range(5, 0)` is empty — need `range(5, 0, -1)` to count down", "range takes one argument only", "Missing colon", "i is not defined"], correctIndex: 0, explanation: "With default step +1, start must be < stop. Use step -1 to count down.", xp: 15 },
        { kind: "mcq", id: "q-java-py-loop-5", prompt: "Does Python have `do-while`?", choices: ["Yes", "No — use `while True: ... if cond: break`", "Only in Python 3.10+", "Same as while"], correctIndex: 1, explanation: "Python has no do-while. Simulate with `while True` and `break`.", xp: 10 },
      ],
    },
    {
      id: "java-py-functions",
      title: "Functions",
      tagline: "Free functions, *args, and first-class citizens.",
      icon: "⚔️",
      level: "beginner",
      order: 4,
      requires: ["java-py-loops"],
      rewardXp: 90,
      lessons: [
        {
          id: "lesson-java-py-fn-1",
          title: "Functions in Python",
          intro: "Python has free functions — no class wrapper needed. `def` defines a function. Default arguments work naturally. `*args` and `**kwargs` collect extra positional and keyword arguments. Functions are first-class: pass them as arguments, return them from other functions.",
          comparisons: [
            { concept: "Function", knownCode: "static int add(int a, int b) {\n    return a + b;\n}", targetCode: "def add(a, b):\n    return a + b", note: "No class needed. No types. No semicolons." },
            { concept: "Default arguments", knownCode: "// Java: overload instead\nstatic void greet() { greet(\"World\"); }\nstatic void greet(String name) { ... }", targetCode: "def greet(name=\"World\"):\n    print(f\"Hello, {name}!\")", note: "One function with defaults vs multiple overloads." },
            { concept: "Varargs", knownCode: "static void log(Object... args) { ... }", targetCode: "def log(*args, **kwargs):\n    print(*args)\n    # kwargs = dict of keyword args", note: "`**kwargs` captures keyword arguments — no Java equivalent." },
            { concept: "Lambda", knownCode: "Function<Integer, Integer> sq = x -> x * x;", targetCode: "sq = lambda x: x * x", note: "Python lambdas are single-expression. No functional interface type needed." },
          ],
          realWorld: "Python functions are objects. You can store them in lists, pass as arguments, and return them from other functions. This enables powerful patterns.",
          exercise: { id: "ex-java-py-fn-1", prompt: "Write a function `greet(name=\"World\")` that prints 'Hello, {name}!'. Call it with and without an argument.", starterCode: "# def greet(...): ...\n", solution: "def greet(name=\"World\"):\n    print(f\"Hello, {name}!\")\n\ngreet()\ngreet(\"Ada\")", expectedOutputIncludes: "Hello, World!", xp: 25 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-java-py-fn-1", prompt: "Can Python functions exist outside classes?", choices: ["No — like Java", "Yes — Python has free functions", "Only lambdas", "Only main()"], correctIndex: 1, explanation: "Python functions don't need a class. `def add(a, b):` at module level is fine.", xp: 10 },
        { kind: "mcq", id: "q-java-py-fn-2", prompt: "`**kwargs` collects…", choices: ["Positional arguments as tuple", "Keyword arguments as a dict", "All arguments", "Type annotations"], correctIndex: 1, explanation: "`**kwargs` captures named arguments: `func(a=1, b=2)` → `{'a': 1, 'b': 2}`.", xp: 10 },
        { kind: "mcq", id: "q-java-py-fn-3", prompt: "Python lambdas can contain…", choices: ["Multiple statements", "Only a single expression", "Any code", "No arguments"], correctIndex: 1, explanation: "Lambdas are limited to one expression. Use `def` for anything more complex.", xp: 10 },
        { kind: "debug", id: "q-java-py-fn-4", prompt: "Why does this produce a mutable default bug?", brokenCode: "def append_to(item, lst=[]):\n    lst.append(item)\n    return lst\n\nprint(append_to(1))  # [1]\nprint(append_to(2))  # [1, 2] — not [2]!", choices: ["Default mutable argument is shared across calls — use `lst=None`", "append is wrong", "Lists can't be defaults", "Missing return"], correctIndex: 0, explanation: "Mutable defaults are created once and reused. Use `def f(lst=None): lst = lst or []`.", xp: 15 },
        { kind: "mcq", id: "q-java-py-fn-5", prompt: "Python supports function overloading.", choices: ["Yes, like Java", "No — last definition wins", "Only with @overload", "Only with *args"], correctIndex: 1, explanation: "Python replaces earlier definitions. Use default args or `*args/**kwargs` instead.", xp: 10 },
      ],
    },
    {
      id: "java-py-collections",
      title: "Collections",
      tagline: "Lists, dicts, sets — batteries included.",
      icon: "📜",
      level: "beginner",
      order: 5,
      requires: ["java-py-functions"],
      rewardXp: 100,
      lessons: [
        {
          id: "lesson-java-py-col-1",
          title: "Built-in collections",
          intro: "Python's collections are built into the language syntax. Lists `[]`, dicts `{}`, sets `{}`, tuples `()`. No imports needed, no wrapper types. Strings are compared with `==` (not `.equals()`!). Slicing (`s[1:4]`) is a killer feature with no Java equivalent.",
          comparisons: [
            { concept: "ArrayList → list", knownCode: "List<Integer> nums = new ArrayList<>(List.of(1, 2, 3));\nnums.add(4);", targetCode: "nums = [1, 2, 3]\nnums.append(4)" },
            { concept: "HashMap → dict", knownCode: "Map<String, Integer> ages = new HashMap<>();\nages.put(\"Ada\", 36);", targetCode: "ages = {'Ada': 36}\nages['Bob'] = 25" },
            { concept: "String comparison", knownCode: "if (s1.equals(s2)) { ... }", targetCode: "if s1 == s2: ...", note: "Python `==` compares content! No `.equals()` needed." },
            { concept: "Slicing", knownCode: "// list.subList(1, 4) — verbose", targetCode: "sub = items[1:4]    # Index 1, 2, 3\nlast = items[-1]    # Last element\nrev = items[::-1]   # Reversed", note: "Slicing works on lists, strings, and tuples." },
          ],
          realWorld: "Python collections are so concise that Java developers often feel 'liberated'. Dict/list comprehensions are game-changers.",
          exercise: { id: "ex-java-py-col-1", prompt: "Create a dict `scores = {'Alice': 90, 'Bob': 85}`. Print Bob's score.", starterCode: "# Create dict and print\n", solution: "scores = {'Alice': 90, 'Bob': 85}\nprint(scores['Bob'])", expectedOutputIncludes: "85", xp: 20 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-java-py-col-1", prompt: "Python uses `==` for string comparison (not `.equals()`).", choices: ["True", "False"], correctIndex: 0, explanation: "Python `==` compares content for all types. No `.equals()` needed.", xp: 10 },
        { kind: "mcq", id: "q-java-py-col-2", prompt: "What does `items[-1]` return?", choices: ["An error", "The last element", "The first element", "A reversed list"], correctIndex: 1, explanation: "Negative indices count from the end: -1 is last, -2 is second-to-last.", xp: 10 },
        { kind: "mcq", id: "q-java-py-col-3", prompt: "Python's equivalent of `ArrayList.add()` is…", choices: ["list.add()", "list.push()", "list.append()", "list.insert()"], correctIndex: 2, explanation: "`.append()` adds to the end. `.insert(i, x)` inserts at index.", xp: 10 },
        { kind: "debug", id: "q-java-py-col-4", prompt: "Why does this fail?", brokenCode: "d = {}\nd.put('key', 'value')", choices: ["Python dicts use `d['key'] = 'value'`, not `.put()`", "put is deprecated", "Empty dict is immutable", "Missing import"], correctIndex: 0, explanation: "Python dict syntax: `d[key] = value`. `.get()` exists for safe access.", xp: 15 },
        { kind: "mcq", id: "q-java-py-col-5", prompt: "`items[::2]` returns…", choices: ["Every other element", "The last 2 elements", "A copy", "An error"], correctIndex: 0, explanation: "`[::2]` is `[start:stop:step]` — step of 2 gives every other element.", xp: 10 },
      ],
    },
    // ===================== INTERMEDIATE =====================
    {
      id: "java-py-oop",
      title: "OOP & Classes",
      tagline: "Duck typing, dataclasses, and dunder methods.",
      icon: "👑",
      level: "intermediate",
      order: 1,
      requires: [],
      rewardXp: 120,
      lessons: [
        {
          id: "lesson-java-py-oop-1",
          title: "Python classes",
          intro: "Python classes use `def __init__(self)` instead of constructors. Every method takes `self` explicitly. No access modifiers — `_private` is convention, `__mangled` triggers name-mangling. Python supports multiple inheritance. `@dataclass` auto-generates boilerplate like Java records.",
          comparisons: [
            { concept: "Class", knownCode: "public class Dog {\n    private String name;\n    public Dog(String name) { this.name = name; }\n    public String bark() { return name + \" barks!\"; }\n}", targetCode: "class Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        return f'{self.name} barks!'" },
            { concept: "Interface → Duck typing", knownCode: "interface Speakable {\n    String speak();\n}\nclass Dog implements Speakable { ... }", targetCode: "class Dog:\n    def speak(self): return 'woof'\n# No interface needed — just implement the method", note: "Python uses duck typing: 'If it quacks like a duck...'." },
            { concept: "Record → dataclass", knownCode: "record Point(int x, int y) { }", targetCode: "from dataclasses import dataclass\n\n@dataclass\nclass Point:\n    x: int\n    y: int", note: "Auto-generates __init__, __repr__, __eq__, etc." },
          ],
          realWorld: "Python's duck typing is liberating but can lead to runtime errors. Type hints + mypy add Java-like safety when needed.",
          exercise: { id: "ex-java-py-oop-1", prompt: "Create a `@dataclass` for `Point` with x and y fields. Print Point(3, 4).", starterCode: "from dataclasses import dataclass\n# @dataclass class Point: ...\n", solution: "from dataclasses import dataclass\n\n@dataclass\nclass Point:\n    x: int\n    y: int\n\nprint(Point(3, 4))", expectedOutputIncludes: "Point(x=3, y=4)", xp: 30 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-java-py-oop-1", prompt: "Java's constructor is Python's…", choices: ["__init__", "constructor", "__new__", "init"], correctIndex: 0, explanation: "`__init__` initializes the instance.", xp: 10 },
        { kind: "mcq", id: "q-java-py-oop-2", prompt: "Why does Python use `self` in methods?", choices: ["Convention only", "Explicit instance reference (like Java's `this`)", "It creates a copy", "It's the class reference"], correctIndex: 1, explanation: "`self` is the instance — like `this` but explicit in the parameter list.", xp: 10 },
        { kind: "mcq", id: "q-java-py-oop-3", prompt: "Python has no `interface` keyword because…", choices: ["Interfaces don't exist", "Duck typing: just implement the methods", "It uses `abstract` instead", "Protocol replaced it"], correctIndex: 1, explanation: "If an object has the right methods, it works — no explicit interface needed.", xp: 10 },
        { kind: "debug", id: "q-java-py-oop-4", prompt: "Why does this print a memory address?", brokenCode: "class Dog:\n    def __init__(self, name):\n        self.name = name\nprint(Dog('Rex'))", choices: ["No __str__ method — Python uses default repr", "name is private", "Missing new", "print doesn't work"], correctIndex: 0, explanation: "Add `__str__` to control what `print()` shows.", xp: 15 },
        { kind: "mcq", id: "q-java-py-oop-5", prompt: "`@dataclass` auto-generates…", choices: ["Only __init__", "__init__, __repr__, __eq__ and more", "Only getters", "Nothing"], correctIndex: 1, explanation: "Dataclasses generate boilerplate from field annotations.", xp: 10 },
      ],
    },
    {
      id: "java-py-errors",
      title: "Error Handling",
      tagline: "No checked exceptions — EAFP style.",
      icon: "🔥",
      level: "intermediate",
      order: 2,
      requires: ["java-py-oop"],
      rewardXp: 110,
      lessons: [
        {
          id: "lesson-java-py-err-1",
          title: "Exceptions in Python",
          intro: "Python uses `try/except/else/finally`. No checked exceptions — you never need `throws`. Python embraces EAFP: try the operation, handle the exception if it fails. `with` (context managers) replaces `try-with-resources`.",
          comparisons: [
            { concept: "try/catch → try/except", knownCode: "try {\n    int n = Integer.parseInt(s);\n} catch (NumberFormatException e) {\n    System.err.println(e.getMessage());\n}", targetCode: "try:\n    n = int(s)\nexcept ValueError as e:\n    print(e)" },
            { concept: "throw → raise", knownCode: "throw new IllegalArgumentException(\"bad\");", targetCode: "raise ValueError('bad')", note: "No `new` — just call the exception class." },
            { concept: "try-with-resources → with", knownCode: "try (var br = new BufferedReader(new FileReader(\"f\"))) {\n    ...\n}", targetCode: "with open('f') as file:\n    data = file.read()" },
          ],
          realWorld: "EAFP pattern: `try: d[key]` is faster and more Pythonic than `if key in d: d[key]`.",
          exercise: { id: "ex-java-py-err-1", prompt: "Write a try/except that converts 'abc' to int and handles the error.", starterCode: "# Try to convert 'abc'\n", solution: "try:\n    n = int('abc')\nexcept ValueError:\n    print('Invalid number')", expectedOutputIncludes: "Invalid number", xp: 25 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-java-py-err-1", prompt: "Java's `catch` is Python's…", choices: ["catch", "except", "handle", "rescue"], correctIndex: 1, explanation: "Python uses `except ExceptionType as e:`.", xp: 10 },
        { kind: "mcq", id: "q-java-py-err-2", prompt: "Does Python have checked exceptions?", choices: ["Yes", "No — all exceptions are unchecked", "Only IOError", "Only in strict mode"], correctIndex: 1, explanation: "No checked exceptions. No `throws` declarations needed.", xp: 10 },
        { kind: "mcq", id: "q-java-py-err-3", prompt: "try-with-resources → Python's…", choices: ["try/finally", "with statement", "using block", "context block"], correctIndex: 1, explanation: "`with open('f') as file:` auto-closes at block exit.", xp: 10 },
        { kind: "debug", id: "q-java-py-err-4", prompt: "What's wrong with this handler?", brokenCode: "try:\n    risky()\nexcept:\n    pass", choices: ["Bare `except` catches everything including KeyboardInterrupt — use `except Exception`", "pass is invalid", "Missing finally", "risky must return"], correctIndex: 0, explanation: "Bare `except:` catches even SystemExit. Use `except Exception:` for normal errors.", xp: 15 },
        { kind: "mcq", id: "q-java-py-err-5", prompt: "EAFP means…", choices: ["Errors Are Fully Preventable", "Easier to Ask Forgiveness than Permission", "Exceptions Are For Programming", "Error And Fault Protocol"], correctIndex: 1, explanation: "Try the operation, catch the exception if it fails.", xp: 10 },
      ],
    },
    {
      id: "java-py-modules",
      title: "Modules & pip",
      tagline: "import, pip install, and virtual environments.",
      icon: "📦",
      level: "intermediate",
      order: 3,
      requires: ["java-py-errors"],
      rewardXp: 100,
      lessons: [
        {
          id: "lesson-java-py-mod-1",
          title: "Python modules and pip",
          intro: "Every `.py` file is a module. `import module` or `from module import func`. pip installs from PyPI (like Maven Central). Virtual environments (`venv`) isolate dependencies per project (like Maven per-project deps). No build file needed for simple projects.",
          comparisons: [
            { concept: "Import", knownCode: "import java.util.List;\nimport com.myapp.Utils;", targetCode: "import os\nfrom collections import defaultdict", note: "No fully-qualified paths needed. Just module names." },
            { concept: "Package manager", knownCode: "// Maven: pom.xml\n// Gradle: build.gradle", targetCode: "# pip install requests\n# requirements.txt lists dependencies", note: "pip is simpler than Maven/Gradle. `requirements.txt` is the dependency file." },
            { concept: "Project structure", knownCode: "src/main/java/com/app/Main.java", targetCode: "myproject/\n    mypackage/\n        __init__.py\n        utils.py\n    main.py", note: "Flatter structure. `__init__.py` makes a directory a package." },
          ],
          realWorld: "Modern Python uses `pyproject.toml` for project config. Poetry and uv are popular alternatives to pip.",
          exercise: { id: "ex-java-py-mod-1", prompt: "Import `math` and print `math.sqrt(144)`.", starterCode: "# Import and compute\n", solution: "import math\nprint(math.sqrt(144))", expectedOutputIncludes: "12", xp: 15 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-java-py-mod-1", prompt: "Maven/Gradle → Python's…", choices: ["pip", "javac", "python3", "mypy"], correctIndex: 0, explanation: "pip installs packages from PyPI.", xp: 10 },
        { kind: "mcq", id: "q-java-py-mod-2", prompt: "What makes a directory a Python package?", choices: ["pom.xml", "__init__.py", "setup.py", "package.json"], correctIndex: 1, explanation: "`__init__.py` (even empty) marks a directory as an importable package.", xp: 10 },
        { kind: "mcq", id: "q-java-py-mod-3", prompt: "Virtual environments in Python are like…", choices: ["Maven per-project deps", "Docker containers", "JVM instances", "Class loaders"], correctIndex: 0, explanation: "venvs isolate dependencies per project, like Maven scopes deps per project.", xp: 10 },
        { kind: "debug", id: "q-java-py-mod-4", prompt: "Why does this fail?", brokenCode: "from math import squareroot", choices: ["The function is called `sqrt`, not `squareroot`", "math is not installed", "from doesn't work", "Missing parentheses"], correctIndex: 0, explanation: "Python names are case-sensitive. The correct name is `sqrt`.", xp: 15 },
      ],
    },
    {
      id: "java-py-functional",
      title: "Functional Patterns",
      tagline: "Comprehensions, generators, and decorators.",
      icon: "⚡",
      level: "intermediate",
      order: 4,
      requires: ["java-py-modules"],
      rewardXp: 130,
      lessons: [
        {
          id: "lesson-java-py-func-1",
          title: "Comprehensions and generators",
          intro: "Python's comprehensions replace Stream API chains. Generator expressions `(expr for x in ...)` are lazy like Streams but with simpler syntax. Generators (`yield`) create iterators effortlessly. `itertools` provides additional functional tools.",
          comparisons: [
            { concept: "Stream.filter.map.collect → Comprehension", knownCode: "nums.stream()\n    .filter(x -> x % 2 == 0)\n    .map(x -> x * x)\n    .collect(Collectors.toList())", targetCode: "[x * x for x in nums if x % 2 == 0]", note: "One line vs four. And it's faster." },
            { concept: "Stream (lazy) → Generator expression", knownCode: "nums.stream().filter(...).map(...)", targetCode: "gen = (x * x for x in nums if x % 2 == 0)\n# Lazy — processes one at a time", note: "Use `()` instead of `[]` for lazy evaluation." },
            { concept: "Custom Stream → Generator function", knownCode: "// Implement Iterable<T> + Iterator<T>", targetCode: "def fibonacci():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b", note: "`yield` makes any function a lazy generator." },
          ],
          realWorld: "Comprehensions and generators are Python's most powerful features. Master them for idiomatic Python code.",
          exercise: { id: "ex-java-py-func-1", prompt: "Write a generator `evens(n)` that yields even numbers from 2 to n. Print evens(10).", starterCode: "def evens(n):\n    pass\n", solution: "def evens(n):\n    for i in range(2, n + 1, 2):\n        yield i\n\nfor x in evens(10):\n    print(x)", expectedOutputIncludes: "2\n4\n6\n8\n10", xp: 40 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-java-py-func-1", prompt: "Java Streams are replaced by Python…", choices: ["for loops only", "List comprehensions and generator expressions", "map() function only", "itertools only"], correctIndex: 1, explanation: "Comprehensions do the same thing in less code.", xp: 10 },
        { kind: "mcq", id: "q-java-py-func-2", prompt: "`yield` turns a function into a…", choices: ["Thread", "Generator (lazy iterator)", "Decorator", "Closure"], correctIndex: 1, explanation: "Generator functions produce values on-demand. No full list in memory.", xp: 10 },
        { kind: "mcq", id: "q-java-py-func-3", prompt: "Difference between `[]` and `()` comprehensions:", choices: ["No difference", "[] creates list, () creates lazy generator", "[] is tuple, () is list", "() is invalid"], correctIndex: 1, explanation: "Square brackets build a list in memory. Parens create a lazy generator.", xp: 10 },
        { kind: "debug", id: "q-java-py-func-4", prompt: "Why is the generator empty on second loop?", brokenCode: "gen = (x for x in [1,2,3])\nfor x in gen: print(x)\nfor x in gen: print(x)  # Nothing!", choices: ["Generators are single-use — exhausted after first iteration", "gen was deleted", "Second loop uses different gen", "print consumes it"], correctIndex: 0, explanation: "Generators are iterators — once consumed, they're done. Use a list if you need to iterate twice.", xp: 15 },
        { kind: "mcq", id: "q-java-py-func-5", prompt: "Python's `@decorator` has no Java equivalent except…", choices: ["Annotations (@Override)", "Aspect-oriented programming / proxies", "Generics", "Enums"], correctIndex: 1, explanation: "AOP frameworks (Spring) and dynamic proxies are the closest. Python decorators are simpler.", xp: 10 },
      ],
    },
    // ===================== ADVANCED =====================
    {
      id: "java-py-memory",
      title: "Memory & Performance",
      tagline: "GC differences, profiling, and optimization.",
      icon: "🧠",
      level: "advanced",
      order: 1,
      requires: [],
      rewardXp: 150,
      lessons: [
        {
          id: "lesson-java-py-mem-1",
          title: "CPython vs JVM",
          intro: "CPython uses reference counting + cyclic GC. The JVM uses generational mark-and-sweep with JIT compilation. CPython is 10-50x slower than JVM for compute-heavy tasks. For performance, Python relies on C extensions (NumPy), Cython, or PyPy (JIT-compiled Python).",
          comparisons: [
            { concept: "GC model", knownCode: "// JVM: generational GC, JIT compilation", targetCode: "# CPython: reference counting + cyclic GC\nimport gc\ngc.collect()  # Force GC cycle" },
            { concept: "Performance", knownCode: "// JVM: JIT compiles to native code\n// Often 10-50x faster than CPython", targetCode: "# Use NumPy for numeric performance\nimport numpy as np\narr = np.array([1, 2, 3])\narr * 2  # Runs in C, not Python" },
          ],
          realWorld: "Python's strength is developer productivity, not raw performance. Use C extensions and libraries for the hot path.",
          exercise: { id: "ex-java-py-mem-1", prompt: "Use `sys.getsizeof()` to print the memory size of a list with 1000 elements.", starterCode: "import sys\n# Check size\n", solution: "import sys\nbig_list = list(range(1000))\nprint(sys.getsizeof(big_list))", expectedOutputIncludes: "", xp: 30 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-java-py-mem-1", prompt: "CPython's primary GC mechanism is…", choices: ["Mark-and-sweep", "Reference counting", "Generational GC", "Manual free"], correctIndex: 1, explanation: "Reference counting is primary. Cyclic GC handles reference cycles.", xp: 10 },
        { kind: "mcq", id: "q-java-py-mem-2", prompt: "For numeric performance, Python uses…", choices: ["JIT compilation", "C extensions like NumPy", "Faster loops", "Assembly"], correctIndex: 1, explanation: "NumPy operations run in optimized C code, bypassing Python's overhead.", xp: 10 },
        { kind: "mcq", id: "q-java-py-mem-3", prompt: "PyPy is…", choices: ["A package manager", "An alternative Python implementation with JIT", "A profiler", "A C compiler"], correctIndex: 1, explanation: "PyPy JIT-compiles Python code. Often 5-20x faster than CPython.", xp: 10 },
        { kind: "debug", id: "q-java-py-mem-4", prompt: "Why is this Python code slow?", brokenCode: "result = []\nfor i in range(1000000):\n    result.append(i * 2)", choices: ["Use list comprehension `[i*2 for i in range(...)]` — executed in C, not Python bytecode", "append is deprecated", "range is slow", "Lists have a size limit"], correctIndex: 0, explanation: "Comprehensions run in optimized C internally. Explicit loops run in slow Python bytecode.", xp: 15 },
        { kind: "mcq", id: "q-java-py-mem-5", prompt: "Python's `is` vs `==`:", choices: ["Same thing", "`is` checks identity (same object), `==` checks equality (same value)", "`is` is for types only", "`==` checks identity"], correctIndex: 1, explanation: "Use `is` only for `None` checks. Use `==` for value comparison.", xp: 10 },
      ],
    },
    {
      id: "java-py-concurrency",
      title: "Concurrency",
      tagline: "The GIL, asyncio, and multiprocessing.",
      icon: "🔄",
      level: "advanced",
      order: 2,
      requires: ["java-py-memory"],
      rewardXp: 170,
      lessons: [
        {
          id: "lesson-java-py-conc-1",
          title: "Python's concurrency model",
          intro: "Python has a GIL (Global Interpreter Lock) that prevents true parallel threads. Use `threading` for I/O-bound tasks only. For CPU-bound parallelism, use `multiprocessing`. `asyncio` provides cooperative concurrency with `async/await` for high-concurrency I/O (like Java's virtual threads).",
          comparisons: [
            { concept: "Threads", knownCode: "Thread t = new Thread(() -> task());\nt.start(); t.join();", targetCode: "import threading\nt = threading.Thread(target=task)\nt.start()\nt.join()", note: "Python threads can't run CPU-bound code in parallel due to GIL." },
            { concept: "Virtual threads → asyncio", knownCode: "Executors.newVirtualThreadPerTaskExecutor()", targetCode: "import asyncio\n\nasync def main():\n    await asyncio.gather(task1(), task2())\n\nasyncio.run(main())" },
            { concept: "True parallelism", knownCode: "// Java: just use threads", targetCode: "from multiprocessing import Pool\nwith Pool(4) as p:\n    results = p.map(cpu_func, data)", note: "Each process has its own GIL — true parallelism." },
          ],
          realWorld: "Use asyncio for web servers (FastAPI). Use multiprocessing for data crunching. The GIL may be removed in future Python (PEP 703).",
          exercise: { id: "ex-java-py-conc-1", prompt: "Write an async function that awaits `asyncio.sleep(0)` and returns 'done'. Run it and print the result.", starterCode: "import asyncio\n# async def ...\n", solution: "import asyncio\n\nasync def quick():\n    await asyncio.sleep(0)\n    return 'done'\n\nprint(asyncio.run(quick()))", expectedOutputIncludes: "done", xp: 40 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-java-py-conc-1", prompt: "Python's GIL means…", choices: ["All threads run in parallel", "Only one thread executes Python bytecode at a time", "Threads don't exist", "GIL is a lock library"], correctIndex: 1, explanation: "The GIL prevents true parallel Python thread execution.", xp: 10 },
        { kind: "mcq", id: "q-java-py-conc-2", prompt: "For CPU-bound parallel work in Python:", choices: ["threading", "asyncio", "multiprocessing", "GIL"], correctIndex: 2, explanation: "Separate processes bypass the GIL for true parallelism.", xp: 10 },
        { kind: "mcq", id: "q-java-py-conc-3", prompt: "asyncio is best for…", choices: ["CPU-bound tasks", "I/O-bound concurrent tasks (network, files)", "Parallel computation", "GPU computing"], correctIndex: 1, explanation: "asyncio excels at high-concurrency I/O (like Java virtual threads).", xp: 10 },
        { kind: "debug", id: "q-java-py-conc-4", prompt: "Why does calling `main()` do nothing?", brokenCode: "async def main():\n    await asyncio.sleep(1)\n    print('done')\n\nmain()  # Nothing!", choices: ["Must use `asyncio.run(main())` — calling returns a coroutine object, not the result", "Missing import", "main can't be async", "print is wrong"], correctIndex: 0, explanation: "Async functions return coroutine objects. `asyncio.run()` actually executes them.", xp: 15 },
        { kind: "mcq", id: "q-java-py-conc-5", prompt: "Java threads vs Python threads:", choices: ["Both truly parallel", "Java: truly parallel. Python: limited by GIL", "Both limited by GIL", "Neither supports threads"], correctIndex: 1, explanation: "Java threads have real parallelism. Python threads share one GIL.", xp: 10 },
      ],
    },
    {
      id: "java-py-advanced",
      title: "Advanced Patterns",
      tagline: "Decorators, metaclasses, and dynamic magic.",
      icon: "✨",
      level: "advanced",
      order: 3,
      requires: ["java-py-concurrency"],
      rewardXp: 200,
      lessons: [
        {
          id: "lesson-java-py-adv-1",
          title: "Decorators and metaprogramming",
          intro: "Python decorators modify functions/classes at definition time — much simpler than Java's AOP or dynamic proxies. Metaclasses control class creation. `__getattr__` enables attribute interception (like Java's `InvocationHandler`). Python's dynamism enables patterns impossible in Java.",
          comparisons: [
            { concept: "Annotation → Decorator", knownCode: "@Override\npublic String toString() { ... }", targetCode: "@functools.lru_cache\ndef fibonacci(n):\n    if n < 2: return n\n    return fibonacci(n-1) + fibonacci(n-2)", note: "Java annotations are metadata. Python decorators modify behavior." },
            { concept: "@property (getter/setter)", knownCode: "private int x;\npublic int getX() { return x; }\npublic void setX(int x) { this.x = x; }", targetCode: "class Obj:\n    @property\n    def x(self):\n        return self._x\n    @x.setter\n    def x(self, value):\n        self._x = value", note: "Access `obj.x` like a field, but it runs a method." },
          ],
          realWorld: "Decorators power Flask routes, Django views, pytest fixtures, and FastAPI endpoints. They're one of Python's most important patterns.",
          exercise: { id: "ex-java-py-adv-1", prompt: "Write a decorator `uppercase` that converts a function's string return to uppercase. Apply to a function returning 'hello'. Print result.", starterCode: "def uppercase(func):\n    pass\n\n# @uppercase\n# def greet(): ...\n", solution: "def uppercase(func):\n    def wrapper(*args, **kwargs):\n        return func(*args, **kwargs).upper()\n    return wrapper\n\n@uppercase\ndef greet():\n    return 'hello'\n\nprint(greet())", expectedOutputIncludes: "HELLO", xp: 50 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-java-py-adv-1", prompt: "Java annotations vs Python decorators:", choices: ["Same thing", "Annotations are metadata, decorators modify behavior", "Decorators are metadata only", "Neither affects code"], correctIndex: 1, explanation: "Decorators wrap and modify functions. Annotations are just metadata (unless processed by frameworks).", xp: 10 },
        { kind: "mcq", id: "q-java-py-adv-2", prompt: "`@property` lets you…", choices: ["Make a field immutable", "Access a method like a field attribute", "Declare a static variable", "Create a constructor"], correctIndex: 1, explanation: "`obj.x` looks like field access but runs a method.", xp: 10 },
        { kind: "mcq", id: "q-java-py-adv-3", prompt: "`@functools.wraps(func)` on a decorator wrapper…", choices: ["Makes it faster", "Preserves the original function's name and docstring", "Makes it thread-safe", "Adds type checking"], correctIndex: 1, explanation: "Without `@wraps`, the wrapper replaces the original function's metadata.", xp: 10 },
        { kind: "debug", id: "q-java-py-adv-4", prompt: "Why does `greet.__name__` return 'wrapper'?", brokenCode: "def dec(fn):\n    def wrapper(): return fn()\n    return wrapper\n\n@dec\ndef greet(): pass\nprint(greet.__name__)  # 'wrapper'!", choices: ["Missing @functools.wraps(fn) on wrapper", "Decorators always rename", "__name__ is wrong", "greet is not defined"], correctIndex: 0, explanation: "`@functools.wraps(fn)` copies __name__, __doc__ and other metadata to wrapper.", xp: 15 },
        { kind: "mcq", id: "q-java-py-adv-5", prompt: "Python metaclasses are like Java's…", choices: ["Class loaders + reflection (partially)", "Annotations", "Interfaces", "Generics"], correctIndex: 0, explanation: "Metaclasses control class creation — like customizing the class loader.", xp: 10 },
      ],
    },
  ],
};
