import type { Course } from "@/lib/types";

export const pythonToCpp: Course = {
  id: "python-to-cpp",
  knownLang: "python",
  targetLang: "cpp",
  title: "Python → C++",
  modules: [
    // ===================== BEGINNER =====================
    {
      id: "py-cpp-variables",
      title: "Variables & Types",
      tagline: "From dynamic typing to static declarations and semicolons.",
      icon: "🏰",
      level: "beginner",
      order: 1,
      requires: [],
      rewardXp: 60,
      lessons: [
        {
          id: "lesson-py-cpp-vars-1",
          title: "Static types and declarations",
          intro: "C++ requires you to declare the type of every variable before use: `int x = 5;`. Types are checked at compile time. Semicolons end every statement. C++ has both stack and heap allocation — a concept that doesn't exist in Python. `auto` provides type inference similar to Python's implicit typing.",
          comparisons: [
            { concept: "Variable declaration", knownCode: "count = 0\nname = \"Ada\"", targetCode: "int count = 0;\nstd::string name = \"Ada\";", note: "Type first, then name. Semicolons mandatory. `std::string` for strings." },
            { concept: "Constants", knownCode: "PI = 3.14159  # Convention only", targetCode: "const double PI = 3.14159;", note: "`const` is enforced by the compiler." },
            { concept: "Type inference", knownCode: "x = 42", targetCode: "auto x = 42;  // Compiler infers int", note: "`auto` deduces the type from the initializer." },
            { concept: "Multiple types", knownCode: "x = 42\nx = \"hello\"  # Fine in Python!", targetCode: "int x = 42;\n// x = \"hello\";  // COMPILE ERROR!", note: "Variables can't change type in C++." },
          ],
          realWorld: "C++ static typing eliminates entire classes of runtime bugs. The compiler is your first line of defense.",
          exercise: { id: "ex-py-cpp-vars-1", prompt: "Declare an int variable `age` set to 25 and a string `name` set to \"Ada\". Print both using cout.", starterCode: "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    // Declare and print\n    return 0;\n}\n", solution: "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    int age = 25;\n    string name = \"Ada\";\n    cout << name << \" is \" << age << endl;\n    return 0;\n}", expectedOutputIncludes: "Ada", xp: 20 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-cpp-var-1", prompt: "How do you declare a string in C++?", choices: ["str name = \"Ada\"", "string name = \"Ada\"  (or std::string)", "String name = \"Ada\"", "var name = \"Ada\""], correctIndex: 1, explanation: "`std::string` (with `#include <string>`) or `string` with `using namespace std`.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-var-2", prompt: "What does `auto` do in C++?", choices: ["Creates a dynamic variable", "Deduces type from the initializer", "Makes a variable global", "Allocates on heap"], correctIndex: 1, explanation: "`auto` lets the compiler figure out the type. Like Python's implicit typing.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-var-3", prompt: "Can a variable change type in C++?", choices: ["Yes, like Python", "No — type is fixed at declaration", "Only with auto", "Only primitives"], correctIndex: 1, explanation: "C++ is statically typed. Once declared, a variable's type never changes.", xp: 10 },
        { kind: "debug", id: "q-py-cpp-var-4", prompt: "Why doesn't this compile?", brokenCode: "int x = 42\ncout << x;", choices: ["Missing semicolons", "cout is not defined", "x needs auto", "42 is not an int"], correctIndex: 0, explanation: "Every C++ statement needs a semicolon: `int x = 42;`", xp: 15 },
        { kind: "mcq", id: "q-py-cpp-var-5", prompt: "C++ output uses…", choices: ["print()", "console.log()", "std::cout <<", "printf() only"], correctIndex: 2, explanation: "`std::cout << value` is C++ stream output. `printf` also works (C-style).", xp: 10 },
      ],
    },
    {
      id: "py-cpp-controlflow",
      title: "Control Flow",
      tagline: "Braces and parens instead of colons and indentation.",
      icon: "🛡️",
      level: "beginner",
      order: 2,
      requires: ["py-cpp-variables"],
      rewardXp: 70,
      lessons: [
        {
          id: "lesson-py-cpp-cf-1",
          title: "Conditionals",
          intro: "C++ uses curly braces `{}` for blocks and parentheses `()` around conditions. `elif` becomes `else if`. Logical operators use symbols: `&&` (and), `||` (or), `!` (not). C++ has implicit bool conversion: 0 is false, non-zero is true. It also has `switch/case`.",
          comparisons: [
            { concept: "if/elif/else", knownCode: "if score > 90:\n    print('A')\nelif score > 75:\n    print('B')\nelse:\n    print('C')", targetCode: "if (score > 90) {\n    cout << \"A\";\n} else if (score > 75) {\n    cout << \"B\";\n} else {\n    cout << \"C\";\n}" },
            { concept: "Logical operators", knownCode: "if x > 0 and y > 0 or not done:", targetCode: "if (x > 0 && y > 0 || !done) { ... }", note: "`and` → `&&`, `or` → `||`, `not` → `!`." },
            { concept: "Ternary", knownCode: "result = x if x > 0 else -x", targetCode: "int result = (x > 0) ? x : -x;", note: "C-style ternary: `condition ? valueTrue : valueFalse`." },
            { concept: "Switch", knownCode: "# Python: match/case (3.10+)", targetCode: "switch (day) {\n    case 1: cout << \"Mon\"; break;\n    case 2: cout << \"Tue\"; break;\n    default: cout << \"Other\";\n}", note: "Don't forget `break` — C++ switch falls through by default!" },
          ],
          realWorld: "C++17 added `if constexpr` for compile-time conditionals and `if` with initializers: `if (auto x = get(); x > 0) { ... }`.",
          exercise: { id: "ex-py-cpp-cf-1", prompt: "Given `int n = 7`, print 'even' if divisible by 2, otherwise 'odd'.", starterCode: "int n = 7;\n// Branch here\n", solution: "int n = 7;\nif (n % 2 == 0) {\n    cout << \"even\" << endl;\n} else {\n    cout << \"odd\" << endl;\n}", expectedOutputIncludes: "odd", xp: 25 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-cpp-cf-1", prompt: "Python's `and` becomes C++…", choices: ["and", "&&", "&", "AND"], correctIndex: 1, explanation: "`&&` is logical AND. (`and` is actually valid in C++ too, but rarely used.)", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-cf-2", prompt: "Python's `elif` becomes C++…", choices: ["elif", "elseif", "else if", "elsif"], correctIndex: 2, explanation: "Two separate words: `else if`.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-cf-3", prompt: "Does C++ have implicit bool conversion from int?", choices: ["No — must be explicit", "Yes — 0 is false, non-zero is true", "Only with auto", "Only for unsigned"], correctIndex: 1, explanation: "C++ implicitly converts int to bool: 0 = false, anything else = true.", xp: 10 },
        { kind: "debug", id: "q-py-cpp-cf-4", prompt: "What's wrong with this switch?", brokenCode: "switch (x) {\n    case 1: cout << \"one\";\n    case 2: cout << \"two\";\n}", choices: ["Missing `break` — causes fall-through", "switch doesn't work with int", "Missing default", "Missing parentheses"], correctIndex: 0, explanation: "Without `break`, execution falls through to the next case. This is a common C++ bug.", xp: 15 },
        { kind: "mcq", id: "q-py-cpp-cf-5", prompt: "C++ ternary syntax is…", choices: ["x if cond else y", "cond ? x : y", "cond then x else y", "x unless cond"], correctIndex: 1, explanation: "`condition ? valueIfTrue : valueIfFalse`.", xp: 10 },
      ],
    },
    {
      id: "py-cpp-loops",
      title: "Loops & Iteration",
      tagline: "C-style for loops and range-based for.",
      icon: "🌀",
      level: "beginner",
      order: 3,
      requires: ["py-cpp-controlflow"],
      rewardXp: 80,
      lessons: [
        {
          id: "lesson-py-cpp-loops-1",
          title: "For loops in C++",
          intro: "C++ has C-style for loops (`for (int i = 0; i < n; i++)`) and range-based for (`for (auto& x : container)`). There's no `range()` — use the classic three-part for loop. Python's `enumerate()` has no direct equivalent. `while` and `do-while` work as expected.",
          comparisons: [
            { concept: "Range loop", knownCode: "for i in range(5):\n    print(i)", targetCode: "for (int i = 0; i < 5; i++) {\n    cout << i << endl;\n}" },
            { concept: "For-each", knownCode: "for word in words:\n    print(word)", targetCode: "for (const auto& word : words) {\n    cout << word << endl;\n}", note: "`const auto&` avoids copies. Use `auto&` if you need to modify." },
            { concept: "Enumerate", knownCode: "for i, item in enumerate(items):\n    print(i, item)", targetCode: "for (int i = 0; i < items.size(); i++) {\n    cout << i << \" \" << items[i] << endl;\n}", note: "No `enumerate`. Use index loop or create a helper." },
            { concept: "While", knownCode: "while n > 0:\n    n -= 1", targetCode: "while (n > 0) {\n    n--;\n}", note: "C++ has `n++` and `n--` operators." },
          ],
          realWorld: "Range-based for (`for (auto& x : v)`) is preferred for readability. Index loops only when you need the index.",
          exercise: { id: "ex-py-cpp-loops-1", prompt: "Print numbers 1 through 5 using a for loop.", starterCode: "// Print 1 to 5\n", solution: "for (int i = 1; i <= 5; i++) {\n    cout << i << endl;\n}", expectedOutputIncludes: "1\n2\n3\n4\n5", xp: 20 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-cpp-loop-1", prompt: "Python's `for x in items:` becomes C++…", choices: ["for (x in items)", "for (auto& x : items)", "for x of items", "foreach (x, items)"], correctIndex: 1, explanation: "`for (auto& x : items)` is range-based for. `&` avoids copies.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-loop-2", prompt: "C++ has `++i` and `i++`. The difference is…", choices: ["No difference", "++i increments before use, i++ after use", "++i is faster", "i++ is deprecated"], correctIndex: 1, explanation: "Pre-increment returns the new value. Post-increment returns the old value.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-loop-3", prompt: "C++ has a built-in `range()` function.", choices: ["True", "False — use C-style for loop or C++20 ranges"], correctIndex: 1, explanation: "Use `for (int i = 0; i < n; i++)`. C++20 ranges library adds some alternatives.", xp: 10 },
        { kind: "debug", id: "q-py-cpp-loop-4", prompt: "Why does this loop never end?", brokenCode: "unsigned int i = 5;\nwhile (i >= 0) {\n    cout << i;\n    i--;\n}", choices: ["Unsigned int wraps to max value at -1 — never < 0", "i-- is wrong syntax", "while needs parentheses", "cout blocks"], correctIndex: 0, explanation: "Unsigned integers can't be negative. When `i` wraps from 0 to 4294967295, the condition is still true.", xp: 15 },
        { kind: "mcq", id: "q-py-cpp-loop-5", prompt: "What does `const auto&` do in a range-based for?", choices: ["Makes a copy", "Creates a const reference (no copy, no modification)", "Makes the loop parallel", "Auto-allocates memory"], correctIndex: 1, explanation: "`const auto&` reads elements by reference without copying or allowing modification.", xp: 10 },
      ],
    },
    {
      id: "py-cpp-functions",
      title: "Functions",
      tagline: "Return types, overloading, and templates.",
      icon: "⚔️",
      level: "beginner",
      order: 4,
      requires: ["py-cpp-loops"],
      rewardXp: 90,
      lessons: [
        {
          id: "lesson-py-cpp-fn-1",
          title: "Functions and parameters",
          intro: "C++ functions declare return type and parameter types. Default arguments work like Python. C++ supports function overloading (same name, different params). Lambdas use `[capture](params) { body }` syntax. Pass by reference with `&` to avoid copies — a concept Python doesn't expose.",
          comparisons: [
            { concept: "Function definition", knownCode: "def add(a, b):\n    return a + b", targetCode: "int add(int a, int b) {\n    return a + b;\n}" },
            { concept: "Default arguments", knownCode: "def greet(name=\"World\"):\n    print(f\"Hello, {name}!\")", targetCode: "void greet(string name = \"World\") {\n    cout << \"Hello, \" << name << \"!\" << endl;\n}" },
            { concept: "Lambda", knownCode: "double = lambda x: x * 2", targetCode: "auto doubleIt = [](int x) { return x * 2; };", note: "`[]` is the capture list. `[=]` captures by value, `[&]` by reference." },
            { concept: "Pass by reference", knownCode: "# Python: all objects passed by reference\ndef modify(lst):\n    lst.append(4)", targetCode: "void modify(vector<int>& v) {\n    v.push_back(4);\n}", note: "`&` means pass by reference. Without it, a copy is made." },
          ],
          realWorld: "Always prefer pass by `const reference` (`const T&`) for large objects. Use `T&&` (move semantics) for transfers of ownership.",
          exercise: { id: "ex-py-cpp-fn-1", prompt: "Write a function `square(int n)` that returns n squared. Print `square(7)`.", starterCode: "// int square(int n) { ... }\n", solution: "int square(int n) {\n    return n * n;\n}\n// cout << square(7);", expectedOutputIncludes: "49", xp: 25 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-cpp-fn-1", prompt: "C++ lambda capture list `[&]` means…", choices: ["Capture nothing", "Capture all by reference", "Capture all by value", "Create a pointer"], correctIndex: 1, explanation: "`[&]` captures all outer variables by reference. `[=]` by value.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-fn-2", prompt: "What does `const int&` parameter do?", choices: ["Creates a copy", "Passes by const reference (no copy, no modification)", "Makes a pointer", "Allocates on heap"], correctIndex: 1, explanation: "Const reference: efficient (no copy) and safe (can't modify).", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-fn-3", prompt: "C++ supports function overloading. Python…", choices: ["Also supports it natively", "Doesn't — last definition wins", "Uses @overload decorator", "Uses *args instead"], correctIndex: 1, explanation: "Python replaces earlier definitions. Use `@typing.overload` for type hints only.", xp: 10 },
        { kind: "debug", id: "q-py-cpp-fn-4", prompt: "Why doesn't this modify the original vector?", brokenCode: "void addOne(vector<int> v) {\n    v.push_back(1);\n}\n// Original unchanged!", choices: ["Missing & — parameter is a copy, not a reference", "push_back is wrong", "void can't modify", "vector is const"], correctIndex: 0, explanation: "Without `&`, `v` is a copy. Changes don't affect the original. Use `vector<int>& v`.", xp: 15 },
        { kind: "mcq", id: "q-py-cpp-fn-5", prompt: "C++ default arguments must be…", choices: ["At the beginning", "At the end of the parameter list", "In the middle", "Anywhere"], correctIndex: 1, explanation: "Default arguments must trail: `void f(int a, int b = 0)` — not `void f(int a = 0, int b)`.", xp: 10 },
      ],
    },
    {
      id: "py-cpp-collections",
      title: "Strings & Collections",
      tagline: "vector, string, map, and the STL.",
      icon: "📜",
      level: "beginner",
      order: 5,
      requires: ["py-cpp-functions"],
      rewardXp: 100,
      lessons: [
        {
          id: "lesson-py-cpp-col-1",
          title: "STL containers",
          intro: "C++ has the Standard Template Library (STL) with `vector` (list), `string`, `unordered_map` (dict), `unordered_set` (set), `map` (sorted dict), and more. Unlike Python, C++ containers are homogeneous (one type per container). Strings are mutable in C++ (unlike Python).",
          comparisons: [
            { concept: "List → vector", knownCode: "nums = [1, 2, 3]\nnums.append(4)", targetCode: "#include <vector>\nvector<int> nums = {1, 2, 3};\nnums.push_back(4);" },
            { concept: "Dict → unordered_map", knownCode: "ages = {'Ada': 36}", targetCode: "#include <unordered_map>\nunordered_map<string, int> ages;\nages[\"Ada\"] = 36;", note: "Use `map` for sorted keys, `unordered_map` for O(1) lookup." },
            { concept: "String operations", knownCode: "s = \"hello\"\ns = s.upper()\nparts = s.split(',')", targetCode: "string s = \"hello\";\n// No built-in upper/split!\n// Use <algorithm> and manual parsing", note: "C++ strings are more basic than Python's. Many operations need manual code." },
            { concept: "Set", knownCode: "unique = {1, 2, 3}", targetCode: "#include <unordered_set>\nunordered_set<int> unique = {1, 2, 3};" },
          ],
          realWorld: "The STL is one of C++'s greatest strengths. `<algorithm>` provides sort, find, transform, and 100+ more algorithms.",
          exercise: { id: "ex-py-cpp-col-1", prompt: "Create a vector<int> with {1, 2, 3}, push_back 4, and print the size.", starterCode: "#include <vector>\n#include <iostream>\nusing namespace std;\n// Create vector\n", solution: "#include <vector>\n#include <iostream>\nusing namespace std;\nint main() {\n    vector<int> v = {1, 2, 3};\n    v.push_back(4);\n    cout << v.size() << endl;\n    return 0;\n}", expectedOutputIncludes: "4", xp: 25 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-cpp-col-1", prompt: "Python's `list` is C++'s…", choices: ["array", "vector", "list (linked list)", "deque"], correctIndex: 1, explanation: "`std::vector` is the dynamic array. `std::list` is a linked list (rarely used).", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-col-2", prompt: "Python's `dict` maps to C++…", choices: ["map", "unordered_map", "Either — map is sorted, unordered_map is hash-based", "dictionary"], correctIndex: 2, explanation: "`map` = sorted (tree), `unordered_map` = hash-based (closer to Python dict).", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-col-3", prompt: "C++ strings are…", choices: ["Immutable (like Python)", "Mutable", "Primitive types", "Not available"], correctIndex: 1, explanation: "C++ `std::string` is mutable — you can modify characters in-place.", xp: 10 },
        { kind: "debug", id: "q-py-cpp-col-4", prompt: "Why does this crash?", brokenCode: "vector<int> v;\ncout << v[0];  // Undefined behavior!", choices: ["Accessing empty vector — no bounds checking with []", "v is not initialized", "cout can't print ints", "Missing include"], correctIndex: 0, explanation: "`[]` has no bounds checking. Use `.at(0)` to get an exception, or check `.empty()` first.", xp: 15 },
        { kind: "mcq", id: "q-py-cpp-col-5", prompt: "To get a vector's size, use…", choices: ["len(v)", "v.length", "v.size()", "sizeof(v)"], correctIndex: 2, explanation: "`.size()` returns the number of elements. `sizeof` returns bytes of the object.", xp: 10 },
      ],
    },
    // ===================== INTERMEDIATE =====================
    {
      id: "py-cpp-oop",
      title: "OOP & Classes",
      tagline: "Headers, access specifiers, and no `self`.",
      icon: "👑",
      level: "intermediate",
      order: 1,
      requires: [],
      rewardXp: 120,
      lessons: [
        {
          id: "lesson-py-cpp-oop-1",
          title: "Classes in C++",
          intro: "C++ classes have explicit access specifiers (`public`, `private`, `protected`), constructors with initializer lists, destructors, and header/source file separation. `this` is an implicit pointer (not a parameter like Python's `self`). C++ supports multiple inheritance.",
          comparisons: [
            { concept: "Class definition", knownCode: "class Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        return f'{self.name} barks!'", targetCode: "class Dog {\nprivate:\n    string name;\npublic:\n    Dog(const string& n) : name(n) {}\n    string bark() const {\n        return name + \" barks!\";\n    }\n};" },
            { concept: "Instantiation", knownCode: "d = Dog('Rex')", targetCode: "Dog d(\"Rex\");        // Stack\nDog* dp = new Dog(\"Rex\");  // Heap", note: "Stack objects are preferred — auto-destroyed. Heap needs `delete`." },
            { concept: "Inheritance", knownCode: "class Puppy(Dog):\n    def __init__(self, name):\n        super().__init__(name)", targetCode: "class Puppy : public Dog {\npublic:\n    Puppy(const string& n) : Dog(n) {}\n};" },
          ],
          realWorld: "Modern C++ prefers stack allocation and RAII. Use smart pointers (`unique_ptr`, `shared_ptr`) instead of raw `new`/`delete`.",
          exercise: { id: "ex-py-cpp-oop-1", prompt: "Define a `Counter` class with private `count` (0), public `inc()` and `getCount()`. Create one, call inc() twice, print count.", starterCode: "// class Counter { ... };\n", solution: "class Counter {\nprivate:\n    int count = 0;\npublic:\n    void inc() { count++; }\n    int getCount() const { return count; }\n};\n// Counter c; c.inc(); c.inc(); cout << c.getCount();", expectedOutputIncludes: "2", xp: 35 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-cpp-oop-1", prompt: "Python's `self` is C++'s…", choices: ["self", "this (implicit pointer)", "me", "cls"], correctIndex: 1, explanation: "`this` is an implicit pointer to the current instance. Not passed as a parameter.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-oop-2", prompt: "What does `const` after a method mean?", choices: ["The method is constant-time", "The method doesn't modify the object", "The method is static", "The return value is const"], correctIndex: 1, explanation: "`void foo() const` promises not to modify member variables.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-oop-3", prompt: "Default access in a C++ class is…", choices: ["public", "private", "protected", "friend"], correctIndex: 1, explanation: "Unlike Python (everything public), C++ defaults to `private`.", xp: 10 },
        { kind: "debug", id: "q-py-cpp-oop-4", prompt: "Why does this leak memory?", brokenCode: "Dog* d = new Dog(\"Rex\");\n// d goes out of scope — never deleted!", choices: ["Missing `delete d;` — use smart pointers instead", "new is deprecated", "Pointers can't leak", "Dog destructor handles it"], correctIndex: 0, explanation: "`new` allocates on heap. Without `delete`, memory leaks. Use `unique_ptr<Dog>`.", xp: 15 },
        { kind: "mcq", id: "q-py-cpp-oop-5", prompt: "C++ supports multiple class inheritance. Python…", choices: ["Also supports it", "Only single inheritance", "Only interfaces", "Only mixins"], correctIndex: 0, explanation: "Both support multiple inheritance. C++ uses virtual inheritance to handle the diamond problem.", xp: 10 },
      ],
    },
    {
      id: "py-cpp-errors",
      title: "Error Handling",
      tagline: "Exceptions, RAII, and error codes.",
      icon: "🔥",
      level: "intermediate",
      order: 2,
      requires: ["py-cpp-oop"],
      rewardXp: 110,
      lessons: [
        {
          id: "lesson-py-cpp-err-1",
          title: "Exceptions and RAII",
          intro: "C++ has `try/catch` like Python's `try/except`. All exceptions should derive from `std::exception`. C++ also uses RAII (Resource Acquisition Is Initialization) — constructors acquire resources, destructors release them. This replaces Python's `with` statement. Error codes are also common in C++ (especially in C-style APIs).",
          comparisons: [
            { concept: "Try/catch", knownCode: "try:\n    result = risky()\nexcept ValueError as e:\n    print(e)", targetCode: "try {\n    auto result = risky();\n} catch (const exception& e) {\n    cerr << e.what() << endl;\n}" },
            { concept: "Raising/throwing", knownCode: "raise ValueError('bad input')", targetCode: "throw runtime_error(\"bad input\");", note: "No `new` — throw by value, catch by const reference." },
            { concept: "Context manager → RAII", knownCode: "with open('f') as f:\n    data = f.read()", targetCode: "{\n    ifstream file(\"f\");\n    // File auto-closed when `file` goes out of scope\n}", note: "RAII: destructor runs automatically at scope exit." },
          ],
          realWorld: "Many C++ codebases avoid exceptions entirely (Google, embedded systems) and use error codes or `std::expected` (C++23). Know both patterns.",
          exercise: { id: "ex-py-cpp-err-1", prompt: "Write a try/catch that catches a `runtime_error` and prints its message.", starterCode: "#include <stdexcept>\n// Try/catch\n", solution: "try {\n    throw runtime_error(\"something failed\");\n} catch (const runtime_error& e) {\n    cout << e.what() << endl;\n}", expectedOutputIncludes: "something failed", xp: 30 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-cpp-err-1", prompt: "Python's `except` is C++'s…", choices: ["except", "catch", "handle", "rescue"], correctIndex: 1, explanation: "`catch (const exception& e)` in C++.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-err-2", prompt: "RAII stands for…", choices: ["Resource Acquisition Is Initialization", "Runtime Allocation Is Immediate", "Reference And Interface Idiom", "Resource Access In Implementation"], correctIndex: 0, explanation: "RAII: tie resource lifetime to object lifetime. Destructor cleans up.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-err-3", prompt: "Python's `with` is closest to C++…", choices: ["try/catch", "RAII (scope-based cleanup)", "using namespace", "shared_ptr"], correctIndex: 1, explanation: "Both ensure deterministic cleanup when scope exits.", xp: 10 },
        { kind: "debug", id: "q-py-cpp-err-4", prompt: "What's wrong with this catch?", brokenCode: "try { risky(); }\ncatch (exception e) { ... }", choices: ["Should catch by const reference: `const exception& e`", "exception is not a type", "Missing throw", "catch is wrong keyword"], correctIndex: 0, explanation: "Catching by value slices the exception object. Always catch by `const&`.", xp: 15 },
        { kind: "mcq", id: "q-py-cpp-err-5", prompt: "In C++, you should throw by…", choices: ["Pointer (new)", "Value", "Reference", "const"], correctIndex: 1, explanation: "Throw by value, catch by const reference. Never throw pointers.", xp: 10 },
      ],
    },
    {
      id: "py-cpp-headers",
      title: "Headers & Build System",
      tagline: "#include, linking, and CMake.",
      icon: "📦",
      level: "intermediate",
      order: 3,
      requires: ["py-cpp-errors"],
      rewardXp: 100,
      lessons: [
        {
          id: "lesson-py-cpp-hdr-1",
          title: "Headers and compilation",
          intro: "C++ separates declarations (headers `.h`) from definitions (source `.cpp`). `#include` copies header content. The build process: preprocess → compile → link. Build tools like CMake generate build files for various platforms. C++20 modules aim to replace headers.",
          comparisons: [
            { concept: "Import → #include", knownCode: "import math\nfrom os import path", targetCode: "#include <cmath>\n#include \"myheader.h\"", note: "`<>` for system headers, `\"\"` for local headers." },
            { concept: "Package manager → vcpkg/Conan", knownCode: "pip install requests", targetCode: "// vcpkg install boost\n// Or: conan install .\n// CMakeLists.txt manages the build", note: "C++ dependency management is more manual than Python's pip." },
          ],
          realWorld: "CMake is the de facto standard build system. `vcpkg` and `Conan` are the main package managers. C++20 modules will eventually replace headers.",
          exercise: { id: "ex-py-cpp-hdr-1", prompt: "Write the #include needed for vector, string, and iostream.", starterCode: "// Write the includes\n", solution: "#include <vector>\n#include <string>\n#include <iostream>", expectedOutputIncludes: "#include", xp: 15 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-cpp-hdr-1", prompt: "`#include <cmath>` is like Python's…", choices: ["import math", "from math import *", "import cmath", "require('math')"], correctIndex: 0, explanation: "`<cmath>` is the C++ math header (C++ version of C's math.h).", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-hdr-2", prompt: "What does `#include` actually do?", choices: ["Imports a module", "Copies the file content into the source", "Links a library", "Downloads a package"], correctIndex: 1, explanation: "`#include` is a preprocessor directive — literally copy-pastes the header content.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-hdr-3", prompt: "The standard C++ build tool is…", choices: ["pip", "Make", "CMake", "npm"], correctIndex: 2, explanation: "CMake generates build files for various compilers and platforms.", xp: 10 },
        { kind: "debug", id: "q-py-cpp-hdr-4", prompt: "Why does this compile twice but link fails?", brokenCode: "// utils.h\nvoid helper() { cout << \"hi\"; }\n// Both a.cpp and b.cpp include utils.h", choices: ["Multiple definition error — define in .cpp, only declare in .h", "cout is wrong", "Missing include guard", "Both A and C are issues"], correctIndex: 3, explanation: "Use header guards (`#pragma once`) AND only declare functions in headers.", xp: 15 },
      ],
    },
    {
      id: "py-cpp-stl",
      title: "STL Algorithms",
      tagline: "sort, find, transform — the C++ power tools.",
      icon: "⚡",
      level: "intermediate",
      order: 4,
      requires: ["py-cpp-headers"],
      rewardXp: 130,
      lessons: [
        {
          id: "lesson-py-cpp-stl-1",
          title: "Algorithms and iterators",
          intro: "The `<algorithm>` header provides 100+ algorithms: `sort`, `find`, `transform`, `accumulate`, `any_of`, `all_of`, `count_if`, etc. They work with iterators — a generic way to traverse containers. C++20 Ranges provide a more Pythonic pipeline style.",
          comparisons: [
            { concept: "Sort", knownCode: "nums.sort()\nnums.sort(key=len)", targetCode: "#include <algorithm>\nsort(nums.begin(), nums.end());\n// Custom: sort(v.begin(), v.end(), [](auto& a, auto& b) { return a > b; });" },
            { concept: "Filter", knownCode: "evens = [x for x in nums if x % 2 == 0]", targetCode: "vector<int> evens;\ncopy_if(nums.begin(), nums.end(), back_inserter(evens),\n    [](int x) { return x % 2 == 0; });" },
            { concept: "Accumulate (reduce)", knownCode: "total = sum(nums)", targetCode: "#include <numeric>\nint total = accumulate(nums.begin(), nums.end(), 0);" },
          ],
          realWorld: "C++20 Ranges: `auto evens = nums | views::filter([](int x){ return x%2==0; });` — much closer to Python style.",
          exercise: { id: "ex-py-cpp-stl-1", prompt: "Sort a vector {5, 3, 1, 4, 2} and print the result.", starterCode: "#include <algorithm>\n#include <vector>\n// Sort and print\n", solution: "vector<int> v = {5, 3, 1, 4, 2};\nsort(v.begin(), v.end());\nfor (int x : v) cout << x << \" \";", expectedOutputIncludes: "1 2 3 4 5", xp: 30 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-cpp-stl-1", prompt: "Python's `sum(nums)` is C++'s…", choices: ["sum(nums)", "accumulate(nums.begin(), nums.end(), 0)", "total(nums)", "reduce(nums)"], correctIndex: 1, explanation: "`std::accumulate` from `<numeric>` header.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-stl-2", prompt: "What is an iterator in C++?", choices: ["A pointer substitute", "A generalized pointer for traversing containers", "A loop keyword", "A template parameter"], correctIndex: 1, explanation: "Iterators abstract position within a container. `.begin()` and `.end()` define a range.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-stl-3", prompt: "C++20 Ranges provide…", choices: ["A range() function like Python", "Composable, lazy view pipelines (filter | transform)", "Async iteration", "Garbage collection"], correctIndex: 1, explanation: "Ranges: `nums | views::filter(pred) | views::transform(fn)` — pipeline style.", xp: 10 },
        { kind: "debug", id: "q-py-cpp-stl-4", prompt: "Why does `sort(v)` fail?", brokenCode: "vector<int> v = {3, 1, 2};\nsort(v);  // Error!", choices: ["sort takes iterator range, not container: sort(v.begin(), v.end())", "v is const", "Missing include", "sort is not a function"], correctIndex: 0, explanation: "STL algorithms work on iterator ranges, not containers directly. (C++20 `ranges::sort(v)` works though.)", xp: 15 },
        { kind: "mcq", id: "q-py-cpp-stl-5", prompt: "`back_inserter(v)` creates…", choices: ["A reverse iterator", "An output iterator that push_back's into v", "A copy of v", "A const iterator"], correctIndex: 1, explanation: "It creates an iterator that appends to the vector with `push_back`.", xp: 10 },
      ],
    },
    // ===================== ADVANCED =====================
    {
      id: "py-cpp-memory",
      title: "Memory & Pointers",
      tagline: "Stack, heap, pointers, and smart pointers.",
      icon: "🧠",
      level: "advanced",
      order: 1,
      requires: [],
      rewardXp: 170,
      lessons: [
        {
          id: "lesson-py-cpp-mem-1",
          title: "Memory model",
          intro: "C++ gives you direct control over memory. Stack allocation is automatic and fast. Heap allocation uses `new`/`delete`. Modern C++ uses smart pointers: `unique_ptr` (sole ownership), `shared_ptr` (shared ownership), `weak_ptr` (non-owning). Raw pointers are for non-owning observation only.",
          comparisons: [
            { concept: "Object creation", knownCode: "obj = MyClass()  # Always heap + GC", targetCode: "MyClass obj;          // Stack (automatic)\nauto p = make_unique<MyClass>();  // Heap (smart ptr)" },
            { concept: "Ownership", knownCode: "# Python: GC handles everything", targetCode: "unique_ptr<Dog> owner = make_unique<Dog>(\"Rex\");\n// Ownership transfers on move:\nauto new_owner = move(owner);  // owner is now null", note: "`unique_ptr` ensures exactly one owner. No leaks." },
            { concept: "Shared ownership", knownCode: "# Python: reference counting", targetCode: "auto dog = make_shared<Dog>(\"Rex\");\nauto copy = dog;  // Both share ownership\n// Deleted when last shared_ptr dies", note: "Like Python's reference counting, but explicit." },
          ],
          realWorld: "Rule of thumb: use `unique_ptr` by default, `shared_ptr` when you need shared ownership, raw pointers only for non-owning references.",
          exercise: { id: "ex-py-cpp-mem-1", prompt: "Create a unique_ptr<string> holding \"hello\". Print the string through the pointer.", starterCode: "#include <memory>\n// unique_ptr\n", solution: "auto p = make_unique<string>(\"hello\");\ncout << *p << endl;", expectedOutputIncludes: "hello", xp: 40 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-cpp-mem-1", prompt: "Python objects live on…", choices: ["Stack", "Heap (always)", "Either", "Registers"], correctIndex: 1, explanation: "Python allocates all objects on the heap with reference counting.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-mem-2", prompt: "`unique_ptr` enforces…", choices: ["Shared ownership", "Sole ownership — only one pointer to the object", "No ownership", "Weak references"], correctIndex: 1, explanation: "`unique_ptr` can't be copied, only moved. Ensures single owner.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-mem-3", prompt: "What is a dangling pointer?", choices: ["A null pointer", "A pointer to freed memory", "An uninitialized pointer", "A const pointer"], correctIndex: 1, explanation: "Accessing freed memory is undefined behavior — one of C++'s most dangerous bugs.", xp: 10 },
        { kind: "debug", id: "q-py-cpp-mem-4", prompt: "What's wrong here?", brokenCode: "int* p = new int(42);\nint* q = p;\ndelete p;\ncout << *q;  // Use after free!", choices: ["q is a dangling pointer after delete p — undefined behavior", "delete is wrong", "cout can't print pointers", "Missing include"], correctIndex: 0, explanation: "After `delete p`, both `p` and `q` are dangling. Use `shared_ptr` or `unique_ptr`.", xp: 15 },
        { kind: "mcq", id: "q-py-cpp-mem-5", prompt: "`make_unique` vs `new`:", choices: ["Same thing", "make_unique is exception-safe and doesn't leak", "new is faster", "make_unique allocates on stack"], correctIndex: 1, explanation: "`make_unique<T>(args)` is exception-safe — use it instead of `new`.", xp: 10 },
      ],
    },
    {
      id: "py-cpp-concurrency",
      title: "Concurrency",
      tagline: "Real threads — no GIL!",
      icon: "🔄",
      level: "advanced",
      order: 2,
      requires: ["py-cpp-memory"],
      rewardXp: 170,
      lessons: [
        {
          id: "lesson-py-cpp-conc-1",
          title: "Threads and synchronization",
          intro: "C++ has real threads with true parallelism — no GIL. `std::thread` creates OS threads. `std::mutex` and `std::lock_guard` provide synchronization. `std::async` and `std::future` provide task-based parallelism. C++20 adds coroutines for async-like programming.",
          comparisons: [
            { concept: "Threading", knownCode: "import threading\nt = threading.Thread(target=func)\nt.start(); t.join()", targetCode: "#include <thread>\nthread t(func);\nt.join();", note: "C++ threads run truly in parallel on multiple cores." },
            { concept: "Lock", knownCode: "lock = threading.Lock()\nwith lock: ...", targetCode: "mutex mtx;\n{\n    lock_guard<mutex> lock(mtx);\n    // critical section\n}  // Auto-unlocked via RAII" },
            { concept: "Async/await", knownCode: "import asyncio\nresult = await coroutine()", targetCode: "auto fut = async(launch::async, func);\nauto result = fut.get();  // Blocks until ready", note: "C++20 has coroutines but they're low-level compared to Python asyncio." },
          ],
          realWorld: "Use `std::jthread` (C++20) for auto-joining threads. Use `std::atomic` for lock-free programming on simple values.",
          exercise: { id: "ex-py-cpp-conc-1", prompt: "Create a thread that prints 'hello', start and join it.", starterCode: "#include <thread>\n#include <iostream>\n// Thread\n", solution: "#include <thread>\n#include <iostream>\nusing namespace std;\nvoid hello() { cout << \"hello\" << endl; }\nint main() {\n    thread t(hello);\n    t.join();\n    return 0;\n}", expectedOutputIncludes: "hello", xp: 40 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-cpp-conc-1", prompt: "C++ threads vs Python threads:", choices: ["Both limited by GIL", "C++ has real parallelism, Python has GIL", "Both are real OS threads", "Neither supports parallelism"], correctIndex: 1, explanation: "C++ threads run truly in parallel. Python's GIL serializes them.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-conc-2", prompt: "`lock_guard` provides…", choices: ["Manual locking", "RAII-based automatic lock/unlock", "Recursive locking", "Read-write locking"], correctIndex: 1, explanation: "Lock on construction, unlock on destruction. Can't forget to unlock.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-conc-3", prompt: "`std::atomic<int>` provides…", choices: ["Thread-safe int without explicit locking", "Bigger integers", "Async operations", "Memory allocation"], correctIndex: 0, explanation: "Atomic types use hardware instructions for lock-free thread safety.", xp: 10 },
        { kind: "debug", id: "q-py-cpp-conc-4", prompt: "Why does this crash?", brokenCode: "thread t(func);\n// t goes out of scope without join or detach!", choices: ["Must call t.join() or t.detach() before thread object is destroyed", "func is wrong", "Missing include", "thread is deprecated"], correctIndex: 0, explanation: "Destroying a joinable thread calls `std::terminate()`. Always join or detach.", xp: 15 },
        { kind: "mcq", id: "q-py-cpp-conc-5", prompt: "C++20 `std::jthread` auto-…", choices: ["Parallelizes code", "Joins on destruction", "Detaches on creation", "Uses coroutines"], correctIndex: 1, explanation: "`jthread` joins automatically when destroyed — safer than `thread`.", xp: 10 },
      ],
    },
    {
      id: "py-cpp-templates",
      title: "Templates & Advanced",
      tagline: "Generic programming and compile-time magic.",
      icon: "✨",
      level: "advanced",
      order: 3,
      requires: ["py-cpp-concurrency"],
      rewardXp: 200,
      lessons: [
        {
          id: "lesson-py-cpp-tmpl-1",
          title: "Templates",
          intro: "C++ templates are like Python's duck typing but at compile time. The compiler generates specialized code for each type used. Templates are far more powerful than Java generics — no type erasure. C++20 concepts constrain template parameters (like Python's `Protocol`).",
          comparisons: [
            { concept: "Generic function", knownCode: "def first(items):\n    return items[0]  # Duck typing", targetCode: "template <typename T>\nT first(const vector<T>& items) {\n    return items[0];\n}", note: "Template generates separate code for each type. No runtime overhead." },
            { concept: "Concepts (C++20)", knownCode: "from typing import Protocol\nclass Sized(Protocol):\n    def __len__(self) -> int: ...", targetCode: "template <typename T>\nconcept Sortable = requires(T a, T b) {\n    { a < b } -> convertible_to<bool>;\n};", note: "Concepts constrain template parameters — better error messages." },
          ],
          realWorld: "Templates are one of C++'s most powerful features. The entire STL is built with templates.",
          exercise: { id: "ex-py-cpp-tmpl-1", prompt: "Write a template function `maxOf(T a, T b)` that returns the larger value. Test with ints.", starterCode: "// template <typename T>\n// T maxOf(T a, T b) { ... }\n", solution: "template <typename T>\nT maxOf(T a, T b) {\n    return (a > b) ? a : b;\n}\n// cout << maxOf(3, 7);  // 7", expectedOutputIncludes: "7", xp: 45 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-cpp-tmpl-1", prompt: "C++ templates vs Java generics:", choices: ["Same thing", "Templates generate code per type, generics use type erasure", "Generics are faster", "Templates only work with ints"], correctIndex: 1, explanation: "Templates: code generation (zero overhead). Generics: type erasure (single implementation).", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-tmpl-2", prompt: "C++20 concepts are like Python's…", choices: ["Decorators", "Protocols / ABCs", "Type hints", "Metaclasses"], correctIndex: 1, explanation: "Both define constraints on types. Concepts are checked at compile time.", xp: 10 },
        { kind: "mcq", id: "q-py-cpp-tmpl-3", prompt: "Template instantiation happens at…", choices: ["Runtime", "Compile time", "Link time", "Import time"], correctIndex: 1, explanation: "The compiler generates specialized code for each type used.", xp: 10 },
        { kind: "debug", id: "q-py-cpp-tmpl-4", prompt: "Why is this error message terrible?", brokenCode: "template <typename T>\nvoid process(T x) { x.frobnicate(); }\n// process(42);  // int has no frobnicate!", choices: ["Without concepts, template errors are generated at instantiation — use C++20 concepts for better errors", "Templates can't take ints", "frobnicate is reserved", "Missing include"], correctIndex: 0, explanation: "Without concepts, you get pages of errors deep in template code. Concepts provide clear error messages.", xp: 15 },
        { kind: "mcq", id: "q-py-cpp-tmpl-5", prompt: "Can templates be used for compile-time computation?", choices: ["No", "Yes — template metaprogramming and constexpr", "Only in C++20", "Only with concepts"], correctIndex: 1, explanation: "Templates + `constexpr` enable compile-time computation. This has no Python equivalent.", xp: 10 },
      ],
    },
  ],
};
