import type { Course } from "@/lib/types";

export const pythonToJava: Course = {
  id: "python-to-java",
  knownLang: "python",
  targetLang: "java",
  title: "Python → Java",
  modules: [
    // ===================== BEGINNER =====================
    {
      id: "py-java-variables",
      title: "Variables & Types",
      tagline: "From dynamic duck-typing to static declarations.",
      icon: "🏰",
      level: "beginner",
      order: 1,
      requires: [],
      rewardXp: 60,
      lessons: [
        {
          id: "lesson-py-java-vars-1",
          title: "Static types and declarations",
          intro: "Java requires you to declare the type of every variable. There's no guessing — `int x = 5;` not just `x = 5`. Java has 8 primitive types (`int`, `double`, `boolean`, `char`, `byte`, `short`, `long`, `float`) and reference types (objects). Every statement ends with a semicolon. Java 10+ has `var` for local type inference.",
          comparisons: [
            { concept: "Variable declaration", knownCode: "count = 0\nname = \"Ada\"", targetCode: "int count = 0;\nString name = \"Ada\";", note: "Type comes first. Semicolons are mandatory." },
            { concept: "Constants", knownCode: "PI = 3.14159  # Convention only", targetCode: "final double PI = 3.14159;", note: "`final` is enforced by the compiler — unlike Python's ALL_CAPS convention." },
            { concept: "Type inference (Java 10+)", knownCode: "x = 42  # Python infers type", targetCode: "var x = 42;  // Compiler infers int", note: "`var` only works for local variables. Fields and parameters need explicit types." },
            { concept: "Boolean", knownCode: "done = True\nnothing = None", targetCode: "boolean done = true;\nObject nothing = null;", note: "`True/False/None` → `true/false/null` (lowercase)." },
          ],
          realWorld: "Java's static typing catches many bugs at compile time that Python only catches at runtime. This is a major advantage for large codebases.",
          exercise: { id: "ex-py-java-vars-1", prompt: "Declare an `int` variable `age` set to 25 and a `String` variable `name` set to \"Ada\". Print both.", starterCode: "// Declare age and name, then print\n", solution: "int age = 25;\nString name = \"Ada\";\nSystem.out.println(name + \" is \" + age);", expectedOutputIncludes: "Ada", xp: 20 },
        },
        {
          id: "lesson-py-java-vars-2",
          title: "Wrappers, autoboxing, and null",
          intro: "Java primitives (`int`, `double`) can't be null and don't work with generics. Wrapper classes (`Integer`, `Double`) bridge this gap. Autoboxing converts between them automatically. But unboxing `null` throws `NullPointerException` — Java's most infamous runtime error.",
          comparisons: [
            { concept: "Type conversion", knownCode: "n = int(\"42\")\ns = str(42)", targetCode: "int n = Integer.parseInt(\"42\");\nString s = String.valueOf(42);", note: "Use static methods on wrapper classes, not constructors." },
            { concept: "Null handling", knownCode: "x = None\nif x is None: ...", targetCode: "Integer x = null;\nif (x == null) { ... }", note: "Primitives can't be null — only reference types (including wrappers) can." },
            { concept: "Optional (safe null)", knownCode: "# Python doesn't have built-in Optional", targetCode: "Optional<String> name = Optional.ofNullable(getName());\nString result = name.orElse(\"Unknown\");", note: "Java's `Optional<T>` is like a type-safe null check." },
          ],
          realWorld: "Modern Java best practice: use `Optional<T>` for return values that might be absent. Never use it for fields or parameters.",
          exercise: { id: "ex-py-java-vars-2", prompt: "Convert the string \"99\" to an int, add 1, and print the result.", starterCode: "String s = \"99\";\n// Convert and add 1\n", solution: "String s = \"99\";\nint n = Integer.parseInt(s) + 1;\nSystem.out.println(n);", expectedOutputIncludes: "100", xp: 25 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-java-var-1", prompt: "Python's `True` becomes what in Java?", choices: ["True", "true", "TRUE", "1"], correctIndex: 1, explanation: "Java booleans are lowercase: `true`, `false`.", xp: 10 },
        { kind: "mcq", id: "q-py-java-var-2", prompt: "What does `final` do in Java?", choices: ["Makes a variable thread-safe", "Prevents reassignment", "Makes a variable global", "Converts to constant type"], correctIndex: 1, explanation: "`final` prevents the variable from being reassigned — enforced by compiler.", xp: 10 },
        { kind: "mcq", id: "q-py-java-var-3", prompt: "Why can't you write `List<int>`?", choices: ["int is not imported", "Generics require reference types — use `Integer`", "List doesn't exist", "int is deprecated"], correctIndex: 1, explanation: "Java generics use type erasure — primitives aren't reference types.", xp: 10 },
        { kind: "debug", id: "q-py-java-var-4", prompt: "Why does this crash?", brokenCode: "Integer x = null;\nint y = x;  // NullPointerException!", choices: ["Unboxing null throws NullPointerException", "null can't be assigned to Integer", "int and Integer are incompatible", "Missing import"], correctIndex: 0, explanation: "Autoboxing tries to call `.intValue()` on null → NPE.", xp: 15 },
        { kind: "mcq", id: "q-py-java-var-5", prompt: "Every Java statement must end with…", choices: ["A colon", "Nothing", "A semicolon", "A newline"], correctIndex: 2, explanation: "Semicolons are mandatory in Java, unlike Python.", xp: 10 },
      ],
    },
    {
      id: "py-java-controlflow",
      title: "Control Flow",
      tagline: "Braces and parens are back — and no more `elif`.",
      icon: "🛡️",
      level: "beginner",
      order: 2,
      requires: ["py-java-variables"],
      rewardXp: 70,
      lessons: [
        {
          id: "lesson-py-java-cf-1",
          title: "if/else and switch",
          intro: "Java uses curly braces for blocks (not indentation) and parentheses around conditions. `elif` becomes `else if`. Java requires boolean expressions — no truthiness like Python. Java 14+ has enhanced switch with arrow syntax and pattern matching.",
          comparisons: [
            { concept: "if / elif / else", knownCode: "if score > 90:\n    print('A')\nelif score > 75:\n    print('B')\nelse:\n    print('C')", targetCode: "if (score > 90) {\n    System.out.println(\"A\");\n} else if (score > 75) {\n    System.out.println(\"B\");\n} else {\n    System.out.println(\"C\");\n}", note: "`elif` → `else if`. Parentheses around condition. Braces for blocks." },
            { concept: "Ternary", knownCode: "result = 'yes' if x > 0 else 'no'", targetCode: "String result = (x > 0) ? \"yes\" : \"no\";", note: "Java ternary: `condition ? valueTrue : valueFalse`." },
            { concept: "No truthiness", knownCode: "if items:  # Truthy check\n    ...", targetCode: "if (!items.isEmpty()) {\n    // ...\n}", note: "Java requires explicit boolean. No implicit bool conversion from ints or collections." },
          ],
          realWorld: "Java's explicitness about booleans prevents subtle Python-style truthiness bugs but requires more verbose code.",
          exercise: { id: "ex-py-java-cf-1", prompt: "Write an if/else if/else chain that prints the letter grade for `score = 82`: A (>90), B (>75), C (>60), F otherwise.", starterCode: "int score = 82;\n// Grade logic\n", solution: "int score = 82;\nif (score > 90) {\n    System.out.println(\"A\");\n} else if (score > 75) {\n    System.out.println(\"B\");\n} else if (score > 60) {\n    System.out.println(\"C\");\n} else {\n    System.out.println(\"F\");\n}", expectedOutputIncludes: "B", xp: 25 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-java-cf-1", prompt: "Python's `elif` becomes what in Java?", choices: ["elif", "elseif", "else if", "elsif"], correctIndex: 2, explanation: "Two separate words: `else if`.", xp: 10 },
        { kind: "mcq", id: "q-py-java-cf-2", prompt: "Can you write `if (list)` in Java to check non-empty?", choices: ["Yes", "No — must use `if (!list.isEmpty())`", "Only for arrays", "Only with var"], correctIndex: 1, explanation: "Java has no truthiness. Conditions must be boolean.", xp: 10 },
        { kind: "mcq", id: "q-py-java-cf-3", prompt: "Java's ternary operator syntax is…", choices: ["x if cond else y", "cond ? x : y", "cond then x else y", "x unless cond"], correctIndex: 1, explanation: "`condition ? valueIfTrue : valueIfFalse`.", xp: 10 },
        { kind: "debug", id: "q-py-java-cf-4", prompt: "Why doesn't this compile?", brokenCode: "if score > 90 {\n    System.out.println(\"A\");\n}", choices: ["Missing parentheses around condition", "Missing semicolon", "score not declared", "Wrong bracket type"], correctIndex: 0, explanation: "Java requires `if (condition)` — parentheses are mandatory.", xp: 15 },
        { kind: "mcq", id: "q-py-java-cf-5", prompt: "Java's enhanced switch (14+) uses…", choices: ["case x then ...", "case x -> ...", "when x: ...", "match x: ..."], correctIndex: 1, explanation: "Arrow syntax: `case value -> expression;` with no fall-through.", xp: 10 },
      ],
    },
    {
      id: "py-java-loops",
      title: "Loops & Iteration",
      tagline: "No `range()`, but enhanced for and streams.",
      icon: "🌀",
      level: "beginner",
      order: 3,
      requires: ["py-java-controlflow"],
      rewardXp: 80,
      lessons: [
        {
          id: "lesson-py-java-loops-1",
          title: "For loops in Java",
          intro: "Java has classic C-style for loops and enhanced for-each loops (`for (Type x : collection)`). There's no built-in `range()`. For counting, use `for (int i = 0; i < n; i++)`. Java 8+ Streams provide functional iteration similar to Python's comprehensions.",
          comparisons: [
            { concept: "Range loop", knownCode: "for i in range(5):\n    print(i)", targetCode: "for (int i = 0; i < 5; i++) {\n    System.out.println(i);\n}", note: "No `range()` — use classic C-style for loop." },
            { concept: "For-each", knownCode: "for word in words:\n    print(word)", targetCode: "for (String word : words) {\n    System.out.println(word);\n}", note: "Colon `:` instead of `in`. Type is required." },
            { concept: "Enumerate equivalent", knownCode: "for i, item in enumerate(items):\n    print(i, item)", targetCode: "for (int i = 0; i < items.size(); i++) {\n    System.out.println(i + \" \" + items.get(i));\n}", note: "Java has no `enumerate`. Use index loop or IntStream." },
            { concept: "List comprehension → Stream", knownCode: "evens = [x for x in nums if x % 2 == 0]", targetCode: "List<Integer> evens = nums.stream()\n    .filter(x -> x % 2 == 0)\n    .collect(Collectors.toList());", note: "Streams are Java's closest equivalent to comprehensions." },
          ],
          realWorld: "Use enhanced for-each when you don't need the index. Use Streams for functional transformations. Classic for loops for index-based iteration.",
          exercise: { id: "ex-py-java-loops-1", prompt: "Print numbers 1 through 5 using a for loop.", starterCode: "// Print 1 to 5\n", solution: "for (int i = 1; i <= 5; i++) {\n    System.out.println(i);\n}", expectedOutputIncludes: "1\n2\n3\n4\n5", xp: 20 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-java-loop-1", prompt: "Java's equivalent of `for x in items:` is…", choices: ["for (x in items)", "for (var x : items)", "for x of items", "foreach (x in items)"], correctIndex: 1, explanation: "`for (Type x : iterable)` is Java's enhanced for-each.", xp: 10 },
        { kind: "mcq", id: "q-py-java-loop-2", prompt: "Java has a built-in `range()` function.", choices: ["True", "False — use IntStream.range() or classic for"], correctIndex: 1, explanation: "Use `IntStream.range(0, 5)` or `for (int i = 0; i < 5; i++)`.", xp: 10 },
        { kind: "mcq", id: "q-py-java-loop-3", prompt: "Python list comprehensions map to Java…", choices: ["for loops with add()", "Stream API (filter/map/collect)", "Array literals", "Lambda arrays"], correctIndex: 1, explanation: "Streams are the functional equivalent of comprehensions.", xp: 10 },
        { kind: "debug", id: "q-py-java-loop-4", prompt: "Why does this throw ConcurrentModificationException?", brokenCode: "for (String s : list) {\n    if (s.equals(\"bad\")) list.remove(s);\n}", choices: ["Can't modify collection during enhanced for-each — use Iterator or removeIf()", "remove() doesn't exist", "equals() is wrong", "Missing break"], correctIndex: 0, explanation: "Use `list.removeIf(s -> s.equals(\"bad\"))` or an explicit Iterator.", xp: 15 },
        { kind: "mcq", id: "q-py-java-loop-5", prompt: "How do you break out of nested loops in Java?", choices: ["break 2", "break outer (with labeled break)", "return", "Cannot"], correctIndex: 1, explanation: "Label the outer loop: `outer: for(...)` then `break outer;`.", xp: 10 },
      ],
    },
    {
      id: "py-java-functions",
      title: "Methods & Overloading",
      tagline: "No `def` — methods live inside classes.",
      icon: "⚔️",
      level: "beginner",
      order: 4,
      requires: ["py-java-loops"],
      rewardXp: 90,
      lessons: [
        {
          id: "lesson-py-java-fn-1",
          title: "Methods and lambdas",
          intro: "Java has no free functions — everything is a method inside a class. `static` methods are the closest to Python functions. Java doesn't support default arguments — use method overloading. Java 8+ lambdas enable functional programming but require a functional interface type.",
          comparisons: [
            { concept: "Function → Method", knownCode: "def add(a, b):\n    return a + b", targetCode: "static int add(int a, int b) {\n    return a + b;\n}", note: "Return type required. Must be inside a class." },
            { concept: "Default args → Overloading", knownCode: "def greet(name=\"World\"):\n    print(f\"Hello, {name}!\")", targetCode: "static void greet() { greet(\"World\"); }\nstatic void greet(String name) {\n    System.out.println(\"Hello, \" + name + \"!\");\n}", note: "Overload by providing multiple method signatures." },
            { concept: "Lambda", knownCode: "double = lambda x: x * 2", targetCode: "Function<Integer, Integer> doubleIt = x -> x * 2;", note: "Java lambdas need a functional interface type." },
            { concept: "*args / **kwargs", knownCode: "def log(*args, **kwargs): ...", targetCode: "static void log(Object... args) {\n    for (Object a : args) System.out.print(a);\n}", note: "Java varargs (`...`) covers `*args`. No `**kwargs` equivalent." },
          ],
          realWorld: "Common functional interfaces: `Function<T,R>`, `Predicate<T>`, `Consumer<T>`, `Supplier<T>`, `BiFunction<T,U,R>`.",
          exercise: { id: "ex-py-java-fn-1", prompt: "Write a static method `square(int n)` that returns n squared. Print `square(7)`.", starterCode: "// static int square(int n) { ... }\n", solution: "static int square(int n) {\n    return n * n;\n}\n// System.out.println(square(7));", expectedOutputIncludes: "49", xp: 25 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-java-fn-1", prompt: "Can Java have free functions outside a class?", choices: ["Yes", "No — all methods must be in a class", "Only lambdas", "Only main()"], correctIndex: 1, explanation: "Everything in Java is inside a class.", xp: 10 },
        { kind: "mcq", id: "q-py-java-fn-2", prompt: "Java's alternative to default arguments is…", choices: ["Optional params", "Method overloading", "Named arguments", "kwargs"], correctIndex: 1, explanation: "Define multiple methods with different parameter lists.", xp: 10 },
        { kind: "mcq", id: "q-py-java-fn-3", prompt: "Java varargs syntax `Object... args` is like Python's…", choices: ["**kwargs", "*args", "def f(args=[])", "list comprehension"], correctIndex: 1, explanation: "Varargs collects extra arguments into an array, like Python's `*args` into a tuple.", xp: 10 },
        { kind: "debug", id: "q-py-java-fn-4", prompt: "Why doesn't this compile?", brokenCode: "static void greet(String name = \"World\") {\n    System.out.println(name);\n}", choices: ["Java doesn't support default parameter values", "String can't have defaults", "Missing return type", "void is wrong"], correctIndex: 0, explanation: "Use method overloading instead.", xp: 15 },
        { kind: "mcq", id: "q-py-java-fn-5", prompt: "`x -> x * 2` in Java is a…", choices: ["Arrow function", "Lambda expression", "Method reference", "Closure"], correctIndex: 1, explanation: "Java's lambda syntax uses `->` (not `=>`). Requires a functional interface type.", xp: 10 },
      ],
    },
    {
      id: "py-java-collections",
      title: "Strings & Collections",
      tagline: "ArrayList, HashMap, and .equals() — not ==.",
      icon: "📜",
      level: "beginner",
      order: 5,
      requires: ["py-java-functions"],
      rewardXp: 100,
      lessons: [
        {
          id: "lesson-py-java-col-1",
          title: "Strings and collections",
          intro: "Java strings are immutable objects compared with `.equals()` (not `==`!). Collections use interfaces (`List`, `Map`, `Set`) with implementations (`ArrayList`, `HashMap`, `HashSet`). Generics can't use primitives — use `Integer` not `int`.",
          comparisons: [
            { concept: "String comparison", knownCode: "if s1 == s2: ...", targetCode: "if (s1.equals(s2)) { ... }", note: "`==` in Java compares references! Always use `.equals()` for strings." },
            { concept: "List (dynamic array)", knownCode: "nums = [1, 2, 3]\nnums.append(4)", targetCode: "List<Integer> nums = new ArrayList<>(List.of(1, 2, 3));\nnums.add(4);", note: "Must use `Integer` wrapper. `add()` instead of `append()`." },
            { concept: "Dict → HashMap", knownCode: "ages = {'Ada': 36, 'Bob': 25}", targetCode: "Map<String, Integer> ages = new HashMap<>();\nages.put(\"Ada\", 36);\nages.put(\"Bob\", 25);", note: "`.put()` and `.get()` instead of `[]` operator." },
            { concept: "Set", knownCode: "unique = {1, 2, 3}", targetCode: "Set<Integer> unique = new HashSet<>(Set.of(1, 2, 3));", note: "HashSet is unordered. LinkedHashSet preserves insertion order." },
          ],
          realWorld: "Program to interfaces: declare `List<T>` not `ArrayList<T>`. This enables easy implementation swapping.",
          exercise: { id: "ex-py-java-col-1", prompt: "Create a HashMap with \"Alice\"→90, \"Bob\"→85. Print Bob's score.", starterCode: "// Create map and print Bob's score\n", solution: "Map<String, Integer> scores = new HashMap<>();\nscores.put(\"Alice\", 90);\nscores.put(\"Bob\", 85);\nSystem.out.println(scores.get(\"Bob\"));", expectedOutputIncludes: "85", xp: 30 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-java-col-1", prompt: "How do you compare strings in Java?", choices: ["==", ".equals()", "is", ".compare()"], correctIndex: 1, explanation: "`==` compares references. `.equals()` compares content.", xp: 10 },
        { kind: "mcq", id: "q-py-java-col-2", prompt: "Python's `dict` maps to Java's…", choices: ["Dictionary", "HashMap", "Hashtable", "TreeMap"], correctIndex: 1, explanation: "HashMap is the standard implementation of Map interface.", xp: 10 },
        { kind: "mcq", id: "q-py-java-col-3", prompt: "Python's `append()` is Java's…", choices: ["push()", "add()", "append()", "insert()"], correctIndex: 1, explanation: "Java's `List.add()` appends to the end.", xp: 10 },
        { kind: "debug", id: "q-py-java-col-4", prompt: "Why does this print false?", brokenCode: "String a = new String(\"hello\");\nString b = new String(\"hello\");\nSystem.out.println(a == b);", choices: ["`==` compares references — use `.equals()`", "new String is deprecated", "Strings can't be compared", "Missing import"], correctIndex: 0, explanation: "`new String()` creates distinct objects. `==` compares object identity.", xp: 15 },
        { kind: "mcq", id: "q-py-java-col-5", prompt: "What interface should you declare for a mutable list?", choices: ["ArrayList<T>", "List<T>", "Collection<T>", "MutableList<T>"], correctIndex: 1, explanation: "Program to the interface: `List<T> list = new ArrayList<>();`.", xp: 10 },
      ],
    },
    // ===================== INTERMEDIATE =====================
    {
      id: "py-java-oop",
      title: "OOP & Classes",
      tagline: "Interfaces, abstract classes, and access modifiers.",
      icon: "👑",
      level: "intermediate",
      order: 1,
      requires: [],
      rewardXp: 120,
      lessons: [
        {
          id: "lesson-py-java-oop-1",
          title: "Classes and interfaces",
          intro: "Java classes have explicit access modifiers (`public`, `private`, `protected`), constructors, and single inheritance with `extends`. Interfaces define contracts (`implements`). Python's duck typing becomes explicit interface implementation. Java 16+ has `record` for data classes.",
          comparisons: [
            { concept: "Class definition", knownCode: "class Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        return f'{self.name} says woof!'", targetCode: "public class Dog {\n    private String name;\n    public Dog(String name) {\n        this.name = name;\n    }\n    public String bark() {\n        return name + \" says woof!\";\n    }\n}" },
            { concept: "Interface (duck typing → explicit)", knownCode: "# Python: just implement the methods\nclass Dog:\n    def speak(self): return 'woof'", targetCode: "interface Speakable {\n    String speak();\n}\nclass Dog implements Speakable {\n    public String speak() { return \"woof\"; }\n}" },
            { concept: "Data class → Record", knownCode: "@dataclass\nclass Point:\n    x: int\n    y: int", targetCode: "record Point(int x, int y) { }\n// Auto: constructor, getters, equals, hashCode, toString", note: "Records (Java 16+) are like Python dataclasses." },
          ],
          realWorld: "Java's type system forces you to think about interfaces and contracts upfront. This pays off in large codebases with many developers.",
          exercise: { id: "ex-py-java-oop-1", prompt: "Create an interface `Greetable` with `greet()` returning String. Implement it in `Person` with a name. Print the greeting.", starterCode: "// interface Greetable { ... }\n// class Person implements Greetable { ... }\n", solution: "interface Greetable {\n    String greet();\n}\nclass Person implements Greetable {\n    private String name;\n    public Person(String name) { this.name = name; }\n    public String greet() { return \"Hello, I'm \" + name; }\n}\nSystem.out.println(new Person(\"Ada\").greet());", expectedOutputIncludes: "Hello", xp: 40 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-java-oop-1", prompt: "Python's `@dataclass` is closest to Java's…", choices: ["class", "record (Java 16+)", "interface", "enum"], correctIndex: 1, explanation: "Records auto-generate constructor, getters, equals, hashCode, toString.", xp: 10 },
        { kind: "mcq", id: "q-py-java-oop-2", prompt: "Java uses `_` prefix for private. True?", choices: ["True", "False — Java uses `private` keyword"], correctIndex: 1, explanation: "Java enforces access with keywords: `private`, `protected`, `public`.", xp: 10 },
        { kind: "mcq", id: "q-py-java-oop-3", prompt: "Can a Java class extend multiple classes?", choices: ["Yes", "No — single inheritance only, but multiple interfaces"], correctIndex: 1, explanation: "One `extends`, multiple `implements`.", xp: 10 },
        { kind: "debug", id: "q-py-java-oop-4", prompt: "Why doesn't this compile?", brokenCode: "class Cat extends Animal, Pet { ... }", choices: ["Java only allows single class inheritance — use `extends Animal implements Pet`", "Missing import", "Cat is reserved", "extends is deprecated"], correctIndex: 0, explanation: "If Pet is an interface: `class Cat extends Animal implements Pet`.", xp: 15 },
        { kind: "mcq", id: "q-py-java-oop-5", prompt: "What does `this` refer to in Java?", choices: ["The class itself", "The current instance (like Python's self)", "The parent class", "A static reference"], correctIndex: 1, explanation: "`this` is the current instance — like `self` but implicit in method signatures.", xp: 10 },
      ],
    },
    {
      id: "py-java-errors",
      title: "Error Handling",
      tagline: "Checked exceptions — Java's unique twist.",
      icon: "🔥",
      level: "intermediate",
      order: 2,
      requires: ["py-java-oop"],
      rewardXp: 110,
      lessons: [
        {
          id: "lesson-py-java-err-1",
          title: "Checked and unchecked exceptions",
          intro: "Java has `try/catch/finally` like Python's `try/except/finally`. The big difference: Java has 'checked exceptions' (must be caught or declared with `throws`). `RuntimeException` subclasses are unchecked. Python has no checked exceptions. Java also has `try-with-resources` for auto-closing resources.",
          comparisons: [
            { concept: "Try/except → try/catch", knownCode: "try:\n    val = int(s)\nexcept ValueError as e:\n    print(f'Error: {e}')", targetCode: "try {\n    int val = Integer.parseInt(s);\n} catch (NumberFormatException e) {\n    System.out.println(\"Error: \" + e.getMessage());\n}" },
            { concept: "Raising → Throwing", knownCode: "raise ValueError('bad input')", targetCode: "throw new IllegalArgumentException(\"bad input\");", note: "`throw new` — exceptions are objects created with `new`." },
            { concept: "Context manager → try-with-resources", knownCode: "with open('file.txt') as f:\n    data = f.read()", targetCode: "try (var reader = new BufferedReader(new FileReader(\"file.txt\"))) {\n    String line = reader.readLine();\n}", note: "Auto-closes at end of try block. Implements `AutoCloseable`." },
          ],
          realWorld: "Modern Java increasingly uses unchecked exceptions. Spring, for example, wraps all checked exceptions in unchecked runtime exceptions.",
          exercise: { id: "ex-py-java-err-1", prompt: "Write a try/catch that parses \"abc\" as an int and prints \"Invalid number\" on error.", starterCode: "// Parse \"abc\" safely\n", solution: "try {\n    int n = Integer.parseInt(\"abc\");\n} catch (NumberFormatException e) {\n    System.out.println(\"Invalid number\");\n}", expectedOutputIncludes: "Invalid number", xp: 30 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-java-err-1", prompt: "Python's `except` becomes Java's…", choices: ["except", "catch", "handle", "rescue"], correctIndex: 1, explanation: "Java uses `catch(ExceptionType e)`.", xp: 10 },
        { kind: "mcq", id: "q-py-java-err-2", prompt: "What are checked exceptions?", choices: ["Exceptions checked at runtime", "Exceptions the compiler forces you to handle or declare", "Exceptions that can't be caught", "All exceptions"], correctIndex: 1, explanation: "Checked exceptions (not RuntimeException) must be handled at compile time.", xp: 10 },
        { kind: "mcq", id: "q-py-java-err-3", prompt: "Python's `with` statement is Java's…", choices: ["with block", "try-with-resources", "using block", "synchronized block"], correctIndex: 1, explanation: "Both auto-close resources when the block exits.", xp: 10 },
        { kind: "debug", id: "q-py-java-err-4", prompt: "Why doesn't this compile?", brokenCode: "public void read() {\n    BufferedReader br = new BufferedReader(new FileReader(\"f.txt\"));\n}", choices: ["FileReader throws checked IOException — must catch or declare throws", "BufferedReader is deprecated", "Missing import", "FileReader doesn't exist"], correctIndex: 0, explanation: "Checked exception: add `throws IOException` or wrap in try/catch.", xp: 15 },
        { kind: "mcq", id: "q-py-java-err-5", prompt: "Multi-catch syntax in Java:", choices: ["catch (A, B e)", "catch (A | B e)", "catch A or B e", "except (A, B)"], correctIndex: 1, explanation: "`catch (IOException | SQLException e)` — pipe separates types.", xp: 10 },
      ],
    },
    {
      id: "py-java-modules",
      title: "Packages & Build Tools",
      tagline: "pip → Maven/Gradle, modules → packages.",
      icon: "📦",
      level: "intermediate",
      order: 3,
      requires: ["py-java-errors"],
      rewardXp: 100,
      lessons: [
        {
          id: "lesson-py-java-pkg-1",
          title: "Packages and build systems",
          intro: "Java organizes code into packages (like directories with `__init__.py` but stricter). Package names must match directory structure. Build tools (Maven with `pom.xml`, Gradle with `build.gradle`) replace `pip` and `requirements.txt`. Dependencies come from Maven Central.",
          comparisons: [
            { concept: "Import", knownCode: "from math import sqrt\nfrom mypackage import utils", targetCode: "import java.lang.Math;\nimport com.myapp.utils.Helper;", note: "Java imports are fully qualified class paths." },
            { concept: "Package manager", knownCode: "pip install requests", targetCode: "// Maven: add to pom.xml\n// Gradle: implementation 'group:artifact:version'", note: "Dependencies are declared in build files, not installed globally." },
            { concept: "Project structure", knownCode: "myproject/\n  mypackage/\n    __init__.py\n    utils.py", targetCode: "src/main/java/\n  com/myapp/\n    utils/\n      Helper.java", note: "Maven/Gradle standard layout: `src/main/java/`." },
          ],
          realWorld: "Gradle is modern (used by Android). Maven is enterprise standard. Both download from Maven Central automatically.",
          exercise: { id: "ex-py-java-pkg-1", prompt: "Write the package declaration for a class in `com.example.utils` and import `java.util.List`.", starterCode: "// Package and import\n", solution: "package com.example.utils;\n\nimport java.util.List;", expectedOutputIncludes: "package", xp: 20 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-java-pkg-1", prompt: "Python's `pip` is closest to Java's…", choices: ["javac", "Maven/Gradle", "JVM", "classpath"], correctIndex: 1, explanation: "Maven and Gradle are build tools + dependency managers.", xp: 10 },
        { kind: "mcq", id: "q-py-java-pkg-2", prompt: "Must Java package names match directory structure?", choices: ["No — convention only", "Yes — strictly required", "Only for public classes", "Only with Maven"], correctIndex: 1, explanation: "`package com.app` must be in directory `com/app/`.", xp: 10 },
        { kind: "mcq", id: "q-py-java-pkg-3", prompt: "Python's `__init__.py` is closest to Java's…", choices: ["Main.java", "package-info.java", "The package statement itself", "module-info.java"], correctIndex: 2, explanation: "Java packages are defined by the `package` statement + directory structure.", xp: 10 },
        { kind: "debug", id: "q-py-java-pkg-4", prompt: "Why can't another package access this class?", brokenCode: "package com.app;\nclass Secret { }  // No access modifier!", choices: ["Package-private (default) — add `public` to make it accessible", "Missing import", "class is a keyword", "Package is wrong"], correctIndex: 0, explanation: "No modifier = package-private. Only accessible within the same package.", xp: 15 },
      ],
    },
    {
      id: "py-java-streams",
      title: "Streams & Functional",
      tagline: "Comprehensions → Streams API.",
      icon: "⚡",
      level: "intermediate",
      order: 4,
      requires: ["py-java-modules"],
      rewardXp: 130,
      lessons: [
        {
          id: "lesson-py-java-stream-1",
          title: "Stream API",
          intro: "Java's Stream API (Java 8+) is the closest thing to Python's list comprehensions. Create a stream (`.stream()`), chain operations (`.filter()`, `.map()`, `.sorted()`), and collect results (`.collect(Collectors.toList())`). Streams are lazy — nothing happens until a terminal operation.",
          comparisons: [
            { concept: "Filter + Map", knownCode: "result = [x.upper() for x in names if len(x) > 3]", targetCode: "List<String> result = names.stream()\n    .filter(n -> n.length() > 3)\n    .map(String::toUpperCase)\n    .collect(Collectors.toList());" },
            { concept: "Sum / Reduce", knownCode: "total = sum(nums)", targetCode: "int total = nums.stream()\n    .mapToInt(Integer::intValue)\n    .sum();" },
            { concept: "Dict comprehension → Collectors.toMap", knownCode: "lengths = {w: len(w) for w in words}", targetCode: "Map<String, Integer> lengths = words.stream()\n    .collect(Collectors.toMap(w -> w, String::length));" },
          ],
          realWorld: "Streams are verbose compared to Python but offer parallel processing with `.parallelStream()`. Excellent for data-heavy operations.",
          exercise: { id: "ex-py-java-stream-1", prompt: "Given a List of [1,2,3,4,5], use Streams to filter even numbers, square them, and collect to a list.", starterCode: "List<Integer> nums = List.of(1, 2, 3, 4, 5);\n// Use streams\n", solution: "List<Integer> nums = List.of(1, 2, 3, 4, 5);\nList<Integer> result = nums.stream()\n    .filter(n -> n % 2 == 0)\n    .map(n -> n * n)\n    .collect(Collectors.toList());\nSystem.out.println(result);", expectedOutputIncludes: "[4, 16]", xp: 40 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-java-stream-1", prompt: "Python's `[x*2 for x in nums]` is Java's…", choices: ["nums.map(x -> x*2)", "nums.stream().map(x -> x*2).collect(...)", "Arrays.double(nums)", "nums.forEach(x -> x*2)"], correctIndex: 1, explanation: "Full pipeline: stream → transform → collect.", xp: 10 },
        { kind: "mcq", id: "q-py-java-stream-2", prompt: "When does a Stream execute?", choices: ["Immediately on .map()", "On terminal operation (.collect(), .forEach(), etc.)", "At compile time", "On garbage collection"], correctIndex: 1, explanation: "Streams are lazy — operations build up and execute on terminal operation.", xp: 10 },
        { kind: "mcq", id: "q-py-java-stream-3", prompt: "`String::toUpperCase` is a…", choices: ["Static method call", "Method reference (shorthand for lambda)", "Constructor", "Import"], correctIndex: 1, explanation: "Method reference: equivalent to `s -> s.toUpperCase()`.", xp: 10 },
        { kind: "debug", id: "q-py-java-stream-4", prompt: "Why does the second forEach crash?", brokenCode: "Stream<String> s = names.stream();\ns.forEach(System.out::println);\ns.forEach(System.out::println);  // IllegalStateException!", choices: ["Streams can only be consumed once", "forEach is not terminal", "System.out is closed", "Missing collect()"], correctIndex: 0, explanation: "Streams are single-use. Create a new `.stream()` for each consumption.", xp: 15 },
        { kind: "mcq", id: "q-py-java-stream-5", prompt: "Python's `sum(nums)` is Java's…", choices: ["nums.sum()", "Collections.sum(nums)", "nums.stream().mapToInt(Integer::intValue).sum()", "Math.sum(nums)"], correctIndex: 2, explanation: "Convert to IntStream first, then `.sum()`.", xp: 10 },
      ],
    },
    // ===================== ADVANCED =====================
    {
      id: "py-java-memory",
      title: "JVM & Memory",
      tagline: "From GC-to-GC — but very different beasts.",
      icon: "🧠",
      level: "advanced",
      order: 1,
      requires: [],
      rewardXp: 150,
      lessons: [
        {
          id: "lesson-py-java-mem-1",
          title: "JVM memory model",
          intro: "Both Python and Java have garbage collection, but the JVM is far more sophisticated. The JVM has heap generations (young/old), multiple GC algorithms (G1, ZGC), JIT compilation (C1/C2 compilers), and detailed tuning knobs. Java's GC is generally faster and more predictable than CPython's reference counting.",
          comparisons: [
            { concept: "Object allocation", knownCode: "obj = MyClass()  # Heap + refcount", targetCode: "var obj = new MyClass();  // Heap + generational GC", note: "Both are heap-allocated. Java uses generational GC, not refcount." },
            { concept: "Resource cleanup", knownCode: "with open('f') as f: ...", targetCode: "try (var f = new FileReader(\"f\")) { ... }", note: "Both auto-close resources. Java calls it try-with-resources." },
            { concept: "JIT compilation", knownCode: "# CPython interprets bytecode (no JIT)\n# PyPy has JIT", targetCode: "// JVM JIT-compiles hot methods to native code\n// Much faster than CPython for long-running programs", note: "JVM performance often 10-50x faster than CPython." },
          ],
          realWorld: "For production Java: tune `-Xmx` (max heap), choose GC algorithm (`-XX:+UseZGC` for low latency), and monitor with JFR/JMC.",
          exercise: { id: "ex-py-java-mem-1", prompt: "Write a try-with-resources block using Scanner(System.in) that reads and prints one line.", starterCode: "import java.util.Scanner;\n// try-with-resources\n", solution: "import java.util.Scanner;\ntry (Scanner sc = new Scanner(System.in)) {\n    String line = sc.nextLine();\n    System.out.println(line);\n}", expectedOutputIncludes: "", xp: 35 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-java-mem-1", prompt: "Java's GC is generally… than CPython's.", choices: ["Slower", "Faster and more sophisticated", "Identical", "Non-existent"], correctIndex: 1, explanation: "JVM GC is highly optimized with generations, concurrent collection, and JIT.", xp: 10 },
        { kind: "mcq", id: "q-py-java-mem-2", prompt: "What is JIT compilation?", choices: ["Just-In-Time: compiles hot code to native machine code at runtime", "A build tool", "A testing framework", "A garbage collection algorithm"], correctIndex: 0, explanation: "The JVM identifies hot methods and compiles them to optimized native code.", xp: 10 },
        { kind: "mcq", id: "q-py-java-mem-3", prompt: "`-Xmx512m` sets…", choices: ["Thread count", "Maximum heap size to 512MB", "GC frequency", "JIT threshold"], correctIndex: 1, explanation: "`-Xmx` controls maximum heap size. `-Xms` controls initial size.", xp: 10 },
        { kind: "debug", id: "q-py-java-mem-4", prompt: "What's wrong here?", brokenCode: "FileWriter fw = new FileWriter(\"out.txt\");\nfw.write(\"hello\");\n// fw is never closed!", choices: ["Resource leak — use try-with-resources", "FileWriter is deprecated", "write() doesn't work", "Missing flush"], correctIndex: 0, explanation: "GC frees memory but not file handles. Always close I/O resources.", xp: 15 },
        { kind: "mcq", id: "q-py-java-mem-5", prompt: "Python has a GIL. Does Java?", choices: ["Yes", "No — Java threads run truly in parallel", "Only for I/O", "Only on Windows"], correctIndex: 1, explanation: "Java has real OS threads with true parallelism — no GIL.", xp: 10 },
      ],
    },
    {
      id: "py-java-concurrency",
      title: "Concurrency & Threads",
      tagline: "Real parallelism — no GIL!",
      icon: "🔄",
      level: "advanced",
      order: 2,
      requires: ["py-java-memory"],
      rewardXp: 170,
      lessons: [
        {
          id: "lesson-py-java-conc-1",
          title: "Threading and virtual threads",
          intro: "Python's threading is limited by the GIL. Java threads are real OS threads with true parallelism. Java has synchronized blocks, `java.util.concurrent` utilities, and Java 21+ virtual threads (Project Loom) for scalable concurrency.",
          comparisons: [
            { concept: "Threading", knownCode: "import threading\nt = threading.Thread(target=func)\nt.start(); t.join()", targetCode: "Thread t = new Thread(() -> func());\nt.start();\nt.join();", note: "Java threads are real OS threads — true CPU parallelism!" },
            { concept: "asyncio → Virtual threads", knownCode: "async def main():\n    await asyncio.gather(task1(), task2())", targetCode: "try (var exec = Executors.newVirtualThreadPerTaskExecutor()) {\n    exec.submit(task1);\n    exec.submit(task2);\n}", note: "Virtual threads (Java 21+) scale to millions like asyncio." },
            { concept: "Locks", knownCode: "lock = threading.Lock()\nwith lock: ...", targetCode: "synchronized (lockObj) {\n    // critical section\n}", note: "`synchronized` is built into the language." },
          ],
          realWorld: "Virtual threads (Project Loom) are a game-changer. They make async Java code look synchronous while scaling to millions of concurrent tasks.",
          exercise: { id: "ex-py-java-conc-1", prompt: "Create a thread that prints 'Hello from thread', start it, and join it.", starterCode: "// Create and run a thread\n", solution: "Thread t = new Thread(() -> System.out.println(\"Hello from thread\"));\nt.start();\nt.join();", expectedOutputIncludes: "Hello from thread", xp: 40 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-java-conc-1", prompt: "Java threads vs Python threads:", choices: ["Both limited by GIL", "Java has real parallelism, Python has GIL", "Both are real OS threads", "Neither supports parallelism"], correctIndex: 1, explanation: "Java threads run truly in parallel on multiple cores. Python's GIL prevents this.", xp: 10 },
        { kind: "mcq", id: "q-py-java-conc-2", prompt: "Virtual threads (Java 21+) are…", choices: ["Physical hardware threads", "Lightweight JVM-managed threads that scale to millions", "Deprecated", "GPU threads"], correctIndex: 1, explanation: "Virtual threads are cheap and managed by the JVM, like goroutines or asyncio tasks.", xp: 10 },
        { kind: "mcq", id: "q-py-java-conc-3", prompt: "`synchronized` in Java is like Python's…", choices: ["async/await", "threading.Lock()", "GIL", "multiprocessing"], correctIndex: 1, explanation: "Both provide mutual exclusion for critical sections.", xp: 10 },
        { kind: "debug", id: "q-py-java-conc-4", prompt: "Why doesn't this create a new thread?", brokenCode: "Thread t = new Thread(() -> System.out.println(\"hi\"));\nt.run();  // Not start()!", choices: ["run() executes synchronously — use start() for a new thread", "Lambda syntax is wrong", "Thread is abstract", "Missing import"], correctIndex: 0, explanation: "`run()` calls the method on the current thread. `start()` creates a new OS thread.", xp: 15 },
        { kind: "mcq", id: "q-py-java-conc-5", prompt: "For CPU-bound parallelism, Python uses…", choices: ["threading", "asyncio", "multiprocessing", "concurrent.futures only"], correctIndex: 2, explanation: "Python needs separate processes to bypass the GIL. Java just uses threads.", xp: 10 },
      ],
    },
    {
      id: "py-java-generics",
      title: "Generics & Advanced",
      tagline: "Type parameters, wildcards, and design patterns.",
      icon: "✨",
      level: "advanced",
      order: 3,
      requires: ["py-java-concurrency"],
      rewardXp: 200,
      lessons: [
        {
          id: "lesson-py-java-gen-1",
          title: "Generics and type system",
          intro: "Python uses duck typing and optional type hints. Java uses generics with type erasure — generic info is removed at runtime. Wildcards (`? extends T`, `? super T`) handle covariance. Java's type system is more restrictive but catches more bugs at compile time.",
          comparisons: [
            { concept: "Generic class", knownCode: "class Box:\n    def __init__(self, value):\n        self.value = value", targetCode: "class Box<T> {\n    private T value;\n    public Box(T value) { this.value = value; }\n    public T get() { return value; }\n}" },
            { concept: "Type hints → Generics", knownCode: "def first(items: list[T]) -> T:\n    return items[0]", targetCode: "public <T> T first(List<T> items) {\n    return items.get(0);\n}", note: "Java generics are enforced at compile time. Python hints are optional." },
            { concept: "Protocol → Interface", knownCode: "class Sized(Protocol):\n    def __len__(self) -> int: ...", targetCode: "interface Sized {\n    int size();\n}", note: "Java interfaces are explicit contracts. Python Protocols are structural (duck typing)." },
          ],
          realWorld: "Type erasure means no `new T()` or `instanceof T` at runtime. This is Java's biggest generics limitation.",
          exercise: { id: "ex-py-java-gen-1", prompt: "Create a generic Pair<A, B> class with first and second fields. Create a Pair<String, Integer> and print it.", starterCode: "// class Pair<A, B> { ... }\n", solution: "class Pair<A, B> {\n    private A first;\n    private B second;\n    public Pair(A first, B second) {\n        this.first = first;\n        this.second = second;\n    }\n    public String toString() {\n        return \"(\" + first + \", \" + second + \")\";\n    }\n}\nSystem.out.println(new Pair<>(\"Ada\", 36));", expectedOutputIncludes: "(Ada, 36)", xp: 50 },
        },
      ],
      quiz: [
        { kind: "mcq", id: "q-py-java-gen-1", prompt: "Python type hints are enforced at…", choices: ["Runtime", "Compile time", "Neither — they're optional annotations", "Import time"], correctIndex: 2, explanation: "Python hints are ignored at runtime. Use mypy for static checking.", xp: 10 },
        { kind: "mcq", id: "q-py-java-gen-2", prompt: "Java generics use type erasure. This means…", choices: ["Types are checked at runtime", "Generic type info is removed at compile time", "Generics don't work", "Types are stored in bytecode"], correctIndex: 1, explanation: "At runtime, `List<String>` is just `List`. Type info is erased.", xp: 10 },
        { kind: "mcq", id: "q-py-java-gen-3", prompt: "What does `? extends Number` mean?", choices: ["Any type that extends Number or is Number", "A number with extensions", "An optional number", "Any type that Number extends"], correctIndex: 0, explanation: "Upper bounded wildcard: accepts Number, Integer, Double, etc.", xp: 10 },
        { kind: "debug", id: "q-py-java-gen-4", prompt: "Why doesn't this compile?", brokenCode: "List<int> nums = new ArrayList<>();", choices: ["Generics can't use primitives — use List<Integer>", "ArrayList is wrong", "int is deprecated", "Missing import"], correctIndex: 0, explanation: "Java generics require reference types. Primitives need wrappers.", xp: 15 },
        { kind: "mcq", id: "q-py-java-gen-5", prompt: "PECS stands for…", choices: ["Producer Extends, Consumer Super", "Private Encapsulated Class System", "Public Enum Constructor Syntax", "Parameterized Extended Class Structure"], correctIndex: 0, explanation: "Use `? extends T` for reading, `? super T` for writing.", xp: 10 },
      ],
    },
  ],
};
